ALTER TABLE [dbo].[HASTAINDIRIMLER_DETAY]
    ADD CONSTRAINT [FK_HASTAINDIRIMLER_DETAY_HIZIL] FOREIGN KEY ([KNR], [SNR], [SIRANO]) REFERENCES [dbo].[HIZIL] ([KNR], [SNR], [SIRANO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

