ALTER TABLE [dbo].[HIZMET_KATSAYI]
    ADD CONSTRAINT [FK_HIZMET_KATSAYI_HIZMET] FOREIGN KEY ([TANIM], [GRUP], [CODE]) REFERENCES [dbo].[HIZMET] ([TANIM], [GRUP], [CODE]) ON DELETE NO ACTION ON UPDATE NO ACTION;

