ALTER TABLE [dbo].[HIZMET_DIGER_KOD]
    ADD CONSTRAINT [FK_HIZMET_DIGER_KOD_HIZMET] FOREIGN KEY ([TANIM], [GRUP], [CODE]) REFERENCES [dbo].[HIZMET] ([TANIM], [GRUP], [CODE]) ON DELETE NO ACTION ON UPDATE NO ACTION;

