ALTER TABLE [dbo].[HASTAINDIRIMLER_DETAY]
    ADD CONSTRAINT [FK_HASTAINDIRIMLER_DETAY_HASTAINDIRIMLER] FOREIGN KEY ([HI_ID]) REFERENCES [dbo].[HASTAINDIRIMLER] ([HI_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

