ALTER TABLE [dbo].[HIZMET_DIGER_AD]
    ADD CONSTRAINT [FK_HIZMET_DIGER_AD_HIZMET] FOREIGN KEY ([TANIM], [GRUP], [CODE]) REFERENCES [dbo].[HIZMET] ([TANIM], [GRUP], [CODE]) ON DELETE NO ACTION ON UPDATE NO ACTION;

