ALTER TABLE [dbo].[LABORSONUC]
    ADD CONSTRAINT [FK_LABORSONUC_LBISTE] FOREIGN KEY ([TANIM], [GRUP], [CODE], [KNR], [SNR], [TARIH]) REFERENCES [dbo].[LBISTE] ([TANIM], [GRUP], [CODE], [KNR], [SNR], [TARIH]) ON DELETE NO ACTION ON UPDATE NO ACTION;

