ALTER TABLE [dbo].[LABORTEXT]
    ADD CONSTRAINT [FK_LABORTEXT_LBISTE] FOREIGN KEY ([TANIM], [GRUP], [CODE], [KNR], [SNR], [TARIH]) REFERENCES [dbo].[LBISTE] ([TANIM], [GRUP], [CODE], [KNR], [SNR], [TARIH]) ON DELETE NO ACTION ON UPDATE NO ACTION;

