ALTER TABLE [dbo].[TET_İSTEK]
    ADD CONSTRAINT [FK_TET_İstek_TET_ALT_TABS] FOREIGN KEY ([ARZT], [TAB_CODE], [ALT_TAB_CODE]) REFERENCES [dbo].[TET_ALT_TABS] ([ARZT], [TAB_CODE], [ALT_TAB_CODE]) ON DELETE CASCADE ON UPDATE CASCADE;

