ALTER TABLE [dbo].[TET_COC_ASI_PRO_DETAY]
    ADD CONSTRAINT [FK_TET_COC_ASI_PRO_DETAY_TET_COC_ASI_PRO_TAN] FOREIGN KEY ([PRO_KOD]) REFERENCES [dbo].[TET_COC_ASI_PRO_TAN] ([KOD]) ON DELETE CASCADE ON UPDATE CASCADE;

