ALTER TABLE [dbo].[TET_COC_HASTA_ASI_UYGULAMA]
    ADD CONSTRAINT [FK_TET_COC_HASTA_ASI_UYGULAMA_TET_COC_ASI_TAN] FOREIGN KEY ([ASI_KOD]) REFERENCES [dbo].[TET_COC_ASI_TAN] ([ASI_KOD]) ON DELETE NO ACTION ON UPDATE NO ACTION;

