ALTER TABLE [dbo].[AVANSLAR_IADE]
    ADD CONSTRAINT [PK_AVANSLAR_IADE] PRIMARY KEY NONCLUSTERED ([AV_ID] ASC, [IADEMAKNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

