ALTER TABLE [dbo].[ADRES_IDARM]
    ADD CONSTRAINT [PK_ADRES_IDARM] PRIMARY KEY CLUSTERED ([KNR] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

