ALTER TABLE [dbo].[AVANSLAR]
    ADD CONSTRAINT [PK_AVANSLAR] PRIMARY KEY NONCLUSTERED ([AV_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

