ALTER TABLE [dbo].[ADRES_KATIL]
    ADD CONSTRAINT [PK_ADRES_KATIL] PRIMARY KEY NONCLUSTERED ([KNR] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

