ALTER TABLE [dbo].[BEHAND_1YAZDI]
    ADD CONSTRAINT [PK_BEHAND_1YAZDI] PRIMARY KEY CLUSTERED ([KNR] ASC, [SNR] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

