ALTER TABLE [dbo].[BDOGUM]
    ADD CONSTRAINT [PK_BDOGUM] PRIMARY KEY NONCLUSTERED ([KNR] ASC, [SNR] ASC, [BEBEKNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

