ALTER TABLE [dbo].[BEHAND_DETAY]
    ADD CONSTRAINT [PK_BEHAND_DETAY] PRIMARY KEY NONCLUSTERED ([KNR] ASC, [SNR] ASC, [GELISTARIHI] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

