ALTER TABLE [dbo].[BARKODSCRIPT]
    ADD CONSTRAINT [PK_BARKODSCRIPT] PRIMARY KEY CLUSTERED ([BARKOD_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

