ALTER TABLE [dbo].[DOKTORLAR_CARI]
    ADD CONSTRAINT [PK_DOKTORLAR_CARI] PRIMARY KEY NONCLUSTERED ([CARI_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

