ALTER TABLE [dbo].[DOKTORLAR_MAKBUZ_DETAY]
    ADD CONSTRAINT [PK_DOKTORLAR_MAKBUZ_DETAY] PRIMARY KEY CLUSTERED ([DETAY_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

