ALTER TABLE [dbo].[DOKTOR_STDRAP]
    ADD CONSTRAINT [PK_DOKTOR_STDRAP] PRIMARY KEY CLUSTERED ([TANIM] ASC, [GRUP] ASC, [CODE] ASC, [ARZT] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

