ALTER TABLE [dbo].[DOKTORLAR_HAVUZ]
    ADD CONSTRAINT [PK_DOKTORLAR_HAVUZ] PRIMARY KEY CLUSTERED ([HAVUZ_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

