ALTER TABLE [dbo].[ETKEN_MADDE]
    ADD CONSTRAINT [PK_ETKEN_MADDE] PRIMARY KEY CLUSTERED ([KODU] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

