ALTER TABLE [dbo].[ECZDEVIRSATADR]
    ADD CONSTRAINT [PK_ECZDEVIRSATADR] PRIMARY KEY NONCLUSTERED ([YIL] ASC, [KNR] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

