ALTER TABLE [dbo].[FIYATLISTESIHIZMETGRUBU]
    ADD CONSTRAINT [PK_FIYATLISTESIHIZMETGRUBU] PRIMARY KEY NONCLUSTERED ([FIYLIST] ASC, [TANIM] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

