ALTER TABLE [dbo].[FATURALAR_DETAY]
    ADD CONSTRAINT [PK_FATURALAR_DETAY] PRIMARY KEY NONCLUSTERED ([DET_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

