ALTER TABLE [dbo].[FIYDATA]
    ADD CONSTRAINT [PK_FIYDATA] PRIMARY KEY CLUSTERED ([FIYLIST] ASC, [TANIM] ASC, [GRUP] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

