ALTER TABLE [dbo].[HIZIL]
    ADD CONSTRAINT [PK_HIZIL] PRIMARY KEY NONCLUSTERED ([KNR] ASC, [SNR] ASC, [SIRANO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

