ALTER TABLE [dbo].[HUZUREVI]
    ADD CONSTRAINT [PK_HUZUREVI] PRIMARY KEY NONCLUSTERED ([KNR] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

