ALTER TABLE [dbo].[HIZILTEMP]
    ADD CONSTRAINT [PK_HIZILTEMP] PRIMARY KEY CLUSTERED ([KNR] ASC, [SNR] ASC, [SIRANO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

