ALTER TABLE [dbo].[HASTAINDIRIMLER_DETAY]
    ADD CONSTRAINT [PK_HASTAINDIRIMLER_DETAY] PRIMARY KEY CLUSTERED ([HI_DET_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

