ALTER TABLE [dbo].[HUZUREVI_DETAY]
    ADD CONSTRAINT [PK_HUZUREVI_DETAY] PRIMARY KEY NONCLUSTERED ([KNR] ASC, [SIRANO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

