ALTER TABLE [dbo].[HASTAOTOMATIKTANIMLAR]
    ADD CONSTRAINT [PK_HASTAOTOMATIKTANIMLAR] PRIMARY KEY CLUSTERED ([HOT_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

