ALTER TABLE [dbo].[HASTAINDIRIMLER]
    ADD CONSTRAINT [PK_HASTAINDIRIMLER] PRIMARY KEY CLUSTERED ([HI_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

