ALTER TABLE [dbo].[HASTARONTGENLERI]
    ADD CONSTRAINT [PK_HASTARONTGENLERI] PRIMARY KEY CLUSTERED ([KNR] ASC, [TARIH] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

