ALTER TABLE [dbo].[HASTAOTOMATIKDIGER]
    ADD CONSTRAINT [PK_HASTAOTOMATIKDIGER] PRIMARY KEY CLUSTERED ([KNR] ASC, [SNR] ASC, [OUTG] ASC, [OUTH] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

