ALTER TABLE [dbo].[ICD10_HASTA]
    ADD CONSTRAINT [PK_ICD10_HASTA] PRIMARY KEY NONCLUSTERED ([KNR] ASC, [SNR] ASC, [CH_NO] ASC, [SC_NO] ASC, [SUBSC_NO] ASC, [DT_NO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

