ALTER TABLE [dbo].[ITS]
    ADD CONSTRAINT [PK_ITS] PRIMARY KEY CLUSTERED ([CODE] ASC, [SERINO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

