ALTER TABLE [dbo].[ILACSARF]
    ADD CONSTRAINT [PK_ILACSARF] PRIMARY KEY NONCLUSTERED ([AKOD] ASC, [TANIM] ASC, [GRUP] ASC, [CODE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

