ALTER TABLE [dbo].[KIT_DETAY]
    ADD CONSTRAINT [PK_KIT_DETAY] PRIMARY KEY NONCLUSTERED ([KIT_ID] ASC, [TANIM] ASC, [GRUP] ASC, [CODE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

