ALTER TABLE [dbo].[KURHIZIL]
    ADD CONSTRAINT [PK_KURHIZIL] PRIMARY KEY NONCLUSTERED ([KKNR] ASC, [KNR] ASC, [SNR] ASC, [SIRANO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

