ALTER TABLE [dbo].[KIT_BILGILERI]
    ADD CONSTRAINT [PK_KIT_BILGILERI] PRIMARY KEY NONCLUSTERED ([KIT_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

