ALTER TABLE [dbo].[KURUMINDIRIMORANLARI]
    ADD CONSTRAINT [PK_KURUMINDIRIMORANLARI] PRIMARY KEY NONCLUSTERED ([KNR] ASC, [TANIM] ASC, [GRUP] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

