ALTER TABLE [dbo].[KURUM_EVRAKKAYIP]
    ADD CONSTRAINT [PK_KURUM_EVRAKKAYIP] PRIMARY KEY NONCLUSTERED ([EVRAKNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

