ALTER TABLE [dbo].[KULLANICILAR]
    ADD CONSTRAINT [PK_KULLANICILAR] PRIMARY KEY NONCLUSTERED ([USER_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

