ALTER TABLE [dbo].[KASA_KAPATMA]
    ADD CONSTRAINT [PK_KASA_KAPATMA] PRIMARY KEY NONCLUSTERED ([TARIH] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

