ALTER TABLE [dbo].[KEYDAT]
    ADD CONSTRAINT [PK_KEYDAT] PRIMARY KEY NONCLUSTERED ([SLK] ASC, [SLB] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

