ALTER TABLE [dbo].[LABKITSTOK]
    ADD CONSTRAINT [PK_LABKITSTOK] PRIMARY KEY CLUSTERED ([LABTANIM] ASC, [LABCODE] ASC, [STOKCODE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

