ALTER TABLE [dbo].[LOGHASTAPAYIDEGISTI]
    ADD CONSTRAINT [PK_LOGHASTAPAYIDEGISTI] PRIMARY KEY CLUSTERED ([HPD_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

