ALTER TABLE [dbo].[LABTANIMLARI]
    ADD CONSTRAINT [PK_LABTANIMLARI_1] PRIMARY KEY CLUSTERED ([TANIM] ASC, [GRUP] ASC, [CODE] ASC, [IND] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

