ALTER TABLE [dbo].[LOGODAMERKEZIYATIS]
    ADD CONSTRAINT [PK_LOGODAMERKEZIYATIS] PRIMARY KEY CLUSTERED ([OMY_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

