ALTER TABLE [dbo].[LABORSONUC]
    ADD CONSTRAINT [PK_LABOR] PRIMARY KEY NONCLUSTERED ([KNR] ASC, [SNR] ASC, [TANIM] ASC, [GRUP] ASC, [CODE] ASC, [TARIH] ASC, [IND] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

