ALTER TABLE [dbo].[LOGKURUM_DEGISTI]
    ADD CONSTRAINT [PK_LOGKURUM_DEGISTI] PRIMARY KEY CLUSTERED ([KD_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

