ALTER TABLE [dbo].[muh_login]
    ADD CONSTRAINT [PK_muh_login] PRIMARY KEY CLUSTERED ([user] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

