ALTER TABLE [dbo].[MESAJLAR]
    ADD CONSTRAINT [PK_MESAJLAR] PRIMARY KEY NONCLUSTERED ([TARIH] ASC, [GONDEREN] ASC, [ALICI] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

