ALTER TABLE [dbo].[MEDULA_ORTAKIPLER]
    ADD CONSTRAINT [PK_MEDULA_ORTAKIPLER] PRIMARY KEY CLUSTERED ([TAKIPNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

