ALTER TABLE [dbo].[MEDULA_KULLANICILAR]
    ADD CONSTRAINT [PK_MEDULA_KULLANICI] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

