ALTER TABLE [dbo].[MEDDIABETILACLAR]
    ADD CONSTRAINT [PK_MEDDIABETILACLAR] PRIMARY KEY CLUSTERED ([SNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

