ALTER TABLE [dbo].[NX_HAREKET_KALEMLERI]
    ADD CONSTRAINT [PK_NX_HAREKET_KALEMLERI] PRIMARY KEY CLUSTERED ([HAREKET_ID] ASC, [MALZEME] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

