ALTER TABLE [dbo].[REFAKAT]
    ADD CONSTRAINT [PK_REFAKAT] PRIMARY KEY NONCLUSTERED ([KNR] ASC, [SNR] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

