ALTER TABLE [dbo].[RAPORLAR]
    ADD CONSTRAINT [PK_RAPORLAR] PRIMARY KEY NONCLUSTERED ([KNR] ASC, [SNR] ASC, [RAPORNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

