ALTER TABLE [dbo].[RANDEVU_HASTA]
    ADD CONSTRAINT [PK_RANDEVU_HASTA] PRIMARY KEY NONCLUSTERED ([HASTA_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

