ALTER TABLE [dbo].[SATHIZ]
    ADD CONSTRAINT [PK_SATHIZ] PRIMARY KEY NONCLUSTERED ([KNR] ASC, [SNR] ASC, [AKOD] ASC, [TANIM] ASC, [GRUP] ASC, [CODE] ASC, [BIRIMF] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

