ALTER TABLE [dbo].[SATBEH]
    ADD CONSTRAINT [PK_SATBEH] PRIMARY KEY NONCLUSTERED ([KNR] ASC, [SNR] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

