ALTER TABLE [dbo].[SAGLIKNET_SERVISLER]
    ADD CONSTRAINT [PK_SAGLIKNET_SERVISLER] PRIMARY KEY CLUSTERED ([SLK] ASC, [SLB] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

