ALTER TABLE [dbo].[SATSIPARIS]
    ADD CONSTRAINT [PK_SATSIPARIS] PRIMARY KEY NONCLUSTERED ([SP_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

