ALTER TABLE [dbo].[SEVKLER]
    ADD CONSTRAINT [PK_SEVKLER] PRIMARY KEY NONCLUSTERED ([SEVK_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

