ALTER TABLE [dbo].[KATILIM_PAYI_MUAF_TESHISLER]
    ADD CONSTRAINT [PK_Table1] PRIMARY KEY CLUSTERED ([TESHISKODU] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

