ALTER TABLE [dbo].[TET_COC_ASI_PRO_TAN]
    ADD CONSTRAINT [PK_TET_COC_ASI_PRO_TAN] PRIMARY KEY CLUSTERED ([KOD] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

