ALTER TABLE [dbo].[TET_ALT_TABS]
    ADD CONSTRAINT [PK_TET_ALT_TABS] PRIMARY KEY CLUSTERED ([ARZT] ASC, [TAB_CODE] ASC, [ALT_TAB_CODE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

