ALTER TABLE [dbo].[TMPECZSAYIMLISTESI]
    ADD CONSTRAINT [PK_TMPECZSAYIMLISTESI] PRIMARY KEY NONCLUSTERED ([AKOD] ASC, [TANIM] ASC, [GRUP] ASC, [CODE] ASC, [USER_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

