ALTER TABLE [dbo].[TET_TES_LIST]
    ADD CONSTRAINT [PK_TET_TES_LIST] PRIMARY KEY CLUSTERED ([TANIM] ASC, [TESKOD] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

