ALTER TABLE [dbo].[TET_ADRES_EK]
    ADD CONSTRAINT [PK_TET_ADRES_EK] PRIMARY KEY CLUSTERED ([KNR] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

