ALTER TABLE [dbo].[TET_SABLON]
    ADD CONSTRAINT [PK_tet_sablon] PRIMARY KEY CLUSTERED ([sablon_kod] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

