ALTER TABLE [dbo].[TET_KONS]
    ADD CONSTRAINT [PK_TET_KONS] PRIMARY KEY NONCLUSTERED ([POLKOD] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

