ALTER TABLE [dbo].[TET_TES_TANIM]
    ADD CONSTRAINT [PK_TET_TEST_TANIM] PRIMARY KEY CLUSTERED ([TES_TANIM_CODE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

