ALTER TABLE [dbo].[TET_ILAC_RAPOR]
    ADD CONSTRAINT [PK_TET_ILAC_RAPOR] PRIMARY KEY NONCLUSTERED ([KNR] ASC, [SNR] ASC, [GELTARIH] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

