ALTER TABLE [dbo].[TET_USER_SABLON]
    ADD CONSTRAINT [PK_TET_USER_SABLON] PRIMARY KEY NONCLUSTERED ([USER_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

