ALTER TABLE [dbo].[TET_COCUK_GELISME]
    ADD CONSTRAINT [PK_TET_COCUK_GELISME] PRIMARY KEY CLUSTERED ([KNR] ASC, [TARIH] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

