ALTER TABLE [dbo].[TET_MUAYENE_DETAY_01]
    ADD CONSTRAINT [PK_TET_MUAYENE_DETAY_01] PRIMARY KEY CLUSTERED ([KNR] ASC, [SNR] ASC, [GELISTARIHI] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

