ALTER TABLE [dbo].[TDISTEM]
    ADD CONSTRAINT [PK_TDISTEM] PRIMARY KEY NONCLUSTERED ([ISTEMNO] ASC, [AKOD] ASC, [TANIM] ASC, [GRUP] ASC, [CODE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

