ALTER TABLE [dbo].[wsUBTIPDATA_Log]
    ADD CONSTRAINT [PK_wsUBTIPDATA_Log] PRIMARY KEY CLUSTERED ([LID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

