using System.Collections.Generic; 
using System.Text; 
using System; 


namespace Naz.Hastane.Data.Entities {
    
    public class LOGHIZMETDELETED {
        public LOGHIZMETDELETED() { }
        public virtual string TANIM { get; set; }
        public virtual string GRUP { get; set; }
        public virtual string CODE { get; set; }
        public virtual string OZELKOD { get; set; }
        public virtual string NAME1 { get; set; }
        public virtual double KDV { get; set; }
        public virtual string BUT { get; set; }
        public virtual System.Nullable<int> PARSAYI { get; set; }
        public virtual string MATERYAL { get; set; }
        public virtual string SIRANO { get; set; }
        public virtual string LABTIPI { get; set; }
        public virtual string GELIRGRUBU { get; set; }
        public virtual string OTOISLE { get; set; }
        public virtual double DRYUZDE { get; set; }
        public virtual double PHYUZDE { get; set; }
        public virtual string HAVUZ { get; set; }
        public virtual string KKODU { get; set; }
        public virtual string APHIZMET { get; set; }
        public virtual double PYUZDE { get; set; }
        public virtual string PDAHIL { get; set; }
        public virtual string PAKET { get; set; }
        public virtual string BKODU { get; set; }
        public virtual string YTKHIZMET { get; set; }
        public virtual string HREFAKAT { get; set; }
        public virtual System.Nullable<double> HMALIYET { get; set; }
        public virtual string CODE1 { get; set; }
        public virtual string MEDGONDER { get; set; }
        public virtual string HKILIT { get; set; }
        public virtual string ARZT { get; set; }
        public virtual string ANHIZ { get; set; }
        public virtual string ANAHIZ { get; set; }
        public virtual string IKINCIHIZ { get; set; }
        public virtual string PAKETGRUBU { get; set; }
        public virtual string P { get; set; }
        public virtual string MEDONAY { get; set; }
        public virtual string MBASLIK { get; set; }
        public virtual string KHIZMET { get; set; }
        public virtual string TESTSAAT { get; set; }
        public virtual string MEDSONUC { get; set; }
        public virtual double SATISF00 { get; set; }
        public virtual double KSATISF00 { get; set; }
        public virtual System.Nullable<double> SATISF01 { get; set; }
        public virtual System.Nullable<double> KSATISF01 { get; set; }
        public virtual System.Nullable<double> SATISF02 { get; set; }
        public virtual System.Nullable<double> KSATISF02 { get; set; }
        public virtual System.Nullable<double> SATISF03 { get; set; }
        public virtual System.Nullable<double> KSATISF03 { get; set; }
        public virtual System.Nullable<double> SATISF04 { get; set; }
        public virtual System.Nullable<double> KSATISF04 { get; set; }
        public virtual System.Nullable<double> SATISF05 { get; set; }
        public virtual System.Nullable<double> KSATISF05 { get; set; }
        public virtual System.Nullable<double> SATISF06 { get; set; }
        public virtual System.Nullable<double> KSATISF06 { get; set; }
        public virtual System.Nullable<double> SATISF07 { get; set; }
        public virtual System.Nullable<double> KSATISF07 { get; set; }
        public virtual System.Nullable<double> SATISF08 { get; set; }
        public virtual System.Nullable<double> KSATISF08 { get; set; }
        public virtual System.Nullable<double> SATISF09 { get; set; }
        public virtual System.Nullable<double> KSATISF09 { get; set; }
        public virtual System.Nullable<double> SATISF10 { get; set; }
        public virtual System.Nullable<double> KSATISF10 { get; set; }
        public virtual System.Nullable<double> SATISF11 { get; set; }
        public virtual System.Nullable<double> KSATISF11 { get; set; }
        public virtual System.Nullable<double> SATISF12 { get; set; }
        public virtual System.Nullable<double> KSATISF12 { get; set; }
        public virtual System.Nullable<double> SATISF13 { get; set; }
        public virtual System.Nullable<double> KSATISF13 { get; set; }
        public virtual System.Nullable<double> SATISF14 { get; set; }
        public virtual System.Nullable<double> KSATISF14 { get; set; }
        public virtual System.Nullable<double> SATISF15 { get; set; }
        public virtual System.Nullable<double> KSATISF15 { get; set; }
        public virtual System.Nullable<double> SATISF16 { get; set; }
        public virtual System.Nullable<double> KSATISF16 { get; set; }
        public virtual System.Nullable<double> SATISF17 { get; set; }
        public virtual System.Nullable<double> KSATISF17 { get; set; }
        public virtual System.Nullable<double> SATISF18 { get; set; }
        public virtual System.Nullable<double> KSATISF18 { get; set; }
        public virtual System.Nullable<double> SATISF19 { get; set; }
        public virtual System.Nullable<double> KSATISF19 { get; set; }
        public virtual System.Nullable<double> SATISF20 { get; set; }
        public virtual System.Nullable<double> KSATISF20 { get; set; }
        public virtual System.Nullable<double> SATISF21 { get; set; }
        public virtual System.Nullable<double> KSATISF21 { get; set; }
        public virtual System.Nullable<double> SATISF22 { get; set; }
        public virtual System.Nullable<double> KSATISF22 { get; set; }
        public virtual System.Nullable<double> SATISF23 { get; set; }
        public virtual System.Nullable<double> KSATISF23 { get; set; }
        public virtual System.Nullable<double> SATISF24 { get; set; }
        public virtual System.Nullable<double> KSATISF24 { get; set; }
        public virtual System.Nullable<double> SATISF25 { get; set; }
        public virtual System.Nullable<double> KSATISF25 { get; set; }
        public virtual System.Nullable<double> SATISF26 { get; set; }
        public virtual System.Nullable<double> KSATISF26 { get; set; }
        public virtual System.Nullable<double> SATISF27 { get; set; }
        public virtual System.Nullable<double> KSATISF27 { get; set; }
        public virtual System.Nullable<double> SATISF28 { get; set; }
        public virtual System.Nullable<double> KSATISF28 { get; set; }
        public virtual System.Nullable<double> SATISF29 { get; set; }
        public virtual System.Nullable<double> KSATISF29 { get; set; }
        public virtual System.Nullable<double> SATISF30 { get; set; }
        public virtual System.Nullable<double> KSATISF30 { get; set; }
        public virtual System.Nullable<double> SATISF31 { get; set; }
        public virtual System.Nullable<double> KSATISF31 { get; set; }
        public virtual System.Nullable<double> SATISF32 { get; set; }
        public virtual System.Nullable<double> KSATISF32 { get; set; }
        public virtual System.Nullable<double> SATISF33 { get; set; }
        public virtual System.Nullable<double> KSATISF33 { get; set; }
        public virtual System.Nullable<double> SATISF34 { get; set; }
        public virtual System.Nullable<double> KSATISF34 { get; set; }
        public virtual System.Nullable<double> SATISF35 { get; set; }
        public virtual System.Nullable<double> KSATISF35 { get; set; }
        public virtual System.Nullable<double> SATISF36 { get; set; }
        public virtual System.Nullable<double> KSATISF36 { get; set; }
        public virtual System.Nullable<double> SATISF37 { get; set; }
        public virtual System.Nullable<double> KSATISF37 { get; set; }
        public virtual System.Nullable<double> SATISF38 { get; set; }
        public virtual System.Nullable<double> KSATISF38 { get; set; }
        public virtual System.Nullable<double> SATISF39 { get; set; }
        public virtual System.Nullable<double> KSATISF39 { get; set; }
        public virtual System.Nullable<double> SATISF40 { get; set; }
        public virtual System.Nullable<double> KSATISF40 { get; set; }
        public virtual System.Nullable<double> SATISF41 { get; set; }
        public virtual System.Nullable<double> KSATISF41 { get; set; }
        public virtual System.Nullable<double> SATISF42 { get; set; }
        public virtual System.Nullable<double> KSATISF42 { get; set; }
        public virtual System.Nullable<double> SATISF43 { get; set; }
        public virtual System.Nullable<double> KSATISF43 { get; set; }
        public virtual System.Nullable<double> SATISF44 { get; set; }
        public virtual System.Nullable<double> KSATISF44 { get; set; }
        public virtual System.Nullable<double> SATISF45 { get; set; }
        public virtual System.Nullable<double> KSATISF45 { get; set; }
        public virtual System.Nullable<double> SATISF46 { get; set; }
        public virtual System.Nullable<double> KSATISF46 { get; set; }
        public virtual System.Nullable<double> SATISF47 { get; set; }
        public virtual System.Nullable<double> KSATISF47 { get; set; }
        public virtual System.Nullable<double> SATISF48 { get; set; }
        public virtual System.Nullable<double> KSATISF48 { get; set; }
        public virtual System.Nullable<double> SATISF49 { get; set; }
        public virtual System.Nullable<double> KSATISF49 { get; set; }
        public virtual System.Nullable<double> SATISF50 { get; set; }
        public virtual System.Nullable<double> KSATISF50 { get; set; }
        public virtual System.Nullable<double> SATISF51 { get; set; }
        public virtual System.Nullable<double> KSATISF51 { get; set; }
        public virtual System.Nullable<double> SATISF52 { get; set; }
        public virtual System.Nullable<double> KSATISF52 { get; set; }
        public virtual System.Nullable<double> SATISF53 { get; set; }
        public virtual System.Nullable<double> KSATISF53 { get; set; }
        public virtual System.Nullable<double> SATISF54 { get; set; }
        public virtual System.Nullable<double> KSATISF54 { get; set; }
        public virtual System.Nullable<double> SATISF55 { get; set; }
        public virtual System.Nullable<double> KSATISF55 { get; set; }
        public virtual System.Nullable<double> SATISF56 { get; set; }
        public virtual System.Nullable<double> KSATISF56 { get; set; }
        public virtual System.Nullable<double> SATISF57 { get; set; }
        public virtual System.Nullable<double> KSATISF57 { get; set; }
        public virtual System.Nullable<double> SATISF58 { get; set; }
        public virtual System.Nullable<double> KSATISF58 { get; set; }
        public virtual System.Nullable<double> SATISF59 { get; set; }
        public virtual System.Nullable<double> KSATISF59 { get; set; }
        public virtual System.Nullable<double> SATISF60 { get; set; }
        public virtual System.Nullable<double> KSATISF60 { get; set; }
        public virtual System.Nullable<double> SATISF61 { get; set; }
        public virtual System.Nullable<double> KSATISF61 { get; set; }
        public virtual System.Nullable<double> SATISF62 { get; set; }
        public virtual System.Nullable<double> KSATISF62 { get; set; }
        public virtual System.Nullable<double> SATISF63 { get; set; }
        public virtual System.Nullable<double> KSATISF63 { get; set; }
        public virtual System.Nullable<double> SATISF64 { get; set; }
        public virtual System.Nullable<double> KSATISF64 { get; set; }
        public virtual System.Nullable<double> SATISF65 { get; set; }
        public virtual System.Nullable<double> KSATISF65 { get; set; }
        public virtual System.Nullable<double> SATISF66 { get; set; }
        public virtual System.Nullable<double> KSATISF66 { get; set; }
        public virtual System.Nullable<double> SATISF67 { get; set; }
        public virtual System.Nullable<double> KSATISF67 { get; set; }
        public virtual System.Nullable<double> SATISF68 { get; set; }
        public virtual System.Nullable<double> KSATISF68 { get; set; }
        public virtual System.Nullable<double> SATISF69 { get; set; }
        public virtual System.Nullable<double> KSATISF69 { get; set; }
        public virtual System.Nullable<double> SATISF70 { get; set; }
        public virtual System.Nullable<double> KSATISF70 { get; set; }
        public virtual System.Nullable<double> SATISF71 { get; set; }
        public virtual System.Nullable<double> KSATISF71 { get; set; }
        public virtual System.Nullable<double> SATISF72 { get; set; }
        public virtual System.Nullable<double> KSATISF72 { get; set; }
        public virtual System.Nullable<double> SATISF73 { get; set; }
        public virtual System.Nullable<double> KSATISF73 { get; set; }
        public virtual System.Nullable<double> SATISF74 { get; set; }
        public virtual System.Nullable<double> KSATISF74 { get; set; }
        public virtual System.Nullable<double> SATISF75 { get; set; }
        public virtual System.Nullable<double> KSATISF75 { get; set; }
        public virtual System.Nullable<double> SATISF76 { get; set; }
        public virtual System.Nullable<double> KSATISF76 { get; set; }
        public virtual System.Nullable<double> SATISF77 { get; set; }
        public virtual System.Nullable<double> KSATISF77 { get; set; }
        public virtual System.Nullable<double> SATISF78 { get; set; }
        public virtual System.Nullable<double> KSATISF78 { get; set; }
        public virtual System.Nullable<double> SATISF79 { get; set; }
        public virtual System.Nullable<double> KSATISF79 { get; set; }
        public virtual System.Nullable<double> SATISF80 { get; set; }
        public virtual System.Nullable<double> KSATISF80 { get; set; }
        public virtual System.Nullable<double> SATISF81 { get; set; }
        public virtual System.Nullable<double> KSATISF81 { get; set; }
        public virtual System.Nullable<double> SATISF82 { get; set; }
        public virtual System.Nullable<double> KSATISF82 { get; set; }
        public virtual System.Nullable<double> SATISF83 { get; set; }
        public virtual System.Nullable<double> KSATISF83 { get; set; }
        public virtual System.Nullable<double> SATISF84 { get; set; }
        public virtual System.Nullable<double> KSATISF84 { get; set; }
        public virtual System.Nullable<double> SATISF85 { get; set; }
        public virtual System.Nullable<double> KSATISF85 { get; set; }
        public virtual System.Nullable<double> SATISF86 { get; set; }
        public virtual System.Nullable<double> KSATISF86 { get; set; }
        public virtual System.Nullable<double> SATISF87 { get; set; }
        public virtual System.Nullable<double> KSATISF87 { get; set; }
        public virtual System.Nullable<double> SATISF88 { get; set; }
        public virtual System.Nullable<double> KSATISF88 { get; set; }
        public virtual System.Nullable<double> SATISF89 { get; set; }
        public virtual System.Nullable<double> KSATISF89 { get; set; }
        public virtual System.Nullable<double> SATISF90 { get; set; }
        public virtual System.Nullable<double> KSATISF90 { get; set; }
        public virtual System.Nullable<double> SATISF91 { get; set; }
        public virtual System.Nullable<double> KSATISF91 { get; set; }
        public virtual System.Nullable<double> SATISF92 { get; set; }
        public virtual System.Nullable<double> KSATISF92 { get; set; }
        public virtual System.Nullable<double> SATISF93 { get; set; }
        public virtual System.Nullable<double> KSATISF93 { get; set; }
        public virtual System.Nullable<double> SATISF94 { get; set; }
        public virtual System.Nullable<double> KSATISF94 { get; set; }
        public virtual System.Nullable<double> SATISF95 { get; set; }
        public virtual System.Nullable<double> KSATISF95 { get; set; }
        public virtual System.Nullable<double> SATISF96 { get; set; }
        public virtual System.Nullable<double> KSATISF96 { get; set; }
        public virtual System.Nullable<double> SATISF97 { get; set; }
        public virtual System.Nullable<double> KSATISF97 { get; set; }
        public virtual System.Nullable<double> SATISF98 { get; set; }
        public virtual System.Nullable<double> KSATISF98 { get; set; }
        public virtual System.Nullable<double> SATISF99 { get; set; }
        public virtual System.Nullable<double> KSATISF99 { get; set; }
        public virtual string USER_ID { get; set; }
        public virtual System.Nullable<System.DateTime> DATE_CREATE { get; set; }
        public virtual string USER_ID_UPDATE { get; set; }
        public virtual System.Nullable<System.DateTime> DATE_UPDATE { get; set; }
        public virtual string USER_ID_DELETED { get; set; }
        public virtual System.Nullable<System.DateTime> DATE_DELETED { get; set; }
    }
}
