//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naz.Hastane.Medula.FaturaKayitIslemleri {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servisler.ws.gss.sgk.gov.tr", ConfigurationName="FaturaKayitIslemleri.FaturaKayitIslemleri")]
    public interface FaturaKayitIslemleri {
        
        // CODEGEN: Parameter 'faturaOkuReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="faturaOkuReturn")]
        Naz.Hastane.Medula.FaturaKayitIslemleri.faturaOkuResponse faturaOku(Naz.Hastane.Medula.FaturaKayitIslemleri.faturaOkuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginfaturaOku(Naz.Hastane.Medula.FaturaKayitIslemleri.faturaOkuRequest request, System.AsyncCallback callback, object asyncState);
        
        Naz.Hastane.Medula.FaturaKayitIslemleri.faturaOkuResponse EndfaturaOku(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'faturaIptalReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="faturaIptalReturn")]
        Naz.Hastane.Medula.FaturaKayitIslemleri.faturaIptalResponse faturaIptal(Naz.Hastane.Medula.FaturaKayitIslemleri.faturaIptalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginfaturaIptal(Naz.Hastane.Medula.FaturaKayitIslemleri.faturaIptalRequest request, System.AsyncCallback callback, object asyncState);
        
        Naz.Hastane.Medula.FaturaKayitIslemleri.faturaIptalResponse EndfaturaIptal(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'faturaKayitReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="faturaKayitReturn")]
        Naz.Hastane.Medula.FaturaKayitIslemleri.faturaKayitResponse faturaKayit(Naz.Hastane.Medula.FaturaKayitIslemleri.faturaKayitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginfaturaKayit(Naz.Hastane.Medula.FaturaKayitIslemleri.faturaKayitRequest request, System.AsyncCallback callback, object asyncState);
        
        Naz.Hastane.Medula.FaturaKayitIslemleri.faturaKayitResponse EndfaturaKayit(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'faturaTutarOkuReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="faturaTutarOkuReturn")]
        Naz.Hastane.Medula.FaturaKayitIslemleri.faturaTutarOkuResponse faturaTutarOku(Naz.Hastane.Medula.FaturaKayitIslemleri.faturaTutarOkuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginfaturaTutarOku(Naz.Hastane.Medula.FaturaKayitIslemleri.faturaTutarOkuRequest request, System.AsyncCallback callback, object asyncState);
        
        Naz.Hastane.Medula.FaturaKayitIslemleri.faturaTutarOkuResponse EndfaturaTutarOku(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaOkuGirisDVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faturaRefNoField;
        
        private string faturaTarihiField;
        
        private string faturaTeslimNoField;
        
        private int saglikTesisKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string faturaRefNo {
            get {
                return this.faturaRefNoField;
            }
            set {
                this.faturaRefNoField = value;
                this.RaisePropertyChanged("faturaRefNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string faturaTarihi {
            get {
                return this.faturaTarihiField;
            }
            set {
                this.faturaTarihiField = value;
                this.RaisePropertyChanged("faturaTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string faturaTeslimNo {
            get {
                return this.faturaTeslimNoField;
            }
            set {
                this.faturaTeslimNoField = value;
                this.RaisePropertyChanged("faturaTeslimNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int saglikTesisKodu {
            get {
                return this.saglikTesisKoduField;
            }
            set {
                this.saglikTesisKoduField = value;
                this.RaisePropertyChanged("saglikTesisKodu");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaHataDVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hataKoduField;
        
        private string hataMesajiField;
        
        private string takipNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string hataKodu {
            get {
                return this.hataKoduField;
            }
            set {
                this.hataKoduField = value;
                this.RaisePropertyChanged("hataKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string hataMesaji {
            get {
                return this.hataMesajiField;
            }
            set {
                this.hataMesajiField = value;
                this.RaisePropertyChanged("hataMesaji");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string takipNo {
            get {
                return this.takipNoField;
            }
            set {
                this.takipNoField = value;
                this.RaisePropertyChanged("takipNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaDetayDVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IslemDetayDVO[] islemDetaylariField;
        
        private string takipNoField;
        
        private double takipToplamTutarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IslemDetayDVO[] islemDetaylari {
            get {
                return this.islemDetaylariField;
            }
            set {
                this.islemDetaylariField = value;
                this.RaisePropertyChanged("islemDetaylari");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string takipNo {
            get {
                return this.takipNoField;
            }
            set {
                this.takipNoField = value;
                this.RaisePropertyChanged("takipNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double takipToplamTutar {
            get {
                return this.takipToplamTutarField;
            }
            set {
                this.takipToplamTutarField = value;
                this.RaisePropertyChanged("takipToplamTutar");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class IslemDetayDVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string islemSiraNoField;
        
        private double islemTutariField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string islemSiraNo {
            get {
                return this.islemSiraNoField;
            }
            set {
                this.islemSiraNoField = value;
                this.RaisePropertyChanged("islemSiraNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double islemTutari {
            get {
                return this.islemTutariField;
            }
            set {
                this.islemTutariField = value;
                this.RaisePropertyChanged("islemTutari");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaCevapDVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faturaRefNoField;
        
        private FaturaDetayDVO[] faturaDetaylariField;
        
        private string faturaTeslimNoField;
        
        private double faturaTutariField;
        
        private string hastaBasvuruNoField;
        
        private FaturaHataDVO[] hataliKayitlarField;
        
        private string sonucKoduField;
        
        private string sonucMesajiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string faturaRefNo {
            get {
                return this.faturaRefNoField;
            }
            set {
                this.faturaRefNoField = value;
                this.RaisePropertyChanged("faturaRefNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FaturaDetayDVO[] faturaDetaylari {
            get {
                return this.faturaDetaylariField;
            }
            set {
                this.faturaDetaylariField = value;
                this.RaisePropertyChanged("faturaDetaylari");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string faturaTeslimNo {
            get {
                return this.faturaTeslimNoField;
            }
            set {
                this.faturaTeslimNoField = value;
                this.RaisePropertyChanged("faturaTeslimNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double faturaTutari {
            get {
                return this.faturaTutariField;
            }
            set {
                this.faturaTutariField = value;
                this.RaisePropertyChanged("faturaTutari");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string hastaBasvuruNo {
            get {
                return this.hastaBasvuruNoField;
            }
            set {
                this.hastaBasvuruNoField = value;
                this.RaisePropertyChanged("hastaBasvuruNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FaturaHataDVO[] hataliKayitlar {
            get {
                return this.hataliKayitlarField;
            }
            set {
                this.hataliKayitlarField = value;
                this.RaisePropertyChanged("hataliKayitlar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string sonucKodu {
            get {
                return this.sonucKoduField;
            }
            set {
                this.sonucKoduField = value;
                this.RaisePropertyChanged("sonucKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string sonucMesaji {
            get {
                return this.sonucMesajiField;
            }
            set {
                this.sonucMesajiField = value;
                this.RaisePropertyChanged("sonucMesaji");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class HizmetDetayDVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aciklamaField;
        
        private string protokolNoField;
        
        private string taburcuKoduField;
        
        private string takipNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
                this.RaisePropertyChanged("aciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string protokolNo {
            get {
                return this.protokolNoField;
            }
            set {
                this.protokolNoField = value;
                this.RaisePropertyChanged("protokolNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string taburcuKodu {
            get {
                return this.taburcuKoduField;
            }
            set {
                this.taburcuKoduField = value;
                this.RaisePropertyChanged("taburcuKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string takipNo {
            get {
                return this.takipNoField;
            }
            set {
                this.takipNoField = value;
                this.RaisePropertyChanged("takipNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaGirisDVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faturaRefNoField;
        
        private string faturaTarihiField;
        
        private string hastaBasvuruNoField;
        
        private HizmetDetayDVO[] hizmetDetaylariField;
        
        private int saglikTesisKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string faturaRefNo {
            get {
                return this.faturaRefNoField;
            }
            set {
                this.faturaRefNoField = value;
                this.RaisePropertyChanged("faturaRefNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string faturaTarihi {
            get {
                return this.faturaTarihiField;
            }
            set {
                this.faturaTarihiField = value;
                this.RaisePropertyChanged("faturaTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string hastaBasvuruNo {
            get {
                return this.hastaBasvuruNoField;
            }
            set {
                this.hastaBasvuruNoField = value;
                this.RaisePropertyChanged("hastaBasvuruNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HizmetDetayDVO[] hizmetDetaylari {
            get {
                return this.hizmetDetaylariField;
            }
            set {
                this.hizmetDetaylariField = value;
                this.RaisePropertyChanged("hizmetDetaylari");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int saglikTesisKodu {
            get {
                return this.saglikTesisKoduField;
            }
            set {
                this.saglikTesisKoduField = value;
                this.RaisePropertyChanged("saglikTesisKodu");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaIptalHataliKayitDVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faturaTeslimNoField;
        
        private string hataKoduField;
        
        private string hataMesajiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string faturaTeslimNo {
            get {
                return this.faturaTeslimNoField;
            }
            set {
                this.faturaTeslimNoField = value;
                this.RaisePropertyChanged("faturaTeslimNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string hataKodu {
            get {
                return this.hataKoduField;
            }
            set {
                this.hataKoduField = value;
                this.RaisePropertyChanged("hataKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string hataMesaji {
            get {
                return this.hataMesajiField;
            }
            set {
                this.hataMesajiField = value;
                this.RaisePropertyChanged("hataMesaji");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaIptalCevapDVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FaturaIptalHataliKayitDVO[] hataliKayitlarField;
        
        private string sonucKoduField;
        
        private string sonucMesajiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FaturaIptalHataliKayitDVO[] hataliKayitlar {
            get {
                return this.hataliKayitlarField;
            }
            set {
                this.hataliKayitlarField = value;
                this.RaisePropertyChanged("hataliKayitlar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string sonucKodu {
            get {
                return this.sonucKoduField;
            }
            set {
                this.sonucKoduField = value;
                this.RaisePropertyChanged("sonucKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string sonucMesaji {
            get {
                return this.sonucMesajiField;
            }
            set {
                this.sonucMesajiField = value;
                this.RaisePropertyChanged("sonucMesaji");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaIptalGirisDVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] faturaTeslimNoField;
        
        private int saglikTesisKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] faturaTeslimNo {
            get {
                return this.faturaTeslimNoField;
            }
            set {
                this.faturaTeslimNoField = value;
                this.RaisePropertyChanged("faturaTeslimNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int saglikTesisKodu {
            get {
                return this.saglikTesisKoduField;
            }
            set {
                this.saglikTesisKoduField = value;
                this.RaisePropertyChanged("saglikTesisKodu");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaCevapDetayDVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aciklamaField;
        
        private IslemDetayDVO[] islemDetaylariField;
        
        private string protokolNoField;
        
        private string taburcuKoduField;
        
        private string takipNoField;
        
        private double takipToplamTutarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
                this.RaisePropertyChanged("aciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IslemDetayDVO[] islemDetaylari {
            get {
                return this.islemDetaylariField;
            }
            set {
                this.islemDetaylariField = value;
                this.RaisePropertyChanged("islemDetaylari");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string protokolNo {
            get {
                return this.protokolNoField;
            }
            set {
                this.protokolNoField = value;
                this.RaisePropertyChanged("protokolNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string taburcuKodu {
            get {
                return this.taburcuKoduField;
            }
            set {
                this.taburcuKoduField = value;
                this.RaisePropertyChanged("taburcuKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string takipNo {
            get {
                return this.takipNoField;
            }
            set {
                this.takipNoField = value;
                this.RaisePropertyChanged("takipNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double takipToplamTutar {
            get {
                return this.takipToplamTutarField;
            }
            set {
                this.takipToplamTutarField = value;
                this.RaisePropertyChanged("takipToplamTutar");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaOkuCevapDVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FaturaCevapDetayDVO[] faturaDetaylariField;
        
        private string faturaRefNoField;
        
        private string faturaTarihiField;
        
        private string faturaTeslimNoField;
        
        private double faturaTutariField;
        
        private string sonucKoduField;
        
        private string sonucMesajiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FaturaCevapDetayDVO[] faturaDetaylari {
            get {
                return this.faturaDetaylariField;
            }
            set {
                this.faturaDetaylariField = value;
                this.RaisePropertyChanged("faturaDetaylari");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string faturaRefNo {
            get {
                return this.faturaRefNoField;
            }
            set {
                this.faturaRefNoField = value;
                this.RaisePropertyChanged("faturaRefNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string faturaTarihi {
            get {
                return this.faturaTarihiField;
            }
            set {
                this.faturaTarihiField = value;
                this.RaisePropertyChanged("faturaTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string faturaTeslimNo {
            get {
                return this.faturaTeslimNoField;
            }
            set {
                this.faturaTeslimNoField = value;
                this.RaisePropertyChanged("faturaTeslimNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double faturaTutari {
            get {
                return this.faturaTutariField;
            }
            set {
                this.faturaTutariField = value;
                this.RaisePropertyChanged("faturaTutari");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string sonucKodu {
            get {
                return this.sonucKoduField;
            }
            set {
                this.sonucKoduField = value;
                this.RaisePropertyChanged("sonucKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string sonucMesaji {
            get {
                return this.sonucMesajiField;
            }
            set {
                this.sonucMesajiField = value;
                this.RaisePropertyChanged("sonucMesaji");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="faturaOku", WrapperNamespace="http://servisler.ws.gss.sgk.gov.tr", IsWrapped=true)]
    public partial class faturaOkuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.gss.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaOkuGirisDVO faturaOkuGiris;
        
        public faturaOkuRequest() {
        }
        
        public faturaOkuRequest(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaOkuGirisDVO faturaOkuGiris) {
            this.faturaOkuGiris = faturaOkuGiris;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="faturaOkuResponse", WrapperNamespace="http://servisler.ws.gss.sgk.gov.tr", IsWrapped=true)]
    public partial class faturaOkuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.gss.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaOkuCevapDVO faturaOkuReturn;
        
        public faturaOkuResponse() {
        }
        
        public faturaOkuResponse(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaOkuCevapDVO faturaOkuReturn) {
            this.faturaOkuReturn = faturaOkuReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="faturaIptal", WrapperNamespace="http://servisler.ws.gss.sgk.gov.tr", IsWrapped=true)]
    public partial class faturaIptalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.gss.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaIptalGirisDVO faturaIptalGiris;
        
        public faturaIptalRequest() {
        }
        
        public faturaIptalRequest(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaIptalGirisDVO faturaIptalGiris) {
            this.faturaIptalGiris = faturaIptalGiris;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="faturaIptalResponse", WrapperNamespace="http://servisler.ws.gss.sgk.gov.tr", IsWrapped=true)]
    public partial class faturaIptalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.gss.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaIptalCevapDVO faturaIptalReturn;
        
        public faturaIptalResponse() {
        }
        
        public faturaIptalResponse(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaIptalCevapDVO faturaIptalReturn) {
            this.faturaIptalReturn = faturaIptalReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="faturaKayit", WrapperNamespace="http://servisler.ws.gss.sgk.gov.tr", IsWrapped=true)]
    public partial class faturaKayitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.gss.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaGirisDVO faturaGiris;
        
        public faturaKayitRequest() {
        }
        
        public faturaKayitRequest(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaGirisDVO faturaGiris) {
            this.faturaGiris = faturaGiris;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="faturaKayitResponse", WrapperNamespace="http://servisler.ws.gss.sgk.gov.tr", IsWrapped=true)]
    public partial class faturaKayitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.gss.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaCevapDVO faturaKayitReturn;
        
        public faturaKayitResponse() {
        }
        
        public faturaKayitResponse(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaCevapDVO faturaKayitReturn) {
            this.faturaKayitReturn = faturaKayitReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="faturaTutarOku", WrapperNamespace="http://servisler.ws.gss.sgk.gov.tr", IsWrapped=true)]
    public partial class faturaTutarOkuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.gss.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaGirisDVO faturaOkuGiris;
        
        public faturaTutarOkuRequest() {
        }
        
        public faturaTutarOkuRequest(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaGirisDVO faturaOkuGiris) {
            this.faturaOkuGiris = faturaOkuGiris;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="faturaTutarOkuResponse", WrapperNamespace="http://servisler.ws.gss.sgk.gov.tr", IsWrapped=true)]
    public partial class faturaTutarOkuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.gss.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaCevapDVO faturaTutarOkuReturn;
        
        public faturaTutarOkuResponse() {
        }
        
        public faturaTutarOkuResponse(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaCevapDVO faturaTutarOkuReturn) {
            this.faturaTutarOkuReturn = faturaTutarOkuReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FaturaKayitIslemleriChannel : Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class faturaOkuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public faturaOkuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaOkuCevapDVO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaOkuCevapDVO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class faturaIptalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public faturaIptalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaIptalCevapDVO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaIptalCevapDVO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class faturaKayitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public faturaKayitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaCevapDVO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaCevapDVO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class faturaTutarOkuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public faturaTutarOkuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaCevapDVO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaCevapDVO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FaturaKayitIslemleriClient : System.ServiceModel.ClientBase<Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri>, Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri {
        
        private BeginOperationDelegate onBeginfaturaOkuDelegate;
        
        private EndOperationDelegate onEndfaturaOkuDelegate;
        
        private System.Threading.SendOrPostCallback onfaturaOkuCompletedDelegate;
        
        private BeginOperationDelegate onBeginfaturaIptalDelegate;
        
        private EndOperationDelegate onEndfaturaIptalDelegate;
        
        private System.Threading.SendOrPostCallback onfaturaIptalCompletedDelegate;
        
        private BeginOperationDelegate onBeginfaturaKayitDelegate;
        
        private EndOperationDelegate onEndfaturaKayitDelegate;
        
        private System.Threading.SendOrPostCallback onfaturaKayitCompletedDelegate;
        
        private BeginOperationDelegate onBeginfaturaTutarOkuDelegate;
        
        private EndOperationDelegate onEndfaturaTutarOkuDelegate;
        
        private System.Threading.SendOrPostCallback onfaturaTutarOkuCompletedDelegate;
        
        public FaturaKayitIslemleriClient() {
        }
        
        public FaturaKayitIslemleriClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FaturaKayitIslemleriClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaturaKayitIslemleriClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaturaKayitIslemleriClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<faturaOkuCompletedEventArgs> faturaOkuCompleted;
        
        public event System.EventHandler<faturaIptalCompletedEventArgs> faturaIptalCompleted;
        
        public event System.EventHandler<faturaKayitCompletedEventArgs> faturaKayitCompleted;
        
        public event System.EventHandler<faturaTutarOkuCompletedEventArgs> faturaTutarOkuCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Naz.Hastane.Medula.FaturaKayitIslemleri.faturaOkuResponse Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri.faturaOku(Naz.Hastane.Medula.FaturaKayitIslemleri.faturaOkuRequest request) {
            return base.Channel.faturaOku(request);
        }
        
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaOkuCevapDVO faturaOku(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaOkuGirisDVO faturaOkuGiris) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.faturaOkuRequest inValue = new Naz.Hastane.Medula.FaturaKayitIslemleri.faturaOkuRequest();
            inValue.faturaOkuGiris = faturaOkuGiris;
            Naz.Hastane.Medula.FaturaKayitIslemleri.faturaOkuResponse retVal = ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri)(this)).faturaOku(inValue);
            return retVal.faturaOkuReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri.BeginfaturaOku(Naz.Hastane.Medula.FaturaKayitIslemleri.faturaOkuRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginfaturaOku(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginfaturaOku(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaOkuGirisDVO faturaOkuGiris, System.AsyncCallback callback, object asyncState) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.faturaOkuRequest inValue = new Naz.Hastane.Medula.FaturaKayitIslemleri.faturaOkuRequest();
            inValue.faturaOkuGiris = faturaOkuGiris;
            return ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri)(this)).BeginfaturaOku(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Naz.Hastane.Medula.FaturaKayitIslemleri.faturaOkuResponse Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri.EndfaturaOku(System.IAsyncResult result) {
            return base.Channel.EndfaturaOku(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaOkuCevapDVO EndfaturaOku(System.IAsyncResult result) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.faturaOkuResponse retVal = ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri)(this)).EndfaturaOku(result);
            return retVal.faturaOkuReturn;
        }
        
        private System.IAsyncResult OnBeginfaturaOku(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaOkuGirisDVO faturaOkuGiris = ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaOkuGirisDVO)(inValues[0]));
            return this.BeginfaturaOku(faturaOkuGiris, callback, asyncState);
        }
        
        private object[] OnEndfaturaOku(System.IAsyncResult result) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaOkuCevapDVO retVal = this.EndfaturaOku(result);
            return new object[] {
                    retVal};
        }
        
        private void OnfaturaOkuCompleted(object state) {
            if ((this.faturaOkuCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.faturaOkuCompleted(this, new faturaOkuCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void faturaOkuAsync(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaOkuGirisDVO faturaOkuGiris) {
            this.faturaOkuAsync(faturaOkuGiris, null);
        }
        
        public void faturaOkuAsync(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaOkuGirisDVO faturaOkuGiris, object userState) {
            if ((this.onBeginfaturaOkuDelegate == null)) {
                this.onBeginfaturaOkuDelegate = new BeginOperationDelegate(this.OnBeginfaturaOku);
            }
            if ((this.onEndfaturaOkuDelegate == null)) {
                this.onEndfaturaOkuDelegate = new EndOperationDelegate(this.OnEndfaturaOku);
            }
            if ((this.onfaturaOkuCompletedDelegate == null)) {
                this.onfaturaOkuCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnfaturaOkuCompleted);
            }
            base.InvokeAsync(this.onBeginfaturaOkuDelegate, new object[] {
                        faturaOkuGiris}, this.onEndfaturaOkuDelegate, this.onfaturaOkuCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Naz.Hastane.Medula.FaturaKayitIslemleri.faturaIptalResponse Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri.faturaIptal(Naz.Hastane.Medula.FaturaKayitIslemleri.faturaIptalRequest request) {
            return base.Channel.faturaIptal(request);
        }
        
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaIptalCevapDVO faturaIptal(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaIptalGirisDVO faturaIptalGiris) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.faturaIptalRequest inValue = new Naz.Hastane.Medula.FaturaKayitIslemleri.faturaIptalRequest();
            inValue.faturaIptalGiris = faturaIptalGiris;
            Naz.Hastane.Medula.FaturaKayitIslemleri.faturaIptalResponse retVal = ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri)(this)).faturaIptal(inValue);
            return retVal.faturaIptalReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri.BeginfaturaIptal(Naz.Hastane.Medula.FaturaKayitIslemleri.faturaIptalRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginfaturaIptal(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginfaturaIptal(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaIptalGirisDVO faturaIptalGiris, System.AsyncCallback callback, object asyncState) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.faturaIptalRequest inValue = new Naz.Hastane.Medula.FaturaKayitIslemleri.faturaIptalRequest();
            inValue.faturaIptalGiris = faturaIptalGiris;
            return ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri)(this)).BeginfaturaIptal(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Naz.Hastane.Medula.FaturaKayitIslemleri.faturaIptalResponse Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri.EndfaturaIptal(System.IAsyncResult result) {
            return base.Channel.EndfaturaIptal(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaIptalCevapDVO EndfaturaIptal(System.IAsyncResult result) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.faturaIptalResponse retVal = ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri)(this)).EndfaturaIptal(result);
            return retVal.faturaIptalReturn;
        }
        
        private System.IAsyncResult OnBeginfaturaIptal(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaIptalGirisDVO faturaIptalGiris = ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaIptalGirisDVO)(inValues[0]));
            return this.BeginfaturaIptal(faturaIptalGiris, callback, asyncState);
        }
        
        private object[] OnEndfaturaIptal(System.IAsyncResult result) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaIptalCevapDVO retVal = this.EndfaturaIptal(result);
            return new object[] {
                    retVal};
        }
        
        private void OnfaturaIptalCompleted(object state) {
            if ((this.faturaIptalCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.faturaIptalCompleted(this, new faturaIptalCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void faturaIptalAsync(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaIptalGirisDVO faturaIptalGiris) {
            this.faturaIptalAsync(faturaIptalGiris, null);
        }
        
        public void faturaIptalAsync(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaIptalGirisDVO faturaIptalGiris, object userState) {
            if ((this.onBeginfaturaIptalDelegate == null)) {
                this.onBeginfaturaIptalDelegate = new BeginOperationDelegate(this.OnBeginfaturaIptal);
            }
            if ((this.onEndfaturaIptalDelegate == null)) {
                this.onEndfaturaIptalDelegate = new EndOperationDelegate(this.OnEndfaturaIptal);
            }
            if ((this.onfaturaIptalCompletedDelegate == null)) {
                this.onfaturaIptalCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnfaturaIptalCompleted);
            }
            base.InvokeAsync(this.onBeginfaturaIptalDelegate, new object[] {
                        faturaIptalGiris}, this.onEndfaturaIptalDelegate, this.onfaturaIptalCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Naz.Hastane.Medula.FaturaKayitIslemleri.faturaKayitResponse Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri.faturaKayit(Naz.Hastane.Medula.FaturaKayitIslemleri.faturaKayitRequest request) {
            return base.Channel.faturaKayit(request);
        }
        
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaCevapDVO faturaKayit(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaGirisDVO faturaGiris) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.faturaKayitRequest inValue = new Naz.Hastane.Medula.FaturaKayitIslemleri.faturaKayitRequest();
            inValue.faturaGiris = faturaGiris;
            Naz.Hastane.Medula.FaturaKayitIslemleri.faturaKayitResponse retVal = ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri)(this)).faturaKayit(inValue);
            return retVal.faturaKayitReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri.BeginfaturaKayit(Naz.Hastane.Medula.FaturaKayitIslemleri.faturaKayitRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginfaturaKayit(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginfaturaKayit(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaGirisDVO faturaGiris, System.AsyncCallback callback, object asyncState) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.faturaKayitRequest inValue = new Naz.Hastane.Medula.FaturaKayitIslemleri.faturaKayitRequest();
            inValue.faturaGiris = faturaGiris;
            return ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri)(this)).BeginfaturaKayit(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Naz.Hastane.Medula.FaturaKayitIslemleri.faturaKayitResponse Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri.EndfaturaKayit(System.IAsyncResult result) {
            return base.Channel.EndfaturaKayit(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaCevapDVO EndfaturaKayit(System.IAsyncResult result) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.faturaKayitResponse retVal = ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri)(this)).EndfaturaKayit(result);
            return retVal.faturaKayitReturn;
        }
        
        private System.IAsyncResult OnBeginfaturaKayit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaGirisDVO faturaGiris = ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaGirisDVO)(inValues[0]));
            return this.BeginfaturaKayit(faturaGiris, callback, asyncState);
        }
        
        private object[] OnEndfaturaKayit(System.IAsyncResult result) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaCevapDVO retVal = this.EndfaturaKayit(result);
            return new object[] {
                    retVal};
        }
        
        private void OnfaturaKayitCompleted(object state) {
            if ((this.faturaKayitCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.faturaKayitCompleted(this, new faturaKayitCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void faturaKayitAsync(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaGirisDVO faturaGiris) {
            this.faturaKayitAsync(faturaGiris, null);
        }
        
        public void faturaKayitAsync(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaGirisDVO faturaGiris, object userState) {
            if ((this.onBeginfaturaKayitDelegate == null)) {
                this.onBeginfaturaKayitDelegate = new BeginOperationDelegate(this.OnBeginfaturaKayit);
            }
            if ((this.onEndfaturaKayitDelegate == null)) {
                this.onEndfaturaKayitDelegate = new EndOperationDelegate(this.OnEndfaturaKayit);
            }
            if ((this.onfaturaKayitCompletedDelegate == null)) {
                this.onfaturaKayitCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnfaturaKayitCompleted);
            }
            base.InvokeAsync(this.onBeginfaturaKayitDelegate, new object[] {
                        faturaGiris}, this.onEndfaturaKayitDelegate, this.onfaturaKayitCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Naz.Hastane.Medula.FaturaKayitIslemleri.faturaTutarOkuResponse Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri.faturaTutarOku(Naz.Hastane.Medula.FaturaKayitIslemleri.faturaTutarOkuRequest request) {
            return base.Channel.faturaTutarOku(request);
        }
        
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaCevapDVO faturaTutarOku(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaGirisDVO faturaOkuGiris) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.faturaTutarOkuRequest inValue = new Naz.Hastane.Medula.FaturaKayitIslemleri.faturaTutarOkuRequest();
            inValue.faturaOkuGiris = faturaOkuGiris;
            Naz.Hastane.Medula.FaturaKayitIslemleri.faturaTutarOkuResponse retVal = ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri)(this)).faturaTutarOku(inValue);
            return retVal.faturaTutarOkuReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri.BeginfaturaTutarOku(Naz.Hastane.Medula.FaturaKayitIslemleri.faturaTutarOkuRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginfaturaTutarOku(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginfaturaTutarOku(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaGirisDVO faturaOkuGiris, System.AsyncCallback callback, object asyncState) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.faturaTutarOkuRequest inValue = new Naz.Hastane.Medula.FaturaKayitIslemleri.faturaTutarOkuRequest();
            inValue.faturaOkuGiris = faturaOkuGiris;
            return ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri)(this)).BeginfaturaTutarOku(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Naz.Hastane.Medula.FaturaKayitIslemleri.faturaTutarOkuResponse Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri.EndfaturaTutarOku(System.IAsyncResult result) {
            return base.Channel.EndfaturaTutarOku(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaCevapDVO EndfaturaTutarOku(System.IAsyncResult result) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.faturaTutarOkuResponse retVal = ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaKayitIslemleri)(this)).EndfaturaTutarOku(result);
            return retVal.faturaTutarOkuReturn;
        }
        
        private System.IAsyncResult OnBeginfaturaTutarOku(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaGirisDVO faturaOkuGiris = ((Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaGirisDVO)(inValues[0]));
            return this.BeginfaturaTutarOku(faturaOkuGiris, callback, asyncState);
        }
        
        private object[] OnEndfaturaTutarOku(System.IAsyncResult result) {
            Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaCevapDVO retVal = this.EndfaturaTutarOku(result);
            return new object[] {
                    retVal};
        }
        
        private void OnfaturaTutarOkuCompleted(object state) {
            if ((this.faturaTutarOkuCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.faturaTutarOkuCompleted(this, new faturaTutarOkuCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void faturaTutarOkuAsync(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaGirisDVO faturaOkuGiris) {
            this.faturaTutarOkuAsync(faturaOkuGiris, null);
        }
        
        public void faturaTutarOkuAsync(Naz.Hastane.Medula.FaturaKayitIslemleri.FaturaGirisDVO faturaOkuGiris, object userState) {
            if ((this.onBeginfaturaTutarOkuDelegate == null)) {
                this.onBeginfaturaTutarOkuDelegate = new BeginOperationDelegate(this.OnBeginfaturaTutarOku);
            }
            if ((this.onEndfaturaTutarOkuDelegate == null)) {
                this.onEndfaturaTutarOkuDelegate = new EndOperationDelegate(this.OnEndfaturaTutarOku);
            }
            if ((this.onfaturaTutarOkuCompletedDelegate == null)) {
                this.onfaturaTutarOkuCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnfaturaTutarOkuCompleted);
            }
            base.InvokeAsync(this.onBeginfaturaTutarOkuDelegate, new object[] {
                        faturaOkuGiris}, this.onEndfaturaTutarOkuDelegate, this.onfaturaTutarOkuCompletedDelegate, userState);
        }
    }
}
