select SNR, TANIM, GRUP, CODE, TARIH, NAME1, ADET, SATISF, SIRANO from HIZIL where KNR='870366' and MAKNO='3750476' order by TARIH
select AK.AV_ID, A.TARIH, AK.TUTAR, A.TUTAR as ATUTAR from AVANSLAR_KULLANILAN AK, AVANSLAR A where AK.AV_ID=A.AV_ID and AK.FATURANO='1794821' order by A.TARIH desc

select AV_ID, TARIH, ODEMESEKLI, TUTAR, KULLANILAN, IADEEDILEN, USER_ID,MAKNO,TIPI,AFATNO from AVANSLAR where KNR='870366' and SNR='999' 
	union select AV_ID, TARIH, ODEMESEKLI, TUTAR, KULLANILAN, IADEEDILEN, USER_ID,MAKNO,TIPI,AFATNO from AVANSLAR where KNR='870366' and SNR='' order by 2 desc
	
select SLT from KEYDAT where SLK='00' and SLB='MAKNUM01'
SELECT  TOP 2 *,KATILIM,ODEMESEKLI FROM KASA WHERE    KNR='870366' AND SNR='999' ORDER BY TARIH DESC

