select  DISTINCT(HesapKodu) as HesapKodu,
	F.FTARIH,
	K.SLT as KDVORANI,
	ISNULL(M.HesapAdi,'')+MIN(F.MFATNO)+'-'+MAX(F.MXFATNO) AS ACIKLAMA,
	'TUTAR'= 
      SUM(CASE 
         WHEN CHARINDEX('600', M.HesapKodu) >0  THEN F.TUTAR
         WHEN CHARINDEX('120', M.HesapKodu) >0  THEN F.TUTAR
         WHEN CHARINDEX('391', M.HesapKodu) >0  THEN F.KDVT
		END),
	SUM(F.TUTAR) AS HTUTAR,
	SUM(F.KDVT) AS KDVTUTAR,
	SUM(F.FATT) AS FATTUTAR
from  MuhasebeHesapKodu M
	left join 
	(select KDVORANI,
		MAX(FATURANO) as MXFATNO,
		MIN(FATURANO) as MFATNO ,
		CONVERT(VARCHAR(10),FATURATARIHI , 104) AS FTARIH,
		USER_ID,
		sum(HIZMETTUTARI) as TUTAR,
		sum(KDVTUTARI) AS KDVT,
		sum(FATURATUTARI) AS FATT
	from FATURA 
	where ISIPTAL IS NULL and FATURATARIHI >= '20110104' and FATURATARIHI < '20110105' 
	GROUP BY CONVERT(VARCHAR(10),FATURATARIHI , 104),USER_ID,KDVORANI) F
  on F.USER_ID = M.UserID and M.KDV = F.KDVORANI
LEFT JOIN KEYDAT K ON 
	K.SLB=F.KDVORANI AND
	K.SLK='02' 
GROUP BY M.HesapKodu, M.HesapAdi, F.FTARIH, K.SLT
   having SUM(F.TUTAR) >0
ORDER BY M.HesapKodu
