SELECT KASA.USER_ID, KASA.ODEMESEKLI, KASA.BORCALACAK, SUM(KASA.TUTAR)
FROM KASA  
WHERE KASA.ISIPTAL is null and KASA.TARIH >= '07.11.2011 00:00:00' and KASA.TARIH <= '07.11.2011 23:59:59' 
	and KASA.USER_ID IN ('AYDIN SAKAR','MURACAAT1','MURACAAT2','MURACAAT3','MAKBUZSSK1','HASTA KABUL3','PHARMACY1','PHARMACY2','PHARMACY3','HASTA KABUL1','MEDICAL12','HASTA KABUL2','PHARMACY4','MURACAAT6','MURACAAT4','BAGIS ZIBEC','BAGIS VAKIF','MURACAAT5','MURACAAT8','MURACAAT9','NOBET','MURACAAT12','ECZNOBET','MURACAAT7','GÜRKAN GÜRGEN','SEVAL','MURACAAT10','DURSUN','MURACAAT11','NAYAT','MARYAM','HASTA KABUL12','HASTA KABUL13','HASTA KABUL4','KNAR','MAKBUZSEYMA','SEYMA','ARARAT1','ARARAT2','ARARAT3','MAKBUZARARAT','GURCAN1','GURCAN2','GURCAN3','MAKBUZGURCAN','YETKILI NOBETCI','ARLIN','MAKBUZYATIS','ACC','ACC1','SAYAT ÇINAR','BURAG','MAKBUZSSK','MAKBUZVEZNE','ARZU','AKABI','MESUT') 
group by USER_ID,  ODEMESEKLI, BORCALACAK
order by USER_ID,  ODEMESEKLI, BORCALACAK

update FATURA set KDVORANI='0' where FATURATARIHI > '20110501' and KDVORANI = '8'

