SELECT KASA.MAKNO, KASA.TARIH, HIZIL.*
FROM HIZIL INNER JOIN KASA ON (KASA.TUTAR = HIZIL.SATISF) AND (HIZIL.SNR = KASA.SNR) AND (HIZIL.KNR = KASA.KNR)
WHERE (((HIZIL.CODE)='SGKKATILIM') AND ((HIZIL.MAKNO) Is Null) AND ((KASA.ISIPTAL) Is Null) AND ((KASA.MAKBUZTIPI)='V'))
order by KASA.TARIH desc


