SELECT KASA.MAKNO, KASA.TARIH, HIZIL.*
FROM HIZIL (NOLOCK)
	INNER JOIN KASA (NOLOCK) 
		ON (KASA.TUTAR = HIZIL.SATISF) AND (HIZIL.SNR = KASA.SNR) AND (HIZIL.KNR = KASA.KNR)
WHERE (((HIZIL.CODE)='SGKKATILIM') AND ((HIZIL.MAKNO) Is Null) AND ((KASA.ISIPTAL) Is Null) AND ((KASA.MAKBUZTIPI)='V'))
order by KASA.TARIH desc


SELECT KASA.MAKNO, KASA.TARIH, HIZIL.*
FROM HIZIL (NOLOCK)
	INNER JOIN KASA (NOLOCK) 
		ON (KASA.TUTAR = 15) and HIZIL.SATISF = 13.89 AND (HIZIL.SNR = KASA.SNR) AND (HIZIL.KNR = KASA.KNR)
WHERE HIZIL.MAKNO Is Null AND KASA.ISIPTAL Is Null and KASA.TARIH >= '20110101'
order by KASA.TARIH desc


