UPDATE HIZIL 
SET HIZIL.MAKNO = KASA.MAKNO, HIZIL.USER_ID_UPDATE = 'AYDIN SAKAR', HIZIL.DATE_UPDATE = '20110722'
FROM HIZIL (NOLOCK)
	INNER JOIN KASA (NOLOCK) 
		ON (KASA.TUTAR = HIZIL.SATISF) AND (HIZIL.SNR = KASA.SNR) AND (HIZIL.KNR = KASA.KNR)
WHERE (((HIZIL.CODE)='SGKKATILIM') AND ((HIZIL.MAKNO) Is Null) AND ((KASA.ISIPTAL) Is Null) AND ((KASA.MAKBUZTIPI)='V'))


UPDATE HIZIL 
SET HIZIL.MAKNO = FATURA.MAKNO, HIZIL.USER_ID_UPDATE = 'AYDIN SAKAR', HIZIL.DATE_UPDATE = '20110722'
FROM HIZIL (NOLOCK)
	INNER JOIN KASA (NOLOCK) 
		ON (KASA.TUTAR = 15) and HIZIL.SATISF = 13.89 AND (HIZIL.SNR = KASA.SNR) AND (HIZIL.KNR = KASA.KNR)
	INNER JOIN FATURA (NOLOCK)
		ON KASA.FATURANO = FATURA.FATURA_ID
WHERE HIZIL.MAKNO Is Null AND KASA.ISIPTAL Is Null and KASA.TARIH >= '20110101'

