//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace meno.MyWSDL_F00 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RaporIslemleriSoapBinding", Namespace="http://servisler.ws.gss.sgk.gov.tr")]
    public partial class RaporIslemleriService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback takipNoileRaporBilgisiKaydetOperationCompleted;
        
        private System.Threading.SendOrPostCallback raporBilgisiBulOperationCompleted;
        
        private System.Threading.SendOrPostCallback raporUzatOperationCompleted;
        
        private System.Threading.SendOrPostCallback raporBilgisiKaydetOperationCompleted;
        
        private System.Threading.SendOrPostCallback raporBilgisiSilOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RaporIslemleriService() {
            this.Url = global::meno.Properties.Settings.Default.meno_MyWSDL_F00_RaporIslemleriService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event takipNoileRaporBilgisiKaydetCompletedEventHandler takipNoileRaporBilgisiKaydetCompleted;
        
        /// <remarks/>
        public event raporBilgisiBulCompletedEventHandler raporBilgisiBulCompleted;
        
        /// <remarks/>
        public event raporUzatCompletedEventHandler raporUzatCompleted;
        
        /// <remarks/>
        public event raporBilgisiKaydetCompletedEventHandler raporBilgisiKaydetCompleted;
        
        /// <remarks/>
        public event raporBilgisiSilCompletedEventHandler raporBilgisiSilCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servisler.ws.gss.sgk.gov.tr", ResponseNamespace="http://servisler.ws.gss.sgk.gov.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("takipNoileRaporBilgisiKaydetReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RaporCevapDVO takipNoileRaporBilgisiKaydet([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] RaporGirisDVO raporGiris) {
            object[] results = this.Invoke("takipNoileRaporBilgisiKaydet", new object[] {
                        raporGiris});
            return ((RaporCevapDVO)(results[0]));
        }
        
        /// <remarks/>
        public void takipNoileRaporBilgisiKaydetAsync(RaporGirisDVO raporGiris) {
            this.takipNoileRaporBilgisiKaydetAsync(raporGiris, null);
        }
        
        /// <remarks/>
        public void takipNoileRaporBilgisiKaydetAsync(RaporGirisDVO raporGiris, object userState) {
            if ((this.takipNoileRaporBilgisiKaydetOperationCompleted == null)) {
                this.takipNoileRaporBilgisiKaydetOperationCompleted = new System.Threading.SendOrPostCallback(this.OntakipNoileRaporBilgisiKaydetOperationCompleted);
            }
            this.InvokeAsync("takipNoileRaporBilgisiKaydet", new object[] {
                        raporGiris}, this.takipNoileRaporBilgisiKaydetOperationCompleted, userState);
        }
        
        private void OntakipNoileRaporBilgisiKaydetOperationCompleted(object arg) {
            if ((this.takipNoileRaporBilgisiKaydetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.takipNoileRaporBilgisiKaydetCompleted(this, new takipNoileRaporBilgisiKaydetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servisler.ws.gss.sgk.gov.tr", ResponseNamespace="http://servisler.ws.gss.sgk.gov.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("raporBilgisiBulReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RaporCevapDVO raporBilgisiBul([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] RaporSorguDVO raporBilgisi) {
            object[] results = this.Invoke("raporBilgisiBul", new object[] {
                        raporBilgisi});
            return ((RaporCevapDVO)(results[0]));
        }
        
        /// <remarks/>
        public void raporBilgisiBulAsync(RaporSorguDVO raporBilgisi) {
            this.raporBilgisiBulAsync(raporBilgisi, null);
        }
        
        /// <remarks/>
        public void raporBilgisiBulAsync(RaporSorguDVO raporBilgisi, object userState) {
            if ((this.raporBilgisiBulOperationCompleted == null)) {
                this.raporBilgisiBulOperationCompleted = new System.Threading.SendOrPostCallback(this.OnraporBilgisiBulOperationCompleted);
            }
            this.InvokeAsync("raporBilgisiBul", new object[] {
                        raporBilgisi}, this.raporBilgisiBulOperationCompleted, userState);
        }
        
        private void OnraporBilgisiBulOperationCompleted(object arg) {
            if ((this.raporBilgisiBulCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.raporBilgisiBulCompleted(this, new raporBilgisiBulCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servisler.ws.gss.sgk.gov.tr", ResponseNamespace="http://servisler.ws.gss.sgk.gov.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("raporUzatReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RaporUzatCevapDVO raporUzat([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] IsgoremezlikRaporEkDVO isgoremezlikRaporEkDVO) {
            object[] results = this.Invoke("raporUzat", new object[] {
                        isgoremezlikRaporEkDVO});
            return ((RaporUzatCevapDVO)(results[0]));
        }
        
        /// <remarks/>
        public void raporUzatAsync(IsgoremezlikRaporEkDVO isgoremezlikRaporEkDVO) {
            this.raporUzatAsync(isgoremezlikRaporEkDVO, null);
        }
        
        /// <remarks/>
        public void raporUzatAsync(IsgoremezlikRaporEkDVO isgoremezlikRaporEkDVO, object userState) {
            if ((this.raporUzatOperationCompleted == null)) {
                this.raporUzatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnraporUzatOperationCompleted);
            }
            this.InvokeAsync("raporUzat", new object[] {
                        isgoremezlikRaporEkDVO}, this.raporUzatOperationCompleted, userState);
        }
        
        private void OnraporUzatOperationCompleted(object arg) {
            if ((this.raporUzatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.raporUzatCompleted(this, new raporUzatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servisler.ws.gss.sgk.gov.tr", ResponseNamespace="http://servisler.ws.gss.sgk.gov.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("raporBilgisiKaydetReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RaporCevapDVO raporBilgisiKaydet([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] RaporGirisDVO raporGiris) {
            object[] results = this.Invoke("raporBilgisiKaydet", new object[] {
                        raporGiris});
            return ((RaporCevapDVO)(results[0]));
        }
        
        /// <remarks/>
        public void raporBilgisiKaydetAsync(RaporGirisDVO raporGiris) {
            this.raporBilgisiKaydetAsync(raporGiris, null);
        }
        
        /// <remarks/>
        public void raporBilgisiKaydetAsync(RaporGirisDVO raporGiris, object userState) {
            if ((this.raporBilgisiKaydetOperationCompleted == null)) {
                this.raporBilgisiKaydetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnraporBilgisiKaydetOperationCompleted);
            }
            this.InvokeAsync("raporBilgisiKaydet", new object[] {
                        raporGiris}, this.raporBilgisiKaydetOperationCompleted, userState);
        }
        
        private void OnraporBilgisiKaydetOperationCompleted(object arg) {
            if ((this.raporBilgisiKaydetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.raporBilgisiKaydetCompleted(this, new raporBilgisiKaydetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servisler.ws.gss.sgk.gov.tr", ResponseNamespace="http://servisler.ws.gss.sgk.gov.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("raporBilgisiSilReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RaporCevapDVO raporBilgisiSil([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] RaporSorguDVO raporBilgisi) {
            object[] results = this.Invoke("raporBilgisiSil", new object[] {
                        raporBilgisi});
            return ((RaporCevapDVO)(results[0]));
        }
        
        /// <remarks/>
        public void raporBilgisiSilAsync(RaporSorguDVO raporBilgisi) {
            this.raporBilgisiSilAsync(raporBilgisi, null);
        }
        
        /// <remarks/>
        public void raporBilgisiSilAsync(RaporSorguDVO raporBilgisi, object userState) {
            if ((this.raporBilgisiSilOperationCompleted == null)) {
                this.raporBilgisiSilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnraporBilgisiSilOperationCompleted);
            }
            this.InvokeAsync("raporBilgisiSil", new object[] {
                        raporBilgisi}, this.raporBilgisiSilOperationCompleted, userState);
        }
        
        private void OnraporBilgisiSilOperationCompleted(object arg) {
            if ((this.raporBilgisiSilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.raporBilgisiSilCompleted(this, new raporBilgisiSilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class RaporGirisDVO {
        
        private AnalikIsgoremezlikRaporDVO analikRaporField;
        
        private DogumOncesiCalisabilirRaporDVO dogumOncesiCalisabilirRaporField;
        
        private DogumRaporDVO dogumRaporField;
        
        private IlacRaporDVO ilacRaporField;
        
        private MaluliyetRaporDVO maluliyetRaporField;
        
        private ProtezRaporDVO protezRaporField;
        
        private TedaviRaporDVO tedaviRaporField;
        
        private IsgoremezlikRaporDVO isgoremezlikRaporField;
        
        private int kullaniciTesisKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public AnalikIsgoremezlikRaporDVO analikRapor {
            get {
                return this.analikRaporField;
            }
            set {
                this.analikRaporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public DogumOncesiCalisabilirRaporDVO dogumOncesiCalisabilirRapor {
            get {
                return this.dogumOncesiCalisabilirRaporField;
            }
            set {
                this.dogumOncesiCalisabilirRaporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public DogumRaporDVO dogumRapor {
            get {
                return this.dogumRaporField;
            }
            set {
                this.dogumRaporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public IlacRaporDVO ilacRapor {
            get {
                return this.ilacRaporField;
            }
            set {
                this.ilacRaporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public MaluliyetRaporDVO maluliyetRapor {
            get {
                return this.maluliyetRaporField;
            }
            set {
                this.maluliyetRaporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ProtezRaporDVO protezRapor {
            get {
                return this.protezRaporField;
            }
            set {
                this.protezRaporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public TedaviRaporDVO tedaviRapor {
            get {
                return this.tedaviRaporField;
            }
            set {
                this.tedaviRaporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public IsgoremezlikRaporDVO isgoremezlikRapor {
            get {
                return this.isgoremezlikRaporField;
            }
            set {
                this.isgoremezlikRaporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int kullaniciTesisKodu {
            get {
                return this.kullaniciTesisKoduField;
            }
            set {
                this.kullaniciTesisKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class AnalikIsgoremezlikRaporDVO {
        
        private string bebekDogumTarihiField;
        
        private int cocukSayisiField;
        
        private RaporDVO raporDVOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bebekDogumTarihi {
            get {
                return this.bebekDogumTarihiField;
            }
            set {
                this.bebekDogumTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cocukSayisi {
            get {
                return this.cocukSayisiField;
            }
            set {
                this.cocukSayisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RaporDVO raporDVO {
            get {
                return this.raporDVOField;
            }
            set {
                this.raporDVOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class RaporDVO {
        
        private string aciklamaField;
        
        private string baslangicTarihiField;
        
        private string bitisTarihiField;
        
        private DoktorBilgisiDVO[] doktorlarField;
        
        private string durumField;
        
        private string duzenlemeTuruField;
        
        private string protokolNoField;
        
        private string protokolTarihiField;
        
        private TaniBilgisiDVO[] tanilarField;
        
        private string turuField;
        
        private RaporBilgisiDVO raporBilgisiField;
        
        private HakSahibiBilgisiDVO hakSahibiField;
        
        private string takipNoField;
        
        private string klinikTaniField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string baslangicTarihi {
            get {
                return this.baslangicTarihiField;
            }
            set {
                this.baslangicTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bitisTarihi {
            get {
                return this.bitisTarihiField;
            }
            set {
                this.bitisTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DoktorBilgisiDVO[] doktorlar {
            get {
                return this.doktorlarField;
            }
            set {
                this.doktorlarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string durum {
            get {
                return this.durumField;
            }
            set {
                this.durumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string duzenlemeTuru {
            get {
                return this.duzenlemeTuruField;
            }
            set {
                this.duzenlemeTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string protokolNo {
            get {
                return this.protokolNoField;
            }
            set {
                this.protokolNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string protokolTarihi {
            get {
                return this.protokolTarihiField;
            }
            set {
                this.protokolTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TaniBilgisiDVO[] tanilar {
            get {
                return this.tanilarField;
            }
            set {
                this.tanilarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string turu {
            get {
                return this.turuField;
            }
            set {
                this.turuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RaporBilgisiDVO raporBilgisi {
            get {
                return this.raporBilgisiField;
            }
            set {
                this.raporBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public HakSahibiBilgisiDVO hakSahibi {
            get {
                return this.hakSahibiField;
            }
            set {
                this.hakSahibiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string takipNo {
            get {
                return this.takipNoField;
            }
            set {
                this.takipNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string klinikTani {
            get {
                return this.klinikTaniField;
            }
            set {
                this.klinikTaniField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class DoktorBilgisiDVO {
        
        private string drAdiField;
        
        private string drSoyadiField;
        
        private string tipiField;
        
        private string drBransKoduField;
        
        private string drTescilNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string drAdi {
            get {
                return this.drAdiField;
            }
            set {
                this.drAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string drSoyadi {
            get {
                return this.drSoyadiField;
            }
            set {
                this.drSoyadiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string tipi {
            get {
                return this.tipiField;
            }
            set {
                this.tipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string drBransKodu {
            get {
                return this.drBransKoduField;
            }
            set {
                this.drBransKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string drTescilNo {
            get {
                return this.drTescilNoField;
            }
            set {
                this.drTescilNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class RaporUzatCevapDVO {
        
        private string sonucAciklamasiField;
        
        private int sonucKoduField;
        
        private IsgoremezlikRaporEkDVO isgoremezlikRaporEkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sonucAciklamasi {
            get {
                return this.sonucAciklamasiField;
            }
            set {
                this.sonucAciklamasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sonucKodu {
            get {
                return this.sonucKoduField;
            }
            set {
                this.sonucKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public IsgoremezlikRaporEkDVO isgoremezlikRaporEk {
            get {
                return this.isgoremezlikRaporEkField;
            }
            set {
                this.isgoremezlikRaporEkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class IsgoremezlikRaporEkDVO {
        
        private string aciklamaField;
        
        private string bitisTarihiField;
        
        private string durumField;
        
        private string duzenlemeTuruField;
        
        private string hastaYatisVarMiField;
        
        private string kontrolMuField;
        
        private string kontrolTarihiField;
        
        private string protokolNoField;
        
        private string protokolTarihiField;
        
        private HastaYatisBilgisiDVO[] yatislarField;
        
        private RaporBilgisiDVO raporBilgisiDVOField;
        
        private DoktorBilgisiDVO[] doktorlarField;
        
        private TaniBilgisiDVO[] tanilarField;
        
        private int kullaniciTesisKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bitisTarihi {
            get {
                return this.bitisTarihiField;
            }
            set {
                this.bitisTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string durum {
            get {
                return this.durumField;
            }
            set {
                this.durumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string duzenlemeTuru {
            get {
                return this.duzenlemeTuruField;
            }
            set {
                this.duzenlemeTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hastaYatisVarMi {
            get {
                return this.hastaYatisVarMiField;
            }
            set {
                this.hastaYatisVarMiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string kontrolMu {
            get {
                return this.kontrolMuField;
            }
            set {
                this.kontrolMuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string kontrolTarihi {
            get {
                return this.kontrolTarihiField;
            }
            set {
                this.kontrolTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string protokolNo {
            get {
                return this.protokolNoField;
            }
            set {
                this.protokolNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string protokolTarihi {
            get {
                return this.protokolTarihiField;
            }
            set {
                this.protokolTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HastaYatisBilgisiDVO[] yatislar {
            get {
                return this.yatislarField;
            }
            set {
                this.yatislarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RaporBilgisiDVO raporBilgisiDVO {
            get {
                return this.raporBilgisiDVOField;
            }
            set {
                this.raporBilgisiDVOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DoktorBilgisiDVO[] doktorlar {
            get {
                return this.doktorlarField;
            }
            set {
                this.doktorlarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TaniBilgisiDVO[] tanilar {
            get {
                return this.tanilarField;
            }
            set {
                this.tanilarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int kullaniciTesisKodu {
            get {
                return this.kullaniciTesisKoduField;
            }
            set {
                this.kullaniciTesisKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class HastaYatisBilgisiDVO {
        
        private string cikisTarihiField;
        
        private string yatisTarihiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string cikisTarihi {
            get {
                return this.cikisTarihiField;
            }
            set {
                this.cikisTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string yatisTarihi {
            get {
                return this.yatisTarihiField;
            }
            set {
                this.yatisTarihiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class RaporBilgisiDVO {
        
        private string noField;
        
        private string tarihField;
        
        private int raporTesisKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string no {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string tarih {
            get {
                return this.tarihField;
            }
            set {
                this.tarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int raporTesisKodu {
            get {
                return this.raporTesisKoduField;
            }
            set {
                this.raporTesisKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class TaniBilgisiDVO {
        
        private string taniKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string taniKodu {
            get {
                return this.taniKoduField;
            }
            set {
                this.taniKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class RaporSorguDVO {
        
        private int kullaniciTesisKoduField;
        
        private RaporBilgisiDVO raporBilgisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int kullaniciTesisKodu {
            get {
                return this.kullaniciTesisKoduField;
            }
            set {
                this.kullaniciTesisKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RaporBilgisiDVO raporBilgisi {
            get {
                return this.raporBilgisiField;
            }
            set {
                this.raporBilgisiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class RaporCevapDVO {
        
        private AnalikIsgoremezlikRaporDVO analikRaporField;
        
        private DogumOncesiCalisabilirRaporDVO dogumOncesiCalisabilirRaporField;
        
        private DogumRaporDVO dogumRaporField;
        
        private IlacRaporDVO ilacRaporField;
        
        private MaluliyetRaporDVO maluliyetRaporField;
        
        private ProtezRaporDVO protezRaporField;
        
        private TedaviRaporDVO tedaviRaporField;
        
        private IsgoremezlikRaporDVO isgoremezlikRaporField;
        
        private IsgoremezlikRaporEkDVO[] isgoremezlikRaporEkleriField;
        
        private string sonucAciklamasiField;
        
        private int sonucKoduField;
        
        private string raporTuruField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public AnalikIsgoremezlikRaporDVO analikRapor {
            get {
                return this.analikRaporField;
            }
            set {
                this.analikRaporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public DogumOncesiCalisabilirRaporDVO dogumOncesiCalisabilirRapor {
            get {
                return this.dogumOncesiCalisabilirRaporField;
            }
            set {
                this.dogumOncesiCalisabilirRaporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public DogumRaporDVO dogumRapor {
            get {
                return this.dogumRaporField;
            }
            set {
                this.dogumRaporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public IlacRaporDVO ilacRapor {
            get {
                return this.ilacRaporField;
            }
            set {
                this.ilacRaporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public MaluliyetRaporDVO maluliyetRapor {
            get {
                return this.maluliyetRaporField;
            }
            set {
                this.maluliyetRaporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ProtezRaporDVO protezRapor {
            get {
                return this.protezRaporField;
            }
            set {
                this.protezRaporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public TedaviRaporDVO tedaviRapor {
            get {
                return this.tedaviRaporField;
            }
            set {
                this.tedaviRaporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public IsgoremezlikRaporDVO isgoremezlikRapor {
            get {
                return this.isgoremezlikRaporField;
            }
            set {
                this.isgoremezlikRaporField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IsgoremezlikRaporEkDVO[] isgoremezlikRaporEkleri {
            get {
                return this.isgoremezlikRaporEkleriField;
            }
            set {
                this.isgoremezlikRaporEkleriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sonucAciklamasi {
            get {
                return this.sonucAciklamasiField;
            }
            set {
                this.sonucAciklamasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sonucKodu {
            get {
                return this.sonucKoduField;
            }
            set {
                this.sonucKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string raporTuru {
            get {
                return this.raporTuruField;
            }
            set {
                this.raporTuruField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class DogumOncesiCalisabilirRaporDVO {
        
        private string bebekDogumTarihiField;
        
        private string dogumIzniBaslangicTarihiField;
        
        private RaporDVO raporDVOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bebekDogumTarihi {
            get {
                return this.bebekDogumTarihiField;
            }
            set {
                this.bebekDogumTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string dogumIzniBaslangicTarihi {
            get {
                return this.dogumIzniBaslangicTarihiField;
            }
            set {
                this.dogumIzniBaslangicTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RaporDVO raporDVO {
            get {
                return this.raporDVOField;
            }
            set {
                this.raporDVOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class DogumRaporDVO {
        
        private string anesteziTipiField;
        
        private string bebekDogumTarihiField;
        
        private int canliCocukSayisiField;
        
        private CocukBilgisiDVO[] cocuklarField;
        
        private int cocukSayisiField;
        
        private string dogumTipiField;
        
        private string epizyotemiField;
        
        private RaporDVO raporDVOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string anesteziTipi {
            get {
                return this.anesteziTipiField;
            }
            set {
                this.anesteziTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bebekDogumTarihi {
            get {
                return this.bebekDogumTarihiField;
            }
            set {
                this.bebekDogumTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int canliCocukSayisi {
            get {
                return this.canliCocukSayisiField;
            }
            set {
                this.canliCocukSayisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CocukBilgisiDVO[] cocuklar {
            get {
                return this.cocuklarField;
            }
            set {
                this.cocuklarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cocukSayisi {
            get {
                return this.cocukSayisiField;
            }
            set {
                this.cocukSayisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string dogumTipi {
            get {
                return this.dogumTipiField;
            }
            set {
                this.dogumTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string epizyotemi {
            get {
                return this.epizyotemiField;
            }
            set {
                this.epizyotemiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RaporDVO raporDVO {
            get {
                return this.raporDVOField;
            }
            set {
                this.raporDVOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class CocukBilgisiDVO {
        
        private string cinsiyetField;
        
        private string dogumSaatiField;
        
        private string kiloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string cinsiyet {
            get {
                return this.cinsiyetField;
            }
            set {
                this.cinsiyetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string dogumSaati {
            get {
                return this.dogumSaatiField;
            }
            set {
                this.dogumSaatiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string kilo {
            get {
                return this.kiloField;
            }
            set {
                this.kiloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class IlacRaporDVO {
        
        private RaporDVO raporDVOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RaporDVO raporDVO {
            get {
                return this.raporDVOField;
            }
            set {
                this.raporDVOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class MaluliyetRaporDVO {
        
        private string aciklamaField;
        
        private string maluliyetYuzdesiField;
        
        private BransGorusBilgisiDVO[] bransGorusleriField;
        
        private RaporDVO raporDVOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string maluliyetYuzdesi {
            get {
                return this.maluliyetYuzdesiField;
            }
            set {
                this.maluliyetYuzdesiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BransGorusBilgisiDVO[] bransGorusleri {
            get {
                return this.bransGorusleriField;
            }
            set {
                this.bransGorusleriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RaporDVO raporDVO {
            get {
                return this.raporDVOField;
            }
            set {
                this.raporDVOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class BransGorusBilgisiDVO {
        
        private string bransKoduField;
        
        private string aciklamaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bransKodu {
            get {
                return this.bransKoduField;
            }
            set {
                this.bransKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class ProtezRaporDVO {
        
        private MalzemeBilgisiDVO[] malzemelerField;
        
        private RaporDVO raporDVOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MalzemeBilgisiDVO[] malzemeler {
            get {
                return this.malzemelerField;
            }
            set {
                this.malzemelerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RaporDVO raporDVO {
            get {
                return this.raporDVOField;
            }
            set {
                this.raporDVOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class MalzemeBilgisiDVO {
        
        private int adetField;
        
        private string malzemeAdiField;
        
        private string malzemeKoduField;
        
        private string malzemeTuruField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int adet {
            get {
                return this.adetField;
            }
            set {
                this.adetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string malzemeAdi {
            get {
                return this.malzemeAdiField;
            }
            set {
                this.malzemeAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string malzemeKodu {
            get {
                return this.malzemeKoduField;
            }
            set {
                this.malzemeKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string malzemeTuru {
            get {
                return this.malzemeTuruField;
            }
            set {
                this.malzemeTuruField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class TedaviRaporDVO {
        
        private TedaviIslemBilgisiDVO[] islemlerField;
        
        private RaporDVO raporDVOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TedaviIslemBilgisiDVO[] islemler {
            get {
                return this.islemlerField;
            }
            set {
                this.islemlerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RaporDVO raporDVO {
            get {
                return this.raporDVOField;
            }
            set {
                this.raporDVOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class TedaviIslemBilgisiDVO {
        
        private string refakatVarMiField;
        
        private int seansGunField;
        
        private int seansSayiField;
        
        private string butKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string refakatVarMi {
            get {
                return this.refakatVarMiField;
            }
            set {
                this.refakatVarMiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int seansGun {
            get {
                return this.seansGunField;
            }
            set {
                this.seansGunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int seansSayi {
            get {
                return this.seansSayiField;
            }
            set {
                this.seansSayiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string butKodu {
            get {
                return this.butKoduField;
            }
            set {
                this.butKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class IsgoremezlikRaporDVO {
        
        private string kontrolMuField;
        
        private string kontrolTarihiField;
        
        private HastaYatisBilgisiDVO[] yatislarField;
        
        private RaporDVO raporDVOField;
        
        private string hastaYatisVarMiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string kontrolMu {
            get {
                return this.kontrolMuField;
            }
            set {
                this.kontrolMuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string kontrolTarihi {
            get {
                return this.kontrolTarihiField;
            }
            set {
                this.kontrolTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HastaYatisBilgisiDVO[] yatislar {
            get {
                return this.yatislarField;
            }
            set {
                this.yatislarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public RaporDVO raporDVO {
            get {
                return this.raporDVOField;
            }
            set {
                this.raporDVOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hastaYatisVarMi {
            get {
                return this.hastaYatisVarMiField;
            }
            set {
                this.hastaYatisVarMiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rapor.dvo.gss.sgk.gov.tr")]
    public partial class HakSahibiBilgisiDVO {
        
        private string tckimlikNoField;
        
        private string devredilenKurumField;
        
        private string karneNoField;
        
        private string sigortaliTuruField;
        
        private string sosyalGuvenlikNoField;
        
        private string yakinlikKoduField;
        
        private string provizyonTarihiField;
        
        private string provizyonTipiField;
        
        private string adiField;
        
        private string soyadiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string tckimlikNo {
            get {
                return this.tckimlikNoField;
            }
            set {
                this.tckimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string devredilenKurum {
            get {
                return this.devredilenKurumField;
            }
            set {
                this.devredilenKurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string karneNo {
            get {
                return this.karneNoField;
            }
            set {
                this.karneNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sigortaliTuru {
            get {
                return this.sigortaliTuruField;
            }
            set {
                this.sigortaliTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sosyalGuvenlikNo {
            get {
                return this.sosyalGuvenlikNoField;
            }
            set {
                this.sosyalGuvenlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string yakinlikKodu {
            get {
                return this.yakinlikKoduField;
            }
            set {
                this.yakinlikKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string provizyonTarihi {
            get {
                return this.provizyonTarihiField;
            }
            set {
                this.provizyonTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string provizyonTipi {
            get {
                return this.provizyonTipiField;
            }
            set {
                this.provizyonTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string adi {
            get {
                return this.adiField;
            }
            set {
                this.adiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string soyadi {
            get {
                return this.soyadiField;
            }
            set {
                this.soyadiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void takipNoileRaporBilgisiKaydetCompletedEventHandler(object sender, takipNoileRaporBilgisiKaydetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class takipNoileRaporBilgisiKaydetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal takipNoileRaporBilgisiKaydetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RaporCevapDVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RaporCevapDVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void raporBilgisiBulCompletedEventHandler(object sender, raporBilgisiBulCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class raporBilgisiBulCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal raporBilgisiBulCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RaporCevapDVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RaporCevapDVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void raporUzatCompletedEventHandler(object sender, raporUzatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class raporUzatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal raporUzatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RaporUzatCevapDVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RaporUzatCevapDVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void raporBilgisiKaydetCompletedEventHandler(object sender, raporBilgisiKaydetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class raporBilgisiKaydetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal raporBilgisiKaydetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RaporCevapDVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RaporCevapDVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void raporBilgisiSilCompletedEventHandler(object sender, raporBilgisiSilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class raporBilgisiSilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal raporBilgisiSilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RaporCevapDVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RaporCevapDVO)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591