//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace Naz.Hastane.Medula.HizmetKayitIslemleriWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HizmetKayitIslemleriSoapBinding", Namespace="http://servisler.ws.gss.sgk.gov.tr")]
    public partial class HizmetKayitIslemleriService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback hizmetKaydiIptalOperationCompleted;
        
        private System.Threading.SendOrPostCallback hizmetKayitOperationCompleted;
        
        private System.Threading.SendOrPostCallback hizmetKaydiOkuOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HizmetKayitIslemleriService() {
            this.Url = global::Naz.Hastane.Medula.Properties.Settings.Default.Naz_Medula_HizmetKayitIslemleri_HizmetKayitIslemleriService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event hizmetKaydiIptalCompletedEventHandler hizmetKaydiIptalCompleted;
        
        /// <remarks/>
        public event hizmetKayitCompletedEventHandler hizmetKayitCompleted;
        
        /// <remarks/>
        public event hizmetKaydiOkuCompletedEventHandler hizmetKaydiOkuCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servisler.ws.gss.sgk.gov.tr", ResponseNamespace="http://servisler.ws.gss.sgk.gov.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("hizmetKaydiIptalReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public HizmetIptalCevapDVO hizmetKaydiIptal([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] HizmetIptalGirisDVO hizmetIptalGirisDVO) {
            object[] results = this.Invoke("hizmetKaydiIptal", new object[] {
                        hizmetIptalGirisDVO});
            return ((HizmetIptalCevapDVO)(results[0]));
        }
        
        /// <remarks/>
        public void hizmetKaydiIptalAsync(HizmetIptalGirisDVO hizmetIptalGirisDVO) {
            this.hizmetKaydiIptalAsync(hizmetIptalGirisDVO, null);
        }
        
        /// <remarks/>
        public void hizmetKaydiIptalAsync(HizmetIptalGirisDVO hizmetIptalGirisDVO, object userState) {
            if ((this.hizmetKaydiIptalOperationCompleted == null)) {
                this.hizmetKaydiIptalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhizmetKaydiIptalOperationCompleted);
            }
            this.InvokeAsync("hizmetKaydiIptal", new object[] {
                        hizmetIptalGirisDVO}, this.hizmetKaydiIptalOperationCompleted, userState);
        }
        
        private void OnhizmetKaydiIptalOperationCompleted(object arg) {
            if ((this.hizmetKaydiIptalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.hizmetKaydiIptalCompleted(this, new hizmetKaydiIptalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servisler.ws.gss.sgk.gov.tr", ResponseNamespace="http://servisler.ws.gss.sgk.gov.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("hizmetKayitReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public HizmetKayitCevapDVO hizmetKayit([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] HizmetKayitGirisDVO hizmetKayitGiris) {
            object[] results = this.Invoke("hizmetKayit", new object[] {
                        hizmetKayitGiris});
            return ((HizmetKayitCevapDVO)(results[0]));
        }
        
        /// <remarks/>
        public void hizmetKayitAsync(HizmetKayitGirisDVO hizmetKayitGiris) {
            this.hizmetKayitAsync(hizmetKayitGiris, null);
        }
        
        /// <remarks/>
        public void hizmetKayitAsync(HizmetKayitGirisDVO hizmetKayitGiris, object userState) {
            if ((this.hizmetKayitOperationCompleted == null)) {
                this.hizmetKayitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhizmetKayitOperationCompleted);
            }
            this.InvokeAsync("hizmetKayit", new object[] {
                        hizmetKayitGiris}, this.hizmetKayitOperationCompleted, userState);
        }
        
        private void OnhizmetKayitOperationCompleted(object arg) {
            if ((this.hizmetKayitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.hizmetKayitCompleted(this, new hizmetKayitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servisler.ws.gss.sgk.gov.tr", ResponseNamespace="http://servisler.ws.gss.sgk.gov.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("hizmetKaydiOkuReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public HizmetOkuCevapDVO hizmetKaydiOku([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] HizmetOkuGirisDVO hizmetOkuGiris) {
            object[] results = this.Invoke("hizmetKaydiOku", new object[] {
                        hizmetOkuGiris});
            return ((HizmetOkuCevapDVO)(results[0]));
        }
        
        /// <remarks/>
        public void hizmetKaydiOkuAsync(HizmetOkuGirisDVO hizmetOkuGiris) {
            this.hizmetKaydiOkuAsync(hizmetOkuGiris, null);
        }
        
        /// <remarks/>
        public void hizmetKaydiOkuAsync(HizmetOkuGirisDVO hizmetOkuGiris, object userState) {
            if ((this.hizmetKaydiOkuOperationCompleted == null)) {
                this.hizmetKaydiOkuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhizmetKaydiOkuOperationCompleted);
            }
            this.InvokeAsync("hizmetKaydiOku", new object[] {
                        hizmetOkuGiris}, this.hizmetKaydiOkuOperationCompleted, userState);
        }
        
        private void OnhizmetKaydiOkuOperationCompleted(object arg) {
            if ((this.hizmetKaydiOkuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.hizmetKaydiOkuCompleted(this, new hizmetKaydiOkuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class HizmetIptalGirisDVO {
        
        private string[] islemSiraNumaralariField;
        
        private int saglikTesisKoduField;
        
        private string takipNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] islemSiraNumaralari {
            get {
                return this.islemSiraNumaralariField;
            }
            set {
                this.islemSiraNumaralariField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int saglikTesisKodu {
            get {
                return this.saglikTesisKoduField;
            }
            set {
                this.saglikTesisKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string takipNo {
            get {
                return this.takipNoField;
            }
            set {
                this.takipNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class HizmetDVO {
        
        private string odemeSorguDurumField;
        
        private AmeliyatveGirisimBilgisiDVO[] ameliyatveGirisimBilgileriField;
        
        private DigerIslemBilgisiDVO[] digerIslemBilgileriField;
        
        private DisBilgisiDVO[] disBilgileriField;
        
        private HastaYatisBilgisiDVO[] hastaYatisBilgileriField;
        
        private IlacBilgisiDVO[] ilacBilgileriField;
        
        private KonsultasyonBilgisiDVO[] konsultasyonBilgileriField;
        
        private MalzemeBilgisiDVO[] malzemeBilgileriField;
        
        private MuayeneBilgisiDVO muayeneBilgisiField;
        
        private TahlilBilgisiDVO[] tahlilBilgileriField;
        
        private string takipNoField;
        
        private TaniBilgisiDVO[] tanilarField;
        
        private TetkikveRadyolojiBilgisiDVO[] tetkikveRadyolojiBilgileriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string odemeSorguDurum {
            get {
                return this.odemeSorguDurumField;
            }
            set {
                this.odemeSorguDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AmeliyatveGirisimBilgisiDVO[] ameliyatveGirisimBilgileri {
            get {
                return this.ameliyatveGirisimBilgileriField;
            }
            set {
                this.ameliyatveGirisimBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DigerIslemBilgisiDVO[] digerIslemBilgileri {
            get {
                return this.digerIslemBilgileriField;
            }
            set {
                this.digerIslemBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DisBilgisiDVO[] disBilgileri {
            get {
                return this.disBilgileriField;
            }
            set {
                this.disBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HastaYatisBilgisiDVO[] hastaYatisBilgileri {
            get {
                return this.hastaYatisBilgileriField;
            }
            set {
                this.hastaYatisBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IlacBilgisiDVO[] ilacBilgileri {
            get {
                return this.ilacBilgileriField;
            }
            set {
                this.ilacBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KonsultasyonBilgisiDVO[] konsultasyonBilgileri {
            get {
                return this.konsultasyonBilgileriField;
            }
            set {
                this.konsultasyonBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MalzemeBilgisiDVO[] malzemeBilgileri {
            get {
                return this.malzemeBilgileriField;
            }
            set {
                this.malzemeBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public MuayeneBilgisiDVO muayeneBilgisi {
            get {
                return this.muayeneBilgisiField;
            }
            set {
                this.muayeneBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TahlilBilgisiDVO[] tahlilBilgileri {
            get {
                return this.tahlilBilgileriField;
            }
            set {
                this.tahlilBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string takipNo {
            get {
                return this.takipNoField;
            }
            set {
                this.takipNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TaniBilgisiDVO[] tanilar {
            get {
                return this.tanilarField;
            }
            set {
                this.tanilarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TetkikveRadyolojiBilgisiDVO[] tetkikveRadyolojiBilgileri {
            get {
                return this.tetkikveRadyolojiBilgileriField;
            }
            set {
                this.tetkikveRadyolojiBilgileriField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class AmeliyatveGirisimBilgisiDVO {
        
        private string ozelDurumField;
        
        private string euroscoreField;
        
        private string aciklamaField;
        
        private int adetField;
        
        private string ayniFarkliKesiField;
        
        private string bransKoduField;
        
        private string drTescilNoField;
        
        private string hizmetSunucuRefNoField;
        
        private string islemSiraNoField;
        
        private string islemTarihiField;
        
        private string sagSolField;
        
        private string sutKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ozelDurum {
            get {
                return this.ozelDurumField;
            }
            set {
                this.ozelDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string euroscore {
            get {
                return this.euroscoreField;
            }
            set {
                this.euroscoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int adet {
            get {
                return this.adetField;
            }
            set {
                this.adetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ayniFarkliKesi {
            get {
                return this.ayniFarkliKesiField;
            }
            set {
                this.ayniFarkliKesiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bransKodu {
            get {
                return this.bransKoduField;
            }
            set {
                this.bransKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string drTescilNo {
            get {
                return this.drTescilNoField;
            }
            set {
                this.drTescilNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hizmetSunucuRefNo {
            get {
                return this.hizmetSunucuRefNoField;
            }
            set {
                this.hizmetSunucuRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemSiraNo {
            get {
                return this.islemSiraNoField;
            }
            set {
                this.islemSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemTarihi {
            get {
                return this.islemTarihiField;
            }
            set {
                this.islemTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sagSol {
            get {
                return this.sagSolField;
            }
            set {
                this.sagSolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sutKodu {
            get {
                return this.sutKoduField;
            }
            set {
                this.sutKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class DigerIslemBilgisiDVO {
        
        private string ayniFarkliKesiField;
        
        private string ozelDurumField;
        
        private int adetField;
        
        private string bransKoduField;
        
        private string sutKoduField;
        
        private string drTescilNoField;
        
        private string hizmetSunucuRefNoField;
        
        private string islemSiraNoField;
        
        private string islemTarihiField;
        
        private string raporTakipNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ayniFarkliKesi {
            get {
                return this.ayniFarkliKesiField;
            }
            set {
                this.ayniFarkliKesiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ozelDurum {
            get {
                return this.ozelDurumField;
            }
            set {
                this.ozelDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int adet {
            get {
                return this.adetField;
            }
            set {
                this.adetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bransKodu {
            get {
                return this.bransKoduField;
            }
            set {
                this.bransKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sutKodu {
            get {
                return this.sutKoduField;
            }
            set {
                this.sutKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string drTescilNo {
            get {
                return this.drTescilNoField;
            }
            set {
                this.drTescilNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hizmetSunucuRefNo {
            get {
                return this.hizmetSunucuRefNoField;
            }
            set {
                this.hizmetSunucuRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemSiraNo {
            get {
                return this.islemSiraNoField;
            }
            set {
                this.islemSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemTarihi {
            get {
                return this.islemTarihiField;
            }
            set {
                this.islemTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string raporTakipNo {
            get {
                return this.raporTakipNoField;
            }
            set {
                this.raporTakipNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class DisBilgisiDVO {
        
        private string ayniFarkliKesiField;
        
        private string ozelDurumField;
        
        private int adetField;
        
        private string anomaliField;
        
        private string bransKoduField;
        
        private string drTescilNoField;
        
        private string hizmetSunucuRefNoField;
        
        private string islemSiraNoField;
        
        private string islemTarihiField;
        
        private string sagAltCeneField;
        
        private string sagSutAltCeneField;
        
        private string sagSutUstCeneField;
        
        private string sagUstCeneField;
        
        private string solAltCeneField;
        
        private string solSutAltCeneField;
        
        private string solSutUstCeneField;
        
        private string solUstCeneField;
        
        private string sutKoduField;
        
        private string sagAltCeneAnomaliDisField;
        
        private string sagUstCeneAnomaliDisField;
        
        private string solAltCeneAnomaliDisField;
        
        private string solUstCeneAnomaliDisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ayniFarkliKesi {
            get {
                return this.ayniFarkliKesiField;
            }
            set {
                this.ayniFarkliKesiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ozelDurum {
            get {
                return this.ozelDurumField;
            }
            set {
                this.ozelDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int adet {
            get {
                return this.adetField;
            }
            set {
                this.adetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string anomali {
            get {
                return this.anomaliField;
            }
            set {
                this.anomaliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bransKodu {
            get {
                return this.bransKoduField;
            }
            set {
                this.bransKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string drTescilNo {
            get {
                return this.drTescilNoField;
            }
            set {
                this.drTescilNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hizmetSunucuRefNo {
            get {
                return this.hizmetSunucuRefNoField;
            }
            set {
                this.hizmetSunucuRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemSiraNo {
            get {
                return this.islemSiraNoField;
            }
            set {
                this.islemSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemTarihi {
            get {
                return this.islemTarihiField;
            }
            set {
                this.islemTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sagAltCene {
            get {
                return this.sagAltCeneField;
            }
            set {
                this.sagAltCeneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sagSutAltCene {
            get {
                return this.sagSutAltCeneField;
            }
            set {
                this.sagSutAltCeneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sagSutUstCene {
            get {
                return this.sagSutUstCeneField;
            }
            set {
                this.sagSutUstCeneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sagUstCene {
            get {
                return this.sagUstCeneField;
            }
            set {
                this.sagUstCeneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string solAltCene {
            get {
                return this.solAltCeneField;
            }
            set {
                this.solAltCeneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string solSutAltCene {
            get {
                return this.solSutAltCeneField;
            }
            set {
                this.solSutAltCeneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string solSutUstCene {
            get {
                return this.solSutUstCeneField;
            }
            set {
                this.solSutUstCeneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string solUstCene {
            get {
                return this.solUstCeneField;
            }
            set {
                this.solUstCeneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sutKodu {
            get {
                return this.sutKoduField;
            }
            set {
                this.sutKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sagAltCeneAnomaliDis {
            get {
                return this.sagAltCeneAnomaliDisField;
            }
            set {
                this.sagAltCeneAnomaliDisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sagUstCeneAnomaliDis {
            get {
                return this.sagUstCeneAnomaliDisField;
            }
            set {
                this.sagUstCeneAnomaliDisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string solAltCeneAnomaliDis {
            get {
                return this.solAltCeneAnomaliDisField;
            }
            set {
                this.solAltCeneAnomaliDisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string solUstCeneAnomaliDis {
            get {
                return this.solUstCeneAnomaliDisField;
            }
            set {
                this.solUstCeneAnomaliDisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class HastaYatisBilgisiDVO {
        
        private string ozelDurumField;
        
        private string bransKoduField;
        
        private string drTescilNoField;
        
        private string hizmetSunucuRefNoField;
        
        private string islemSiraNoField;
        
        private string refakatciGunSayisiField;
        
        private string sutKoduField;
        
        private string yatisBaslangicTarihiField;
        
        private string yatisBitisTarihiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ozelDurum {
            get {
                return this.ozelDurumField;
            }
            set {
                this.ozelDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bransKodu {
            get {
                return this.bransKoduField;
            }
            set {
                this.bransKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string drTescilNo {
            get {
                return this.drTescilNoField;
            }
            set {
                this.drTescilNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hizmetSunucuRefNo {
            get {
                return this.hizmetSunucuRefNoField;
            }
            set {
                this.hizmetSunucuRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemSiraNo {
            get {
                return this.islemSiraNoField;
            }
            set {
                this.islemSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string refakatciGunSayisi {
            get {
                return this.refakatciGunSayisiField;
            }
            set {
                this.refakatciGunSayisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sutKodu {
            get {
                return this.sutKoduField;
            }
            set {
                this.sutKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string yatisBaslangicTarihi {
            get {
                return this.yatisBaslangicTarihiField;
            }
            set {
                this.yatisBaslangicTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string yatisBitisTarihi {
            get {
                return this.yatisBitisTarihiField;
            }
            set {
                this.yatisBitisTarihiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class IlacBilgisiDVO {
        
        private string ozelDurumField;
        
        private string paketHaricField;
        
        private string aciklamaField;
        
        private double adetField;
        
        private string barkodField;
        
        private string hizmetSunucuRefNoField;
        
        private string ilacTuruField;
        
        private string islemSiraNoField;
        
        private string islemTarihiField;
        
        private double tutarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ozelDurum {
            get {
                return this.ozelDurumField;
            }
            set {
                this.ozelDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string paketHaric {
            get {
                return this.paketHaricField;
            }
            set {
                this.paketHaricField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double adet {
            get {
                return this.adetField;
            }
            set {
                this.adetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string barkod {
            get {
                return this.barkodField;
            }
            set {
                this.barkodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hizmetSunucuRefNo {
            get {
                return this.hizmetSunucuRefNoField;
            }
            set {
                this.hizmetSunucuRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ilacTuru {
            get {
                return this.ilacTuruField;
            }
            set {
                this.ilacTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemSiraNo {
            get {
                return this.islemSiraNoField;
            }
            set {
                this.islemSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemTarihi {
            get {
                return this.islemTarihiField;
            }
            set {
                this.islemTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double tutar {
            get {
                return this.tutarField;
            }
            set {
                this.tutarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class KonsultasyonBilgisiDVO {
        
        private string ozelDurumField;
        
        private string bransKoduField;
        
        private string drTescilNoField;
        
        private string hizmetSunucuRefNoField;
        
        private string islemSiraNoField;
        
        private string islemTarihiField;
        
        private string sutKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ozelDurum {
            get {
                return this.ozelDurumField;
            }
            set {
                this.ozelDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bransKodu {
            get {
                return this.bransKoduField;
            }
            set {
                this.bransKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string drTescilNo {
            get {
                return this.drTescilNoField;
            }
            set {
                this.drTescilNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hizmetSunucuRefNo {
            get {
                return this.hizmetSunucuRefNoField;
            }
            set {
                this.hizmetSunucuRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemSiraNo {
            get {
                return this.islemSiraNoField;
            }
            set {
                this.islemSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemTarihi {
            get {
                return this.islemTarihiField;
            }
            set {
                this.islemTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sutKodu {
            get {
                return this.sutKoduField;
            }
            set {
                this.sutKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class MalzemeBilgisiDVO {
        
        private string ozelDurumField;
        
        private string katkiPayiField;
        
        private string kodsuzMalzemeAdiField;
        
        private double adetField;
        
        private string barkodField;
        
        private string hizmetSunucuRefNoField;
        
        private string islemSiraNoField;
        
        private string islemTarihiField;
        
        private double kodsuzMalzemeFiyatiField;
        
        private string malzemeKoduField;
        
        private string malzemeTuruField;
        
        private string paketHaricField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ozelDurum {
            get {
                return this.ozelDurumField;
            }
            set {
                this.ozelDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string katkiPayi {
            get {
                return this.katkiPayiField;
            }
            set {
                this.katkiPayiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string kodsuzMalzemeAdi {
            get {
                return this.kodsuzMalzemeAdiField;
            }
            set {
                this.kodsuzMalzemeAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double adet {
            get {
                return this.adetField;
            }
            set {
                this.adetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string barkod {
            get {
                return this.barkodField;
            }
            set {
                this.barkodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hizmetSunucuRefNo {
            get {
                return this.hizmetSunucuRefNoField;
            }
            set {
                this.hizmetSunucuRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemSiraNo {
            get {
                return this.islemSiraNoField;
            }
            set {
                this.islemSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemTarihi {
            get {
                return this.islemTarihiField;
            }
            set {
                this.islemTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double kodsuzMalzemeFiyati {
            get {
                return this.kodsuzMalzemeFiyatiField;
            }
            set {
                this.kodsuzMalzemeFiyatiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string malzemeKodu {
            get {
                return this.malzemeKoduField;
            }
            set {
                this.malzemeKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string malzemeTuru {
            get {
                return this.malzemeTuruField;
            }
            set {
                this.malzemeTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string paketHaric {
            get {
                return this.paketHaricField;
            }
            set {
                this.paketHaricField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class MuayeneBilgisiDVO {
        
        private string ozelDurumField;
        
        private string bransKoduField;
        
        private string drTescilNoField;
        
        private string hizmetSunucuRefNoField;
        
        private string islemSiraNoField;
        
        private string muayeneTarihiField;
        
        private string sutKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ozelDurum {
            get {
                return this.ozelDurumField;
            }
            set {
                this.ozelDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bransKodu {
            get {
                return this.bransKoduField;
            }
            set {
                this.bransKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string drTescilNo {
            get {
                return this.drTescilNoField;
            }
            set {
                this.drTescilNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hizmetSunucuRefNo {
            get {
                return this.hizmetSunucuRefNoField;
            }
            set {
                this.hizmetSunucuRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemSiraNo {
            get {
                return this.islemSiraNoField;
            }
            set {
                this.islemSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string muayeneTarihi {
            get {
                return this.muayeneTarihiField;
            }
            set {
                this.muayeneTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sutKodu {
            get {
                return this.sutKoduField;
            }
            set {
                this.sutKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class TahlilBilgisiDVO {
        
        private TahlilSonucDVO[] tahlilSonuclariField;
        
        private string ozelDurumField;
        
        private int adetField;
        
        private string bransKoduField;
        
        private string drTescilNoField;
        
        private string hizmetSunucuRefNoField;
        
        private string islemSiraNoField;
        
        private string islemTarihiField;
        
        private string sutKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TahlilSonucDVO[] tahlilSonuclari {
            get {
                return this.tahlilSonuclariField;
            }
            set {
                this.tahlilSonuclariField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ozelDurum {
            get {
                return this.ozelDurumField;
            }
            set {
                this.ozelDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int adet {
            get {
                return this.adetField;
            }
            set {
                this.adetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bransKodu {
            get {
                return this.bransKoduField;
            }
            set {
                this.bransKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string drTescilNo {
            get {
                return this.drTescilNoField;
            }
            set {
                this.drTescilNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hizmetSunucuRefNo {
            get {
                return this.hizmetSunucuRefNoField;
            }
            set {
                this.hizmetSunucuRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemSiraNo {
            get {
                return this.islemSiraNoField;
            }
            set {
                this.islemSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemTarihi {
            get {
                return this.islemTarihiField;
            }
            set {
                this.islemTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sutKodu {
            get {
                return this.sutKoduField;
            }
            set {
                this.sutKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class TahlilSonucDVO {
        
        private string islemSiraNoField;
        
        private string sonucField;
        
        private string tahlilTipiField;
        
        private string birimField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemSiraNo {
            get {
                return this.islemSiraNoField;
            }
            set {
                this.islemSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sonuc {
            get {
                return this.sonucField;
            }
            set {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string tahlilTipi {
            get {
                return this.tahlilTipiField;
            }
            set {
                this.tahlilTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string birim {
            get {
                return this.birimField;
            }
            set {
                this.birimField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class TaniBilgisiDVO {
        
        private string ozelDurumField;
        
        private string islemSiraNoField;
        
        private string hizmetSunucuRefNoField;
        
        private string birincilTaniField;
        
        private string taniKoduField;
        
        private string taniTipiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ozelDurum {
            get {
                return this.ozelDurumField;
            }
            set {
                this.ozelDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemSiraNo {
            get {
                return this.islemSiraNoField;
            }
            set {
                this.islemSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hizmetSunucuRefNo {
            get {
                return this.hizmetSunucuRefNoField;
            }
            set {
                this.hizmetSunucuRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string birincilTani {
            get {
                return this.birincilTaniField;
            }
            set {
                this.birincilTaniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string taniKodu {
            get {
                return this.taniKoduField;
            }
            set {
                this.taniKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string taniTipi {
            get {
                return this.taniTipiField;
            }
            set {
                this.taniTipiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class TetkikveRadyolojiBilgisiDVO {
        
        private string ayniFarkliKesiField;
        
        private string aciklamaField;
        
        private string birimField;
        
        private string sonucField;
        
        private string ozelDurumField;
        
        private int adetField;
        
        private string bransKoduField;
        
        private string drTescilNoField;
        
        private string hizmetSunucuRefNoField;
        
        private string islemSiraNoField;
        
        private string islemTarihiField;
        
        private string sutKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ayniFarkliKesi {
            get {
                return this.ayniFarkliKesiField;
            }
            set {
                this.ayniFarkliKesiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string birim {
            get {
                return this.birimField;
            }
            set {
                this.birimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sonuc {
            get {
                return this.sonucField;
            }
            set {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ozelDurum {
            get {
                return this.ozelDurumField;
            }
            set {
                this.ozelDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int adet {
            get {
                return this.adetField;
            }
            set {
                this.adetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bransKodu {
            get {
                return this.bransKoduField;
            }
            set {
                this.bransKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string drTescilNo {
            get {
                return this.drTescilNoField;
            }
            set {
                this.drTescilNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hizmetSunucuRefNo {
            get {
                return this.hizmetSunucuRefNoField;
            }
            set {
                this.hizmetSunucuRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemSiraNo {
            get {
                return this.islemSiraNoField;
            }
            set {
                this.islemSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemTarihi {
            get {
                return this.islemTarihiField;
            }
            set {
                this.islemTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sutKodu {
            get {
                return this.sutKoduField;
            }
            set {
                this.sutKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class HizmetOkuCevapDVO {
        
        private string hastaBasvuruNoField;
        
        private HizmetDVO hizmetlerField;
        
        private string sonucKoduField;
        
        private string sonucMesajiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hastaBasvuruNo {
            get {
                return this.hastaBasvuruNoField;
            }
            set {
                this.hastaBasvuruNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public HizmetDVO hizmetler {
            get {
                return this.hizmetlerField;
            }
            set {
                this.hizmetlerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sonucKodu {
            get {
                return this.sonucKoduField;
            }
            set {
                this.sonucKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sonucMesaji {
            get {
                return this.sonucMesajiField;
            }
            set {
                this.sonucMesajiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class HizmetOkuGirisDVO {
        
        private string[] islemSiraNumaralariField;
        
        private int saglikTesisKoduField;
        
        private string takipNoField;
        
        private string[] hizmetSunucuRefNolariField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] islemSiraNumaralari {
            get {
                return this.islemSiraNumaralariField;
            }
            set {
                this.islemSiraNumaralariField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int saglikTesisKodu {
            get {
                return this.saglikTesisKoduField;
            }
            set {
                this.saglikTesisKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string takipNo {
            get {
                return this.takipNoField;
            }
            set {
                this.takipNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] hizmetSunucuRefNolari {
            get {
                return this.hizmetSunucuRefNolariField;
            }
            set {
                this.hizmetSunucuRefNolariField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class KayitliIslemBilgisiDVO {
        
        private string hizmetSunucuRefNoField;
        
        private string islemSiraNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hizmetSunucuRefNo {
            get {
                return this.hizmetSunucuRefNoField;
            }
            set {
                this.hizmetSunucuRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemSiraNo {
            get {
                return this.islemSiraNoField;
            }
            set {
                this.islemSiraNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class OncekiIslemBilgisiDVO {
        
        private int islemAdediField;
        
        private string islemTarihiField;
        
        private int saglikTesisKoduField;
        
        private string tesisAdiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int islemAdedi {
            get {
                return this.islemAdediField;
            }
            set {
                this.islemAdediField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemTarihi {
            get {
                return this.islemTarihiField;
            }
            set {
                this.islemTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int saglikTesisKodu {
            get {
                return this.saglikTesisKoduField;
            }
            set {
                this.saglikTesisKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string tesisAdi {
            get {
                return this.tesisAdiField;
            }
            set {
                this.tesisAdiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class HataliIslemBilgisiDVO {
        
        private string hataKoduField;
        
        private string hataMesajiField;
        
        private string hizmetSunucuRefNoField;
        
        private OncekiIslemBilgisiDVO oncekiIslemBilgisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hataKodu {
            get {
                return this.hataKoduField;
            }
            set {
                this.hataKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hataMesaji {
            get {
                return this.hataMesajiField;
            }
            set {
                this.hataMesajiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hizmetSunucuRefNo {
            get {
                return this.hizmetSunucuRefNoField;
            }
            set {
                this.hizmetSunucuRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public OncekiIslemBilgisiDVO oncekiIslemBilgisi {
            get {
                return this.oncekiIslemBilgisiField;
            }
            set {
                this.oncekiIslemBilgisiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class HizmetKayitCevapDVO {
        
        private string hastaBasvuruNoField;
        
        private HataliIslemBilgisiDVO[] hataliKayitlarField;
        
        private KayitliIslemBilgisiDVO[] islemBilgileriField;
        
        private int saglikTesisKoduField;
        
        private string sonucKoduField;
        
        private string sonucMesajiField;
        
        private string takipNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hastaBasvuruNo {
            get {
                return this.hastaBasvuruNoField;
            }
            set {
                this.hastaBasvuruNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HataliIslemBilgisiDVO[] hataliKayitlar {
            get {
                return this.hataliKayitlarField;
            }
            set {
                this.hataliKayitlarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KayitliIslemBilgisiDVO[] islemBilgileri {
            get {
                return this.islemBilgileriField;
            }
            set {
                this.islemBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int saglikTesisKodu {
            get {
                return this.saglikTesisKoduField;
            }
            set {
                this.saglikTesisKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sonucKodu {
            get {
                return this.sonucKoduField;
            }
            set {
                this.sonucKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sonucMesaji {
            get {
                return this.sonucMesajiField;
            }
            set {
                this.sonucMesajiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string takipNo {
            get {
                return this.takipNoField;
            }
            set {
                this.takipNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class HizmetKayitGirisDVO {
        
        private AmeliyatveGirisimBilgisiDVO[] ameliyatveGirisimBilgileriField;
        
        private DigerIslemBilgisiDVO[] digerIslemBilgileriField;
        
        private DisBilgisiDVO[] disBilgileriField;
        
        private string hastaBasvuruNoField;
        
        private HastaYatisBilgisiDVO[] hastaYatisBilgileriField;
        
        private IlacBilgisiDVO[] ilacBilgileriField;
        
        private KonsultasyonBilgisiDVO[] konsultasyonBilgileriField;
        
        private MalzemeBilgisiDVO[] malzemeBilgileriField;
        
        private MuayeneBilgisiDVO muayeneBilgisiField;
        
        private int saglikTesisKoduField;
        
        private TahlilBilgisiDVO[] tahlilBilgileriField;
        
        private string takipNoField;
        
        private TaniBilgisiDVO[] tanilarField;
        
        private TetkikveRadyolojiBilgisiDVO[] tetkikveRadyolojiBilgileriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AmeliyatveGirisimBilgisiDVO[] ameliyatveGirisimBilgileri {
            get {
                return this.ameliyatveGirisimBilgileriField;
            }
            set {
                this.ameliyatveGirisimBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DigerIslemBilgisiDVO[] digerIslemBilgileri {
            get {
                return this.digerIslemBilgileriField;
            }
            set {
                this.digerIslemBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DisBilgisiDVO[] disBilgileri {
            get {
                return this.disBilgileriField;
            }
            set {
                this.disBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hastaBasvuruNo {
            get {
                return this.hastaBasvuruNoField;
            }
            set {
                this.hastaBasvuruNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HastaYatisBilgisiDVO[] hastaYatisBilgileri {
            get {
                return this.hastaYatisBilgileriField;
            }
            set {
                this.hastaYatisBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IlacBilgisiDVO[] ilacBilgileri {
            get {
                return this.ilacBilgileriField;
            }
            set {
                this.ilacBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KonsultasyonBilgisiDVO[] konsultasyonBilgileri {
            get {
                return this.konsultasyonBilgileriField;
            }
            set {
                this.konsultasyonBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MalzemeBilgisiDVO[] malzemeBilgileri {
            get {
                return this.malzemeBilgileriField;
            }
            set {
                this.malzemeBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public MuayeneBilgisiDVO muayeneBilgisi {
            get {
                return this.muayeneBilgisiField;
            }
            set {
                this.muayeneBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int saglikTesisKodu {
            get {
                return this.saglikTesisKoduField;
            }
            set {
                this.saglikTesisKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TahlilBilgisiDVO[] tahlilBilgileri {
            get {
                return this.tahlilBilgileriField;
            }
            set {
                this.tahlilBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string takipNo {
            get {
                return this.takipNoField;
            }
            set {
                this.takipNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TaniBilgisiDVO[] tanilar {
            get {
                return this.tanilarField;
            }
            set {
                this.tanilarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TetkikveRadyolojiBilgisiDVO[] tetkikveRadyolojiBilgileri {
            get {
                return this.tetkikveRadyolojiBilgileriField;
            }
            set {
                this.tetkikveRadyolojiBilgileriField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class HizmetIptalCevapDVO {
        
        private string sonucKoduField;
        
        private string sonucMesajiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sonucKodu {
            get {
                return this.sonucKoduField;
            }
            set {
                this.sonucKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sonucMesaji {
            get {
                return this.sonucMesajiField;
            }
            set {
                this.sonucMesajiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void hizmetKaydiIptalCompletedEventHandler(object sender, hizmetKaydiIptalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class hizmetKaydiIptalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal hizmetKaydiIptalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HizmetIptalCevapDVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HizmetIptalCevapDVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void hizmetKayitCompletedEventHandler(object sender, hizmetKayitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class hizmetKayitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal hizmetKayitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HizmetKayitCevapDVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HizmetKayitCevapDVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void hizmetKaydiOkuCompletedEventHandler(object sender, hizmetKaydiOkuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class hizmetKaydiOkuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal hizmetKaydiOkuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HizmetOkuCevapDVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HizmetOkuCevapDVO)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591