CREATE TABLE [dbo].[ADRES_IDARM] (
    [KNR]               VARCHAR (6)  NOT NULL,
    [VAF_VAFTIZBABASI]  VARCHAR (30) NULL,
    [VAF_VAFTIZYERI]    VARCHAR (30) NULL,
    [VAF_VAFTIZCI]      VARCHAR (30) NULL,
    [VAF_VAFTIZTARIHI]  VARCHAR (10) NULL,
    [VAF_DONMETARIHI]   VARCHAR (10) NULL,
    [VAF_VAFTIZKAYITNO] VARCHAR (10) NULL,
    [MED_ESININADI]     VARCHAR (30) NULL,
    [MED_SAHIDINADI]    VARCHAR (30) NULL,
    [MED_DINGOREVLISI]  VARCHAR (30) NULL,
    [MED_DUGUNTARIHI]   VARCHAR (10) NULL,
    [MED_DUGUNYERI]     VARCHAR (30) NULL,
    [MED_DUGUNKAYITNO]  VARCHAR (10) NULL,
    [MED_KIZLIKSOYADI]  VARCHAR (30) NULL,
    [OZL_KENDIOGRENIM]  VARCHAR (10) NULL,
    [OZL_KENDIMESLEK]   VARCHAR (30) NULL,
    [OZL_KENDIERMENICE] VARCHAR (30) NULL,
    [OZL_ESIOGRENIM]    VARCHAR (10) NULL,
    [OZL_ESIMESLEK]     VARCHAR (30) NULL,
    [OZL_ESIERMENICE]   VARCHAR (30) NULL
);

