CREATE TABLE [dbo].[AMELIYATEKIBI] (
    [KNR]      VARCHAR (8)  NOT NULL,
    [SNR]      VARCHAR (8)  NOT NULL,
    [TARIH]    DATETIME     NULL,
    [YAPDR]    VARCHAR (50) NULL,
    [YDR1]     VARCHAR (50) NULL,
    [YDR2]     VARCHAR (50) NULL,
    [YDR3]     VARCHAR (50) NULL,
    [ANESDR]   VARCHAR (50) NULL,
    [ANESTEK1] VARCHAR (50) NULL,
    [ANESTEK2] VARCHAR (50) NULL,
    [HEM1]     VARCHAR (50) NULL,
    [HEM2]     VARCHAR (50) NULL,
    [NOTLAR]   VARCHAR (50) NULL
);

