CREATE TABLE [dbo].[ARMAKOMPARAMETRELER_112] (
    [SIRANO]      INT            IDENTITY (1, 1) NOT NULL,
    [ARMAKOMURL]  NVARCHAR (100) NULL,
    [ARMAKOMUSER] NVARCHAR (50)  NULL,
    [ARMAKOMPASS] NVARCHAR (50)  NULL,
    [ARMAKOMIP]   NVARCHAR (50)  NULL,
    [PROXY]       NVARCHAR (50)  NULL,
    [PROXYUSER]   NVARCHAR (50)  NULL,
    [PROXYPASS]   NVARCHAR (50)  NULL,
    [GSUREADET]   INT            NULL,
    [GSUREPER]    INT            NULL,
    [GSUREVAKA]   INT            NULL
);

