CREATE TABLE [dbo].[ARMAKOMVAKABILGISIGON_112] (
    [SIRANO]      INT           IDENTITY (1, 1) NOT NULL,
    [KNR]         NVARCHAR (50) NULL,
    [SNR]         NVARCHAR (50) NULL,
    [PROTNO]      NVARCHAR (50) NULL,
    [GELISTARIH]  DATETIME      NULL,
    [ARCIKLAMA]   NVARCHAR (50) NULL,
    [GONTARIH]    DATETIME      NULL,
    [HASTAADI]    NVARCHAR (50) NULL,
    [HASTASOYADI] NVARCHAR (50) NULL,
    [HATA]        NVARCHAR (50) NULL
);

