CREATE TABLE [dbo].[ARMAKOMADETBILGISI_112] (
    [SIRANO]         INT           IDENTITY (1, 1) NOT NULL,
    [BOLUMADI]       NVARCHAR (50) NULL,
    [TOPYATAK]       NVARCHAR (50) NULL,
    [BOSYATAK]       NVARCHAR (50) NULL,
    [TOPVENTIL]      NVARCHAR (50) NULL,
    [BOSVENTIL]      NVARCHAR (50) NULL,
    [TOPKUVEZ]       NVARCHAR (50) NULL,
    [BOSKUVEZ]       NVARCHAR (50) NULL,
    [BOLUMKOD]       NVARCHAR (50) NULL,
    [GONDERMETARIHI] DATETIME      NULL,
    [GONDERILDI]     NVARCHAR (50) NULL,
    [USER_112]       NVARCHAR (50) NULL,
    [HATA]           VARCHAR (200) NULL
);

