CREATE TABLE [dbo].[AVANSLAR_KULLANILAN] (
    [AV_ID]       FLOAT        NOT NULL,
    [TARIH]       DATETIME     NOT NULL,
    [FATURANO]    VARCHAR (7)  NOT NULL,
    [TUTAR]       FLOAT        NOT NULL,
    [USER_ID]     VARCHAR (20) NOT NULL,
    [DATE_CREATE] DATETIME     NOT NULL
);

