CREATE TABLE [dbo].[BDOGUM] (
    [KNR]             VARCHAR (6)    NOT NULL,
    [SNR]             VARCHAR (3)    NOT NULL,
    [BEBEKNO]         INT            NOT NULL,
    [ANNEDOGUMSEKLI]  VARCHAR (2)    NOT NULL,
    [BEBEKDOGUMSEKLI] VARCHAR (2)    NOT NULL,
    [BEBEKDOGUMT]     DATETIME       NOT NULL,
    [BEBEKDOGUMS]     DATETIME       NOT NULL,
    [BEBEKADI]        VARCHAR (20)   NULL,
    [BEBEKCINSIYET]   VARCHAR (1)    NOT NULL,
    [BEBEKBOY]        VARCHAR (2)    NULL,
    [BEBEKKILO]       VARCHAR (5)    NULL,
    [PROTOKOLNO]      VARCHAR (6)    NULL,
    [USER_ID]         VARCHAR (20)   NOT NULL,
    [DATE_CREATE]     DATETIME       NOT NULL,
    [USER_ID_UPDATE]  VARCHAR (20)   NULL,
    [DATE_UPDATE]     DATETIME       NULL,
    [SAGLIKNETDURUM]  CHAR (5)       NULL,
    [GIUD]            VARCHAR (50)   NULL,
    [GELENMESAJ]      VARCHAR (1000) NULL
);

