CREATE TABLE [dbo].[BEHAND1] (
    [KNR]             VARCHAR (6)  NOT NULL,
    [SNR]             VARCHAR (3)  NOT NULL,
    [BHDAT]           DATETIME     NOT NULL,
    [SEVKGECSURE]     SMALLINT     NOT NULL,
    [FATURATARIHI]    DATETIME     NULL,
    [ARZT]            VARCHAR (4)  NOT NULL,
    [SERVIS]          VARCHAR (2)  NOT NULL,
    [AMBU]            VARCHAR (1)  NOT NULL,
    [IMPF2]           VARCHAR (1)  NULL,
    [KAR_NO]          VARCHAR (7)  NULL,
    [ARSIVNO]         VARCHAR (7)  NULL,
    [TES_ANA]         VARCHAR (2)  NULL,
    [TES_CODE]        VARCHAR (15) NULL,
    [HASTALIKSONU]    VARCHAR (1)  NULL,
    [AMELIYAT]        VARCHAR (1)  NULL,
    [DOGUM]           VARCHAR (1)  NULL,
    [UCRETDURUMU]     VARCHAR (1)  NULL,
    [SERNO]           VARCHAR (5)  NULL,
    [FATURANO]        VARCHAR (7)  NULL,
    [MTOPT]           FLOAT        NOT NULL,
    [KTOPT]           FLOAT        NOT NULL,
    [DTOPT]           FLOAT        NULL,
    [GEL]             VARCHAR (1)  NULL,
    [FIYATARTISMUAF]  VARCHAR (1)  NULL,
    [ODANO]           VARCHAR (10) NULL,
    [ODAUCR]          CHAR (1)     NULL,
    [CIKTAR]          DATETIME     NULL,
    [HZLNO]           SMALLINT     NULL,
    [SIRAID]          FLOAT        NULL,
    [PROTOKOLNO]      VARCHAR (6)  NULL,
    [PROVIZYONNO]     VARCHAR (40) NULL,
    [OZELNOT]         VARCHAR (20) NULL,
    [USER_ID]         VARCHAR (20) NOT NULL,
    [DATE_CREATE]     DATETIME     NOT NULL,
    [USER_ID_UPDATE]  VARCHAR (20) NULL,
    [DATE_UPDATE]     DATETIME     NULL,
    [TAKIPNO]         VARCHAR (50) NULL,
    [TAKIPSEND]       VARCHAR (50) NULL,
    [DESTEKPSG]       VARCHAR (50) NULL,
    [XLOCK]           BIT          NULL,
    [TAKIPTUTAR]      FLOAT        NULL,
    [PSG]             VARCHAR (50) NULL,
    [SEVKTAKIPNO]     VARCHAR (50) NULL,
    [ICMALNO]         VARCHAR (50) NULL,
    [ICMALTARIHI]     DATETIME     NULL,
    [PAKET]           VARCHAR (50) NULL,
    [MYBUTKOD]        VARCHAR (50) NULL,
    [MEDFATTUTAR]     FLOAT        NULL,
    [STURU]           VARCHAR (50) NULL,
    [TABKODU]         VARCHAR (50) NULL,
    [TESLIMNO]        VARCHAR (50) NULL,
    [MCIKISTARIHI]    DATETIME     NULL,
    [REFGUNSAY]       VARCHAR (50) NULL,
    [MEDFATURANO]     VARCHAR (50) NULL,
    [MEDFATURATARIHI] DATETIME     NULL
);

