CREATE TABLE [dbo].[BEHAND_DETAY_KONTROL] (
    [KONTROL_ID]    NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [SERNO]         VARCHAR (5)  NOT NULL,
    [KONTROLTARIHI] DATETIME     NOT NULL,
    [ARZT]          VARCHAR (4)  NOT NULL,
    [SERVIS]        VARCHAR (2)  NOT NULL,
    [USER_ID]       VARCHAR (20) NOT NULL,
    [DATE_CREATE]   DATETIME     NOT NULL
);

