CREATE TABLE [dbo].[BEHAND] (
    [KNR]             VARCHAR (6)  NOT NULL,
    [SNR]             VARCHAR (3)  NOT NULL,
    [BHDAT]           DATETIME     NOT NULL,
    [SEVKGECSURE]     SMALLINT     NOT NULL,
    [FATURATARIHI]    DATETIME     NULL,
    [ARZT]            VARCHAR (4)  NOT NULL,
    [SERVIS]          VARCHAR (2)  NOT NULL,
    [AMBU]            VARCHAR (1)  NOT NULL,
    [IMPF2]           VARCHAR (1)  NULL,
    [KAR_NO]          VARCHAR (7)  NULL,
    [ARSIVNO]         VARCHAR (7)  NULL,
    [TES_ANA]         VARCHAR (2)  NULL,
    [TES_CODE]        VARCHAR (15) NULL,
    [HASTALIKSONU]    VARCHAR (1)  NULL,
    [AMELIYAT]        VARCHAR (1)  NULL,
    [DOGUM]           VARCHAR (1)  NULL,
    [UCRETDURUMU]     VARCHAR (1)  NULL,
    [SERNO]           VARCHAR (5)  NULL,
    [FATURANO]        VARCHAR (7)  NULL,
    [MTOPT]           FLOAT        NOT NULL,
    [KTOPT]           FLOAT        NOT NULL,
    [DTOPT]           FLOAT        NULL,
    [GEL]             VARCHAR (1)  NULL,
    [FIYATARTISMUAF]  VARCHAR (1)  NULL,
    [ODANO]           VARCHAR (10) NULL,
    [ODAUCR]          CHAR (1)     NULL,
    [CIKTAR]          DATETIME     NULL,
    [HZLNO]           SMALLINT     NULL,
    [SIRAID]          FLOAT        NULL,
    [PROTOKOLNO]      VARCHAR (6)  NULL,
    [PROVIZYONNO]     VARCHAR (40) NULL,
    [OZELNOT]         VARCHAR (20) NULL,
    [USER_ID]         VARCHAR (20) NOT NULL,
    [DATE_CREATE]     DATETIME     NOT NULL,
    [USER_ID_UPDATE]  VARCHAR (20) NULL,
    [DATE_UPDATE]     DATETIME     NULL,
    [TAKIPNO]         VARCHAR (20) NULL,
    [TAKIPSEND]       VARCHAR (2)  NULL,
    [DESTEKPSG]       VARCHAR (10) NULL,
    [XLOCK]           BIT          NULL,
    [TAKIPTUTAR]      FLOAT        NULL,
    [PSG]             VARCHAR (10) NULL,
    [STURU]           VARCHAR (2)  NULL,
    [TABKODU]         VARCHAR (2)  NULL,
    [ICMALNO]         VARCHAR (10) NULL,
    [ICMALTARIHI]     DATETIME     NULL,
    [SEVKTAKIPNO]     VARCHAR (20) NOT NULL,
    [paket]           VARCHAR (2)  NULL,
    [MYBUTKOD]        VARCHAR (20) NULL,
    [MEDFATTUTAR]     FLOAT        NULL,
    [TESLIMNO]        VARCHAR (30) NULL,
    [MCIKISTARIHI]    DATETIME     NULL,
    [REFGUNSAY]       VARCHAR (4)  NULL,
    [MEDFATURANO]     VARCHAR (20) NULL,
    [MEDFATURATARIHI] DATETIME     NULL,
    [TAKIPTURU]       VARCHAR (10) NULL,
    [DESFATURATARIHI] DATETIME     NULL,
    [HASTABASNO]      VARCHAR (10) NULL,
    [ILISKILITAKIPNO] VARCHAR (20) NULL,
    [TEDAVITURU]      VARCHAR (4)  NULL,
    [FARKTUTAR]       FLOAT        NULL,
    [ARACIKLAMA]      VARCHAR (50) NULL,
    [ARGONDERILDI]    BIT          NULL,
    [ARHATA]          VARCHAR (50) NULL,
    [CIKSAAT]         VARCHAR (10) NOT NULL,
    [DURUM]           NCHAR (1)    NULL,
    [KONTROLTAR]      DATE         NULL,
    [KONTROLT]        DATETIME     NULL,
    [KONTROL]         NCHAR (1)    NULL,
    [HAVUZ_DURUMU]    VARCHAR (2)  NULL
);

