CREATE TABLE [dbo].[BILGISISTEMLERIPERSONEL_112] (
    [SIRANO]         INT           IDENTITY (1, 1) NOT NULL,
    [PERSADI]        NVARCHAR (50) NULL,
    [PERSOYADI]      NVARCHAR (50) NULL,
    [PERSNO]         NVARCHAR (50) NULL,
    [PERBRANS]       NVARCHAR (50) NULL,
    [PERBKODU]       NVARCHAR (50) NULL,
    [PERGOREV]       NVARCHAR (50) NULL,
    [PERTELEFON]     NVARCHAR (50) NULL,
    [PERNBASTARIH]   NVARCHAR (50) NULL,
    [PERBITTARIH]    NVARCHAR (50) NULL,
    [PERNOBETTIPI]   INT           NULL,
    [PERNOBETDURUM]  INT           NULL,
    [PERACIKLAMA]    NVARCHAR (50) NULL,
    [TARIH]          DATETIME      NULL,
    [GONDERMETARIHI] DATETIME      NULL,
    [USER112]        NVARCHAR (50) NULL,
    [GONDERILDI]     NVARCHAR (50) NULL,
    [HATA]           VARCHAR (200) NULL
);

