CREATE TABLE [dbo].[DOKTOR_STDRAP] (
    [TANIM]   VARCHAR (2)  NOT NULL,
    [GRUP]    VARCHAR (3)  NOT NULL,
    [CODE]    VARCHAR (15) NOT NULL,
    [ARZT]    VARCHAR (4)  NOT NULL,
    [RAPORNO] INT          NULL
);

