CREATE TABLE [dbo].[ECZPOLRECETELER] (
    [KNR]            VARCHAR (6)  NULL,
    [TARIH]          DATETIME     NOT NULL,
    [RECKNR]         VARCHAR (5)  NOT NULL,
    [PSG]            VARCHAR (6)  NULL,
    [RECNO]          VARCHAR (10) NULL,
    [PROTOKOLNO]     VARCHAR (7)  NULL,
    [RECTIP]         CHAR (1)     NOT NULL,
    [SIRANO]         VARCHAR (6)  NULL,
    [HASTAADI]       VARCHAR (50) NULL,
    [SIGORTANO]      VARCHAR (15) NULL,
    [KURUM]          VARCHAR (30) NULL,
    [ARZT]           VARCHAR (4)  NULL,
    [SERVIS]         VARCHAR (2)  NULL,
    [NORMALILAC]     FLOAT        NOT NULL,
    [RAPORLUILAC]    FLOAT        NOT NULL,
    [BEDHASAITILAC]  FLOAT        NOT NULL,
    [HASKATPAY]      FLOAT        NOT NULL,
    [GENELTOPLAM]    FLOAT        NOT NULL,
    [HASTATOPLAM]    FLOAT        NOT NULL,
    [ALACAK]         FLOAT        NOT NULL,
    [MUAYENE]        FLOAT        NOT NULL,
    [YUVARLAMA]      FLOAT        NOT NULL,
    [BILGKATPAY]     FLOAT        NOT NULL,
    [EKUCRET]        FLOAT        NOT NULL,
    [DURUM]          VARCHAR (1)  NULL,
    [KASA]           VARCHAR (1)  NULL,
    [KASANO]         VARCHAR (8)  NULL,
    [USER_ID]        VARCHAR (20) NOT NULL,
    [DATE_CREATE]    DATETIME     NOT NULL,
    [USER_ID_UPDATE] VARCHAR (20) NULL,
    [DATE_UPDATE]    DATETIME     NULL
);

