CREATE TABLE [dbo].[ETKEN_MADDE] (
    [KODU]     VARCHAR (20)  NOT NULL,
    [ACIKLAMA] VARCHAR (100) NULL,
    [ICERIK]   VARCHAR (50)  NULL,
    [FORM]     VARCHAR (50)  NULL,
    [MIKTAR]   VARCHAR (50)  NULL
);

