CREATE TABLE [dbo].[FATURA] (
    [KNR]            VARCHAR (6)   NOT NULL,
    [FATURA_ID]      VARCHAR (8)   NOT NULL,
    [SLNR]           VARCHAR (10)  NOT NULL,
    [FATURANO]       VARCHAR (20)  NOT NULL,
    [FATURATARIHI]   DATETIME      NOT NULL,
    [HIZMETTUTARI]   FLOAT         NOT NULL,
    [INDIRIM]        FLOAT         NOT NULL,
    [KDVTUTARI]      FLOAT         NOT NULL,
    [YUVARLAMA]      FLOAT         NOT NULL,
    [FATURATUTARI]   FLOAT         NOT NULL,
    [KDVORANI]       VARCHAR (1)   NOT NULL,
    [NAME]           VARCHAR (100) NOT NULL,
    [FATURATIPI]     VARCHAR (1)   NOT NULL,
    [VEZNE]          VARCHAR (2)   NOT NULL,
    [FAK]            VARCHAR (2)   NOT NULL,
    [ZHLKZ]          VARCHAR (2)   NULL,
    [PSG]            VARCHAR (6)   NULL,
    [ISIPTAL]        VARCHAR (1)   NULL,
    [ISODENDI]       VARCHAR (1)   NULL,
    [MAKNO]          VARCHAR (7)   NULL,
    [USER_ID]        VARCHAR (20)  NOT NULL,
    [DATE_CREATE]    DATETIME      NOT NULL,
    [USER_ID_UPDATE] VARCHAR (20)  NULL,
    [DATE_UPDATE]    DATETIME      NULL,
    [mk]             CHAR (1)      NOT NULL,
    [teslimNo]       VARCHAR (10)  NULL,
    [MAKBUZNO]       VARCHAR (10)  NULL,
    [SEC]            BIT           NULL,
    [KALAN]          FLOAT         NULL,
    [AMAKNO]         VARCHAR (50)  NULL,
    [IPTAL_NEDENI]   VARCHAR (50)  NULL
);

