CREATE TABLE [dbo].[HIZMET_DIGER_AD] (
    [TANIM]   VARCHAR (2)   NOT NULL,
    [GRUP]    VARCHAR (3)   NOT NULL,
    [CODE]    VARCHAR (15)  NOT NULL,
    [FIYLIST] VARCHAR (2)   NOT NULL,
    [NAME1]   VARCHAR (100) NOT NULL
);

