CREATE TABLE [dbo].[HIZMET_DIGER_KOD21] (
    [TANIM]   VARCHAR (2)   NOT NULL,
    [GRUP]    VARCHAR (3)   NOT NULL,
    [CODE]    VARCHAR (15)  NOT NULL,
    [FIYLIST] VARCHAR (2)   NOT NULL,
    [CODE1]   VARCHAR (15)  NOT NULL,
    [NAME1]   VARCHAR (250) NULL
);

