CREATE TABLE [dbo].[HIZMET_DIGER_KOD] (
    [TANIM]   VARCHAR (2)  NOT NULL,
    [GRUP]    VARCHAR (3)  NOT NULL,
    [CODE]    VARCHAR (15) NOT NULL,
    [FIYLIST] VARCHAR (2)  NOT NULL,
    [CODE1]   VARCHAR (15) NOT NULL,
    [BUT]     VARCHAR (1)  NULL
);

