CREATE TABLE [dbo].[HIZMETDOKTORYUZDE] (
    [TANIM] VARCHAR (2)  NOT NULL,
    [GRUP]  VARCHAR (3)  NOT NULL,
    [CODE]  VARCHAR (15) NOT NULL,
    [ARZT]  VARCHAR (4)  NOT NULL,
    [YUZDE] FLOAT        NOT NULL
);

