CREATE TABLE [dbo].[HUZUREVI] (
    [KNR]          VARCHAR (6) NOT NULL,
    [GIRISTARIHI]  DATETIME    NOT NULL,
    [CIKISTARIHI]  DATETIME    NULL,
    [UCRTIPI]      CHAR (5)    NOT NULL,
    [SABITTUTAR]   FLOAT       NOT NULL,
    [HASTANEDE]    CHAR (1)    NOT NULL,
    [TAHAKKUKGUNU] SMALLINT    NOT NULL
);

