CREATE TABLE [dbo].[ILAC_ATC_INDEX] (
    [H_ID]        INT           IDENTITY (1, 1) NOT NULL,
    [CODE]        VARCHAR (50)  NULL,
    [ATCNO]       VARCHAR (50)  NULL,
    [ATCINDEX]    VARCHAR (50)  NULL,
    [ATCAD]       VARCHAR (200) NULL,
    [ATCARAMAAD]  VARCHAR (200) NULL,
    [PARENTATCNO] VARCHAR (50)  NULL,
    [MAINATCNO]   VARCHAR (50)  NULL,
    [ACIKLAMA]    VARCHAR (200) NULL
);

