CREATE TABLE [dbo].[ILAC] (
    [KNR]    VARCHAR (50)  NULL,
    [SNR]    VARCHAR (50)  NULL,
    [CODE]   VARCHAR (50)  NULL,
    [NAME1]  VARCHAR (500) NULL,
    [ADET]   VARCHAR (50)  NULL,
    [TUTARI] FLOAT         NULL
);

