CREATE TABLE [dbo].[KEYDAT1] (
    [SLK]  VARCHAR (2)   NOT NULL,
    [SLB]  VARCHAR (10)  NOT NULL,
    [SLT]  VARCHAR (80)  NOT NULL,
    [SLX]  FLOAT         NULL,
    [SLY]  FLOAT         NULL,
    [SLZ]  FLOAT         NULL,
    [SLVV] VARCHAR (100) NULL,
    [SLXX] VARCHAR (100) NULL,
    [SLYY] VARCHAR (100) NULL,
    [SLZZ] VARCHAR (100) NULL,
    [SLXA] FLOAT         NULL
);

