CREATE TABLE [dbo].[KULLANICI_YETKI] (
    [USER_ID]    VARCHAR (20) NOT NULL,
    [FORMNAME]   VARCHAR (50) NOT NULL,
    [OBJECTNAME] VARCHAR (50) NOT NULL,
    [TABNUMBER]  SMALLINT     NULL,
    [YETKI]      CHAR (1)     NOT NULL
);

