CREATE TABLE [dbo].[KULLANICILAR_112] (
    [SIRANO]       INT           IDENTITY (1, 1) NOT NULL,
    [KULLANICIADI] NVARCHAR (50) NULL,
    [SIFRE]        NVARCHAR (50) NULL,
    [KTIPI]        NVARCHAR (50) NULL
);

