CREATE TABLE [dbo].[KURHIZIL] (
    [KKNR]           VARCHAR (6)   NOT NULL,
    [KNR]            VARCHAR (6)   NOT NULL,
    [SNR]            VARCHAR (3)   NOT NULL,
    [SIRANO]         FLOAT         NOT NULL,
    [AKOD]           VARCHAR (2)   NULL,
    [TANIM]          VARCHAR (2)   NOT NULL,
    [GRUP]           VARCHAR (3)   NOT NULL,
    [CODE]           VARCHAR (15)  NOT NULL,
    [ARZT]           VARCHAR (4)   NOT NULL,
    [ARZT2]          VARCHAR (4)   NOT NULL,
    [ADET]           FLOAT         NOT NULL,
    [UNITE]          VARCHAR (2)   NULL,
    [NAME1]          VARCHAR (100) NOT NULL,
    [SATISF]         FLOAT         NOT NULL,
    [KSATISF]        FLOAT         NOT NULL,
    [KDV]            FLOAT         NOT NULL,
    [TARIH]          DATETIME      NOT NULL,
    [PSG]            VARCHAR (6)   NOT NULL,
    [HZLNO]          SMALLINT      NULL,
    [USER_ID]        VARCHAR (20)  NOT NULL,
    [DATE_CREATE]    DATETIME      NOT NULL,
    [USER_ID_UPDATE] VARCHAR (20)  NULL,
    [DATE_UPDATE]    DATETIME      NULL,
    [MAKNO]          VARCHAR (8)   NULL,
    [KFATNO]         VARCHAR (7)   NULL,
    [ISLENDIMI]      VARCHAR (2)   NULL,
    [PAKET]          VARCHAR (2)   NULL
);

