CREATE TABLE [dbo].[LABKITSTOK] (
    [LABTANIM]  VARCHAR (2)  NOT NULL,
    [LABCODE]   VARCHAR (15) NOT NULL,
    [STOKCODE]  VARCHAR (15) NOT NULL,
    [STOKGRUP]  VARCHAR (3)  NOT NULL,
    [STOKAKOD]  VARCHAR (2)  NOT NULL,
    [STOKTANIM] VARCHAR (2)  NOT NULL,
    [STOKADET]  FLOAT        NOT NULL
);

