CREATE TABLE [dbo].[LOGADRESDELETED] (
    [KNR]         VARCHAR (6)  NOT NULL,
    [HASTAADI]    VARCHAR (15) NULL,
    [HASTASOYADI] VARCHAR (20) NULL,
    [USER_ID]     VARCHAR (20) NOT NULL,
    [DATE_CREATE] DATETIME     NOT NULL
);

