CREATE TABLE [dbo].[LOGBARCODDEGISTI] (
    [TANIM]       VARCHAR (2)  NOT NULL,
    [EKOD]        VARCHAR (15) NOT NULL,
    [YKOD]        VARCHAR (15) NOT NULL,
    [USER_ID]     VARCHAR (20) NOT NULL,
    [DATE_CREATE] DATETIME     NOT NULL
);

