CREATE TABLE [dbo].[LOGDOKTORSERVISDEGISTI] (
    [DSD_ID]      NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [KNR]         VARCHAR (6)  NOT NULL,
    [SNR]         VARCHAR (3)  NOT NULL,
    [ETARIH]      DATETIME     NOT NULL,
    [YTARIH]      DATETIME     NOT NULL,
    [ESERVIS]     VARCHAR (2)  NOT NULL,
    [YSERVIS]     VARCHAR (2)  NOT NULL,
    [EARZT]       VARCHAR (4)  NOT NULL,
    [YARZT]       VARCHAR (4)  NOT NULL,
    [USER_ID]     VARCHAR (20) NOT NULL,
    [DATE_CREATE] DATETIME     NOT NULL
);

