CREATE TABLE [dbo].[LOGHASTAKARTIBIRLESTI] (
    [HKB_ID]        NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [YENIKNR]       VARCHAR (6)  NOT NULL,
    [ESKIKNR]       VARCHAR (6)  NOT NULL,
    [YENISNRARALIK] VARCHAR (10) NOT NULL,
    [USER_ID]       VARCHAR (20) NOT NULL,
    [DATE_CREATE]   DATETIME     NOT NULL
);

