CREATE TABLE [dbo].[LOGKODLARARASITRANSFER] (
    [TANIM]       VARCHAR (2)  NOT NULL,
    [AKOD]        VARCHAR (2)  NOT NULL,
    [EVRAKNO]     VARCHAR (10) NOT NULL,
    [KACTANE]     SMALLINT     NOT NULL,
    [USER_ID]     VARCHAR (20) NOT NULL,
    [DATE_CREATE] DATETIME     NOT NULL
);

