CREATE TABLE [dbo].[MEDDIABETDOKTORLAR] (
    [SNO]      INT          IDENTITY (1, 1) NOT NULL,
    [KNR]      VARCHAR (6)  NULL,
    [SNR]      VARCHAR (3)  NULL,
    [DRTESCIL] VARCHAR (20) NULL,
    [DRBRANS]  VARCHAR (4)  NULL,
    [DRDM]     VARCHAR (1)  NULL
);

