CREATE TABLE [dbo].[MEDRAPORTESHIS] (
    [KNR]           VARCHAR (50)  NOT NULL,
    [SNR]           VARCHAR (50)  NOT NULL,
    [RAPORBASTARIH] DATETIME      NULL,
    [RAPORBITTARIH] DATETIME      NULL,
    [RAPORTESKOD]   VARCHAR (50)  NULL,
    [RAPORACIKLAMA] VARCHAR (250) NULL,
    [ICD10TANIKODU] VARCHAR (20)  NULL
);

