CREATE TABLE [dbo].[MEDRAPORDOKTOR] (
    [SNO]      INT          IDENTITY (1, 1) NOT NULL,
    [KNR]      VARCHAR (6)  NULL,
    [SNR]      VARCHAR (3)  NULL,
    [DRAD]     VARCHAR (50) NULL,
    [DRSOYAD]  VARCHAR (50) NULL,
    [BRANS]    VARCHAR (10) NULL,
    [TESCILNO] VARCHAR (20) NULL,
    [TIPI]     VARCHAR (10) NULL
);

