CREATE TABLE [dbo].[MuhasebeLinkTablosu] (
    [ID]           INT        IDENTITY (1, 1) NOT NULL,
    [FisTarihi]    DATE       NULL,
    [HesapKodu]    NCHAR (20) NULL,
    [BaBs]         NCHAR (10) NULL,
    [Aciklama]     NCHAR (50) NULL,
    [Unvani]       NCHAR (30) NULL,
    [BA]           NCHAR (1)  NULL,
    [ParaBirimi]   TINYINT    NULL,
    [Tutar]        FLOAT      NULL,
    [DovizCinsi]   NCHAR (5)  NULL,
    [DovizKuru]    FLOAT      NULL,
    [DovizTutar]   FLOAT      NULL,
    [VergiHesapNo] NCHAR (15) NULL,
    [VergiDairesi] NCHAR (20) NULL,
    [EvrakTarihi]  DATE       NULL,
    [EvrakNo]      NCHAR (10) NULL,
    [EvrakTipi]    INT        NULL,
    [EvrakSayisi]  INT        NULL,
    [KDVOrani]     FLOAT      NULL,
    [FisTipi]      NCHAR (5)  NULL,
    [FisNo]        INT        NULL,
    [FisKodu]      NCHAR (5)  NULL,
    [MaddeNo]      INT        NULL,
    [IslemTipi]    INT        NULL,
    [VadeTarihi]   DATETIME   NULL,
    [Ulke]         INT        NULL
);

