CREATE TABLE [dbo].[NECATI] (
    [KNR]            VARCHAR (6)   NOT NULL,
    [SNR]            VARCHAR (3)   NOT NULL,
    [SIRANO]         FLOAT         NULL,
    [AKOD]           VARCHAR (2)   NULL,
    [TANIM]          VARCHAR (2)   NOT NULL,
    [GRUP]           VARCHAR (3)   NOT NULL,
    [CODE]           VARCHAR (15)  NOT NULL,
    [ARZT]           VARCHAR (4)   NOT NULL,
    [ARZT2]          VARCHAR (4)   NOT NULL,
    [ADET]           FLOAT         NOT NULL,
    [UNITE]          VARCHAR (2)   NULL,
    [NAME1]          VARCHAR (100) NOT NULL,
    [SATISF]         FLOAT         NOT NULL,
    [KSATISF]        FLOAT         NOT NULL,
    [DSATISF]        FLOAT         NULL,
    [KDV]            FLOAT         NOT NULL,
    [TARIH]          DATETIME      NOT NULL,
    [PSG]            VARCHAR (6)   NOT NULL,
    [HZLNO]          SMALLINT      NULL,
    [USER_ID]        VARCHAR (20)  NOT NULL,
    [DATE_CREATE]    DATETIME      NOT NULL,
    [USER_ID_UPDATE] VARCHAR (20)  NULL,
    [DATE_UPDATE]    DATETIME      NULL,
    [MAKNO]          VARCHAR (8)   NULL,
    [KFATNO]         VARCHAR (7)   NULL,
    [FATURAEDILSIN]  VARCHAR (1)   NULL,
    [ISLENDIMI]      VARCHAR (50)  NULL,
    [PAKET]          VARCHAR (1)   NULL,
    [LRGOR]          VARCHAR (1)   NULL,
    [BUTCODE]        VARCHAR (20)  NULL,
    [BUTNAME]        VARCHAR (100) NULL,
    [ESKI_SATISF]    FLOAT         NULL,
    [KABUL]          VARCHAR (1)   NULL,
    [ISODENDI]       VARCHAR (50)  NULL,
    [CARIFIYAT]      VARCHAR (50)  NULL,
    [ODEMETARIHI]    DATETIME      NULL,
    [ISDURUM]        VARCHAR (50)  NULL,
    [PSEANS]         VARCHAR (50)  NULL,
    [SAGSOL]         VARCHAR (50)  NULL,
    [EUSCORE]        CHAR (10)     NULL,
    [HMAKNO]         VARCHAR (50)  NULL,
    [HODENDI]        VARCHAR (50)  NULL,
    [AMAKNO]         VARCHAR (50)  NULL,
    [DEGER]          VARCHAR (50)  NULL
);

