CREATE TABLE [dbo].[ODALAR] (
    [ODANO]      VARCHAR (10) NOT NULL,
    [SERVIS]     VARCHAR (2)  NOT NULL,
    [KAT]        VARCHAR (2)  NULL,
    [DTELNO]     VARCHAR (4)  NOT NULL,
    [DURUM]      VARCHAR (1)  NOT NULL,
    [KNR]        VARCHAR (6)  NULL,
    [SNR]        VARCHAR (3)  NULL,
    [OZELNOT]    VARCHAR (50) NULL,
    [HIZMETKODU] VARCHAR (20) NULL
);

