CREATE TABLE [dbo].[ORALDIYAGNOZ] (
    [DIYAGNOZ_ID]      NUMERIC (18)   NOT NULL,
    [KNR]              VARCHAR (6)    NOT NULL,
    [TARIH]            DATETIME       NOT NULL,
    [KALP]             CHAR (1)       NULL,
    [DIABET]           CHAR (1)       NULL,
    [ALLERJI]          CHAR (1)       NULL,
    [GUATR]            CHAR (1)       NULL,
    [TUBERKULOZ]       CHAR (1)       NULL,
    [SARILIK]          CHAR (1)       NULL,
    [HAMILELIK]        CHAR (1)       NULL,
    [TANSIYON]         CHAR (1)       NULL,
    [BAKANDR]          VARCHAR (4)    NULL,
    [RVAPSE]           CHAR (1)       NULL,
    [RVALVEOLIT]       CHAR (1)       NULL,
    [RVPERIODONTITIS]  CHAR (1)       NULL,
    [RVGINGIVITIS]     CHAR (1)       NULL,
    [RVFIRCA]          CHAR (1)       NULL,
    [AMELIYATHANE]     CHAR (32)      NULL,
    [CERRAHI]          CHAR (32)      NULL,
    [CERRAHI2]         CHAR (32)      NULL,
    [TEDAVI]           CHAR (32)      NULL,
    [RONTGEN]          CHAR (32)      NULL,
    [RONTPAN]          CHAR (1)       NULL,
    [RONTSEF]          CHAR (1)       NULL,
    [HRKAUTP]          CHAR (1)       NULL,
    [HRKATP]           CHAR (1)       NULL,
    [HRKUTP]           CHAR (1)       NULL,
    [HRKAUPP]          CHAR (1)       NULL,
    [HRKAPP]           CHAR (1)       NULL,
    [HRKUPP]           CHAR (1)       NULL,
    [HRKVURUK]         CHAR (1)       NULL,
    [HRKTAMIR]         CHAR (1)       NULL,
    [HRKDISILAVESI]    CHAR (1)       NULL,
    [HRKBESLEME]       CHAR (1)       NULL,
    [SABIT]            CHAR (1)       NULL,
    [SABITSOKUM]       CHAR (32)      NULL,
    [SABITYAPIM]       CHAR (32)      NULL,
    [SABITFASET]       CHAR (32)      NULL,
    [SABITSIMENTASYON] CHAR (32)      NULL,
    [ORTODONTI]        CHAR (1)       NULL,
    [PERIODONTI]       CHAR (1)       NULL,
    [NOT1]             VARCHAR (2000) NULL,
    [USER_ID]          VARCHAR (20)   NULL,
    [DATE_CREATE]      DATETIME       NULL,
    [USER_ID_UPDATE]   VARCHAR (20)   NULL,
    [DATE_UPDATE]      DATETIME       NULL
);

