CREATE TABLE [dbo].[OTOMATIK_MUAYENELER] (
    [SERVISKODU] VARCHAR (4)  NOT NULL,
    [TANIM]      VARCHAR (4)  NOT NULL,
    [GRUP]       VARCHAR (4)  NOT NULL,
    [CODE]       VARCHAR (50) NOT NULL,
    [KATILIM]    VARCHAR (50) NULL,
    [AYKATILIM]  VARCHAR (50) NULL
);

