CREATE TABLE [dbo].[RANDEVULARRUHANI] (
    [RUHANIKODU] VARCHAR (4)  NOT NULL,
    [TARIH]      DATETIME     NOT NULL,
    [SAAT]       VARCHAR (5)  NOT NULL,
    [ISLEM_ID]   NUMERIC (18) NOT NULL
);

