CREATE TABLE [dbo].[RANDEVULOCKS] (
    [SLK]      CHAR (2)     NOT NULL,
    [SLB]      CHAR (10)    NOT NULL,
    [AY]       SMALLINT     NOT NULL,
    [GUNBASLA] SMALLINT     NOT NULL,
    [SAAT]     VARCHAR (5)  NOT NULL,
    [USER_ID]  VARCHAR (20) NOT NULL
);

