CREATE TABLE [dbo].[RDYKULLANILANFILMLER] (
    [RKF_ID]    INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [TANIM]     VARCHAR (2)  NOT NULL,
    [GRUP]      VARCHAR (3)  NOT NULL,
    [CODE]      VARCHAR (15) NOT NULL,
    [KNR]       VARCHAR (6)  NOT NULL,
    [SNR]       VARCHAR (3)  NOT NULL,
    [TARIH]     DATETIME     NOT NULL,
    [FILMEBADI] VARCHAR (2)  NOT NULL
);

