CREATE TABLE [dbo].[rtblOzetAnaIslem] (
    [RowNumber]   BIGINT         NULL,
    [Key1]        NVARCHAR (255) NULL,
    [AdetC]       FLOAT          NOT NULL,
    [AdetP]       FLOAT          NOT NULL,
    [AdetP1]      FLOAT          NOT NULL,
    [AdetY]       FLOAT          NULL,
    [AdetY1]      FLOAT          NULL,
    [HastaC]      INT            NOT NULL,
    [HastaP]      INT            NOT NULL,
    [HastaP1]     INT            NOT NULL,
    [HastaY]      FLOAT          NULL,
    [HastaY1]     FLOAT          NULL,
    [ToplamC]     FLOAT          NOT NULL,
    [ToplamP]     FLOAT          NOT NULL,
    [ToplamP1]    FLOAT          NOT NULL,
    [ToplamY]     FLOAT          NULL,
    [ToplamY1]    FLOAT          NULL,
    [KisiBasiC]   FLOAT          NULL,
    [KisiBasiP]   FLOAT          NULL,
    [KisiBasiP1]  FLOAT          NULL,
    [KisiBasiY]   FLOAT          NULL,
    [KisiBasiY1]  FLOAT          NULL,
    [IslemBasiC]  FLOAT          NULL,
    [IslemBasiP]  FLOAT          NULL,
    [IslemBasiP1] FLOAT          NULL,
    [IslemBasiY]  FLOAT          NULL,
    [IslemBasiY1] FLOAT          NULL
);

