CREATE TABLE [dbo].[SAGLIKKURULU] (
    [ID]                   INT           IDENTITY (1, 1) NOT NULL,
    [KNR]                  VARCHAR (6)   NULL,
    [TIPI]                 CHAR (1)      NULL,
    [RAPORTARIHI]          DATETIME      NULL,
    [RAPORNO]              VARCHAR (15)  NULL,
    [SAGLIKURUMUADI]       VARCHAR (80)  NULL,
    [ADISOYADI]            VARCHAR (50)  NULL,
    [BABAADI]              VARCHAR (50)  NULL,
    [DOGUMYERI]            VARCHAR (50)  NULL,
    [DOGUMTARIHI]          DATETIME      NULL,
    [RAPORISTEKNEDENI]     VARCHAR (100) NULL,
    [SEVKEDENKURUM]        VARCHAR (50)  NULL,
    [GOREVI]               VARCHAR (50)  NULL,
    [SICILNO]              VARCHAR (20)  NULL,
    [YAKINLIGI]            VARCHAR (50)  NULL,
    [MEMURUNADISOYADI]     VARCHAR (50)  NULL,
    [BOY]                  VARCHAR (5)   NULL,
    [KILO]                 VARCHAR (5)   NULL,
    [GOGUS]                VARCHAR (5)   NULL,
    [BAS]                  VARCHAR (5)   NULL,
    [RONTGEN]              VARCHAR (255) NULL,
    [LABORATUVAR]          VARCHAR (255) NULL,
    [TANI]                 TEXT          NULL,
    [TANI1]                VARCHAR (255) NULL,
    [KARAR]                TEXT          NULL,
    [KARAR1]               VARCHAR (255) NULL,
    [MURACAATTARIHI]       DATETIME      NULL,
    [MUAYENEYEGONDEREN]    VARCHAR (50)  NULL,
    [KURUMKISISEL]         CHAR (1)      NULL,
    [NOROLOJI]             CHAR (1)      NULL,
    [RUH]                  CHAR (1)      NULL,
    [GOZ]                  CHAR (1)      NULL,
    [KBB]                  CHAR (1)      NULL,
    [BATIN]                CHAR (1)      NULL,
    [UROLOJI]              CHAR (1)      NULL,
    [ICHASTALIKLAR]        CHAR (1)      NULL,
    [SINDIRIM]             CHAR (1)      NULL,
    [HEMATOLOJI]           CHAR (1)      NULL,
    [ORTOPEDI]             CHAR (1)      NULL,
    [DERI]                 CHAR (1)      NULL,
    [GOGUSDAMAR]           CHAR (1)      NULL,
    [ONKOLOJI]             CHAR (1)      NULL,
    [YANIK]                CHAR (1)      NULL,
    [TESHIS]               TEXT          NULL,
    [TESHIS1]              VARCHAR (255) NULL,
    [CALISABILIR]          CHAR (1)      NULL,
    [CALISAMAZISALANLARI]  VARCHAR (255) NULL,
    [RAPORUNKULLANIMAMACI] VARCHAR (100) NULL,
    [SUREKLI]              CHAR (1)      NULL,
    [KONTROLSURESI]        VARCHAR (5)   NULL,
    [CALISMAKAYBI]         VARCHAR (3)   NULL,
    [SERVIS1]              VARCHAR (50)  NULL,
    [DOKTOR1]              VARCHAR (50)  NULL,
    [SERVIS2]              VARCHAR (50)  NULL,
    [DOKTOR2]              VARCHAR (50)  NULL,
    [SERVIS3]              VARCHAR (50)  NULL,
    [DOKTOR3]              VARCHAR (50)  NULL,
    [SERVIS4]              VARCHAR (50)  NULL,
    [DOKTOR4]              VARCHAR (50)  NULL,
    [SERVIS5]              VARCHAR (50)  NULL,
    [DOKTOR5]              VARCHAR (50)  NULL,
    [SERVIS6]              VARCHAR (50)  NULL,
    [DOKTOR6]              VARCHAR (50)  NULL,
    [SERVIS7]              VARCHAR (50)  NULL,
    [DOKTOR7]              VARCHAR (50)  NULL,
    [SERVIS8]              VARCHAR (50)  NULL,
    [DOKTOR8]              VARCHAR (50)  NULL,
    [SERVIS9]              VARCHAR (50)  NULL,
    [DOKTOR9]              VARCHAR (50)  NULL,
    [KURULBASKANI]         VARCHAR (50)  NULL,
    [BASHEKIM]             VARCHAR (50)  NULL,
    [USER_ID]              VARCHAR (20)  NOT NULL,
    [DATE_CREATE]          DATETIME      NOT NULL
);

