CREATE TABLE [dbo].[SATBEH] (
    [KNR]            VARCHAR (5)   NOT NULL,
    [SNR]            VARCHAR (3)   NOT NULL,
    [IRSALIYETARIHI] DATETIME      NOT NULL,
    [FATURATARIHI]   DATETIME      NOT NULL,
    [IRSALIYENO]     VARCHAR (10)  NOT NULL,
    [FATURANO]       VARCHAR (10)  NOT NULL,
    [ISKONTO]        FLOAT         NOT NULL,
    [ISKONTO1]       FLOAT         NOT NULL,
    [TOPLAM]         FLOAT         NOT NULL,
    [YUVARLAMA]      FLOAT         NOT NULL,
    [KDVTUTARI]      FLOAT         NOT NULL,
    [KDVYUVARLAMA]   FLOAT         NOT NULL,
    [GENELTOPLAM]    FLOAT         NOT NULL,
    [ILACSARF]       VARCHAR (1)   NULL,
    [TESELLUMNO]     VARCHAR (10)  NULL,
    [TESELLUMTARIHI] DATETIME      NULL,
    [ISLENDI]        VARCHAR (1)   NOT NULL,
    [USER_ID]        VARCHAR (20)  NOT NULL,
    [DATE_CREATE]    DATETIME      NOT NULL,
    [USER_ID_UPDATE] VARCHAR (20)  NULL,
    [DATE_UPDATE]    DATETIME      NULL,
    [IPTAL]          VARCHAR (1)   NULL,
    [ODEMETARIHI]    DATETIME      NULL,
    [ODEMETARIHIG]   DATETIME      NULL,
    [ODEMETUTAR]     FLOAT         NULL,
    [ODEMEACIKLAMA]  VARCHAR (150) NULL,
    [ISODENDI]       VARCHAR (1)   NULL,
    [ODEMESEKLI]     VARCHAR (1)   NULL,
    [SEC]            BIT           NULL,
    [MK]             BIT           NULL
);

