CREATE TABLE [dbo].[SILINEN_HIZMET] (
    [TANIM]    NVARCHAR (255) NULL,
    [GRUP]     NVARCHAR (255) NULL,
    [CODE]     NVARCHAR (255) NULL,
    [NAME1]    NVARCHAR (255) NULL,
    [APHIZMET] NVARCHAR (255) NULL,
    [LABTIPI]  NVARCHAR (255) NULL
);

