CREATE TABLE [dbo].[TET_ADRES_EK] (
    [KNR]                   VARCHAR (6)   NOT NULL,
    [ANNE_KAN_GRUBU]        INT           NULL,
    [BABA_KAN_GRUBU]        INT           NULL,
    [ANNE_DOGUM_TARIH]      DATETIME      NULL,
    [BABA_DOGUM_TARIH]      DATETIME      NULL,
    [ANNE_SİGARA]           BIT           NULL,
    [BABA_SİGARA]           BIT           NULL,
    [ANNE_EGITIM]           INT           NULL,
    [BABA_EGITIM]           INT           NULL,
    [ANNE_TEL]              VARCHAR (15)  NULL,
    [BABA_TEL]              VARCHAR (15)  NULL,
    [ANNE_EPOSTA]           VARCHAR (50)  NULL,
    [BABA_EPOSTA]           VARCHAR (50)  NULL,
    [DOGUM_MEKAN]           INT           NULL,
    [DOGUM_NOTLAR]          VARCHAR (50)  NULL,
    [GESTASYON_YAS]         INT           NULL,
    [HASTANE_KAL_SURE]      INT           NULL,
    [KOMPLIKASYON]          VARCHAR (200) NULL,
    [PRENATAL_OYKU]         VARCHAR (200) NULL,
    [DOGUM_SEKLI]           INT           NULL,
    [DOGUM_AGIRLIK]         INT           NULL,
    [DOGUM_BOY]             INT           NULL,
    [DOGUM_BAS]             INT           NULL,
    [DOGUM_AGPAR]           VARCHAR (200) NULL,
    [YENI_DOGAN_BASLANGIC]  INT           NULL,
    [YENI_DOGAN_SURE]       INT           NULL,
    [FOTOTERAPİ]            VARCHAR (200) NULL,
    [EXCHANGE]              VARCHAR (200) NULL,
    [YENI_DOGAN_TARAMA]     VARCHAR (20)  NULL,
    [YENI_DOGAN_DIGER]      VARCHAR (50)  NULL,
    [AKRABA_EVLILIK]        BIT           NULL,
    [AKRABA_EVLILIK_DERECE] VARCHAR (50)  NULL,
    [EBEVEYN_DURUM]         INT           NULL,
    [KARDES1_DOGUMTARIHI]   DATETIME      NULL,
    [KARDES2_DOGUMTARIHI]   DATETIME      NULL,
    [KARDES3_DOGUMTARIHI]   DATETIME      NULL,
    [KARDES1_CINSIYET]      BIT           NULL,
    [KARDES2_CINSIYET]      BIT           NULL,
    [KARDES3_CINSIYET]      BIT           NULL,
    [KARDES1_ADI]           VARCHAR (50)  NULL,
    [KARDES2_ADI]           VARCHAR (50)  NULL,
    [KARDES3_ADI]           VARCHAR (50)  NULL,
    [EBEVEYN_NOTLAR]        VARCHAR (50)  NULL,
    [ANTENATAL]             VARCHAR (250) NULL,
    [NATAL]                 VARCHAR (250) NULL,
    [POSTNATAL]             VARCHAR (250) NULL,
    [ILAC_ALERJI]           VARCHAR (250) NULL,
    [OPERASYON]             VARCHAR (250) NULL,
    [HASTALIK]              VARCHAR (250) NULL,
    [SOYGEÇMİŞ]             VARCHAR (250) NULL
);

