CREATE TABLE [dbo].[TET_ANAMNEZ_DETAY_SETRAK] (
    [KNR]          VARCHAR (6)  NOT NULL,
    [SNR]          VARCHAR (3)  NOT NULL,
    [TESHISKODU]   VARCHAR (10) NOT NULL,
    [GELISTARIHI]  DATETIME     NOT NULL,
    [TANITIPI]     VARCHAR (1)  NULL,
    [BIRINCILTANI] VARCHAR (1)  NULL,
    [SIRANO]       INT          NOT NULL,
    [MEDSIRANO]    VARCHAR (20) NULL,
    [MEDONAY]      VARCHAR (2)  NULL,
    [MEDOZDURUM]   VARCHAR (1)  NOT NULL
);

