CREATE TABLE [dbo].[TMPFIYATLISTESI] (
    [TANIM]     VARCHAR (2)   NOT NULL,
    [TANIMSLT]  VARCHAR (100) NULL,
    [GRUP]      VARCHAR (3)   NOT NULL,
    [GRUPSLT]   VARCHAR (100) NULL,
    [CODE]      VARCHAR (50)  NOT NULL,
    [NAME1]     VARCHAR (200) NOT NULL,
    [SATISF00]  FLOAT         NULL,
    [KSATISF00] FLOAT         NULL,
    [KATSAY00]  FLOAT         NULL,
    [KKATSAY00] FLOAT         NULL,
    [USER_ID]   VARCHAR (20)  NOT NULL
);

