CREATE TABLE [dbo].[TMPKURUMODEMELISTESI] (
    [FATURAADI]        VARCHAR (50)  NULL,
    [FATURANO]         VARCHAR (50)  NULL,
    [FATURATUTARI]     FLOAT         NULL,
    [FATURATARIHI]     DATETIME      NULL,
    [FATURAVADETARIHI] DATETIME      NULL,
    [VADESURESI]       VARCHAR (50)  NULL,
    [ODEMEDURUMU]      VARCHAR (50)  NULL,
    [KURUMADI]         VARCHAR (250) NULL,
    [USER_ID]          VARCHAR (50)  NULL
);

