

CREATE VIEW dbo.ANAHIZMETALTHIZMET
AS
SELECT ANAH.SLT AS GRUP,ALTH.SLT AS ALTHIZMET,ALTH.SLB AS TANIMGRUP FROM dbo.KEYDAT ANAH
INNER JOIN (SELECT SEC,SLB, SLT,SLX FROM dbo.KEYDAT WHERE SLK = '30') ALTH ON SUBSTRING(ALTH.SLB,0,3)=ANAH.SLB
WHERE     (ANAH.SLK = '01')
--ORDER BY ANAH.SLT





