
CREATE VIEW SAG_NET_SERVIS
AS
SELECT KEYDAT.SLB AS TKODU, KEYDAT.SLT AS TADI,SS.SLYY AS SADI,SS.SLYA AS SKODU,ISNULL(SS.SLYA,'2') AS SEKLE FROM KEYDAT
LEFT OUTER JOIN SAGLIKNET_SERVISLER SS ON  SS.SLK=KEYDAT.SLK AND SS.SLB=KEYDAT.SLB WHERE KEYDAT.SLK='17'

