


CREATE VIEW dbo.tet
AS
SELECT     dbo.BEHAND.KNR, dbo.BEHAND.SNR, dbo.ADRES.HASTAADI, dbo.ADRES.HASTASOYADI, dbo.BEHAND.AMBU, dbo.BEHAND.TAKIPNO, 
                      dbo.BEHAND.SERVIS, dbo.BEHAND.ARZT, dbo.ADRES.SIGORTANO, dbo.ADRES.BAGKARNENO, dbo.ADRES.TCKIMLIKNO, dbo.BEHAND.PSG, 
                      dbo.KURADR.ADI1, dbo.BEHAND.KTOPT
FROM         dbo.ADRES INNER JOIN
                      dbo.BEHAND ON dbo.ADRES.KNR = dbo.BEHAND.KNR INNER JOIN
                      dbo.KURADR ON dbo.BEHAND.PSG = dbo.KURADR.PSG LEFT OUTER JOIN
                      dbo.TET_ANAMNEZ ON dbo.BEHAND.KNR = dbo.TET_ANAMNEZ.KNR AND dbo.BEHAND.SNR = dbo.TET_ANAMNEZ.SNR
WHERE     (dbo.TET_ANAMNEZ.KNR IS NULL) AND (dbo.BEHAND.KTOPT > 0) AND (dbo.BEHAND.TAKIPSEND = '9') AND (dbo.BEHAND.TAKIPNO IS NOT NULL)



