

CREATE PROCEDURE [Arman] 
 @ICD10 varchar(20),
 @Cinsiyet varchar(1)
AS
DECLARE @Sonuc integer

Set @Sonuc = (SELECT     TOP 100 PERCENT COUNT(*) AS Expr1
FROM         ADRES INNER JOIN
                      BEHAND ON ADRES.KNR = BEHAND.KNR INNER JOIN
                      TET_ANAMNEZ_DETAY ON ADRES.KNR = TET_ANAMNEZ_DETAY.KNR
WHERE     (BEHAND.BHDAT BETWEEN CONVERT(DATETIME, '2008-01-01 00:00:00', 102) AND CONVERT(DATETIME, '2008-12-31 00:00:00', 102))  AND 
                      (ADRES.CINSIYETI = @Cinsiyet) AND TET_ANAMNEZ_DETAY.TESHISKODU = 'IC'+ @ICD10)
return @Sonuc

