
CREATE  PROCEDURE [dbo].[faturaIptal] @ID INT ,@KNR VARCHAR(6), @FN VARCHAR(10)
AS
DECLARE @AV_ID INT,@TUT FLOAT 
--, @ID VARCHAR(10) ,@KNR VARCHAR(6), @FN VARCHAR(10)

-- FATURALAR_DETAY DAN SİLİNİYOR
DELETE FROM FATURALAR_DETAY WHERE ID= @ID
DELETE FROM FATURALAR WHERE ID = @ID
-- FATURALAR_DETAY DAN SİLİNİYOR

UPDATE HIZIL set MAKNO=NULL where KNR = @KNR and (MAKNO='' OR MAKNO = 'EF0')update FATURA set ISIPTAL='1' where KNR = @KNR and  FATURANO = @FN


-- CURSOR AVANSLARI IPTAL EDİYOR ----
DECLARE AVANSLAR_cursor CURSOR FOR 
SELECT AV_ID,SUM(TUTAR)TUT FROM AVANSLAR_KULLANILAN 
WHERE FATURANO = @FN
GROUP BY AV_ID

OPEN AVANSLAR_cursor
FETCH NEXT FROM AVANSLAR_cursor 
INTO @AV_ID,@TUT
    
SELECT @AV_ID , @TUT

  WHILE @@FETCH_STATUS = 0 
  BEGIN   
        
       UPDATE AVANSLAR 
        SET KULLANILAN = KULLANILAN - @TUT
        WHERE AV_ID = @AV_ID
 /*       
       UPDATE AVANSLAR 
        SET IADEEDILEN = IADEEDILEN + @TUT
        WHERE AV_ID = @AV_ID
   
        DELETE AVANSLAR_KULLANILAN WHERE AV_ID = @AV_ID
*/
        FETCH NEXT FROM AVANSLAR_cursor
        INTO @AV_ID,@TUT
  END
--SON:
        CLOSE AVANSLAR_CURSOR
      	DEALLOCATE AVANSLAR_cursor 
-- CURSOR AVANSLARI IPTAL EDİYOR ----
