


--CREATE PROCEDURE [dbo].[HESAPTOPLAM] (@HESAP VARCHAR(20))

--AS
--DECLARE @SONUCTABLO TABLE (AY VARCHAR(20),ALACAK FLOAT,BORC FLOAT,AB FLOAT,BB FLOAT)
--DECLARE @DON FLOAT, @A FLOAT ,@B FLOAT ,@AYLAR VARCHAR(20),@AB FLOAT,@BB FLOAT,
--        @A1 FLOAT,@B1 FLOAT,
--        @A2 FLOAT,@B2 FLOAT,
--        @A3 FLOAT,@B3 FLOAT,
--        @A4 FLOAT,@B4 FLOAT,
--        @A5 FLOAT,@B5 FLOAT,
--        @A6 FLOAT,@B6 FLOAT,
--        @A7 FLOAT,@B7 FLOAT,
--        @A8 FLOAT,@B8 FLOAT,
--        @A9 FLOAT,@B9 FLOAT,
--        @A10 FLOAT,@B10 FLOAT,
--        @A11 FLOAT,@B11 FLOAT,
--        @A12 FLOAT,@B12 FLOAT      
         

----declare @OCAK VARCHAR(50), @SUBAT VARCHAR(50)
----DECLARE @SONUC VARCHAR(2000)
--SET @DON = 1
----set @SONUC = ''
--SELECT @B1 = SUM(AY1TOPB), @A1 = SUM(AY1TOPA),
--       @B2 = SUM(AY2TOPB), @A2 = SUM(AY2TOPA),
--       @B3 = SUM(AY3TOPB), @A3 = SUM(AY3TOPA),
--       @B4 = SUM(AY4TOPB), @A4 = SUM(AY4TOPA),
--       @B5 = SUM(AY5TOPB), @A5 = SUM(AY1TOPA),
--       @B6 = SUM(AY6TOPB), @A6 = SUM(AY6TOPA),
--       @B7 = SUM(AY7TOPB), @A7 = SUM(AY7TOPA),
--       @B8 = SUM(AY8TOPB), @A8 = SUM(AY8TOPA),
--       @B9 = SUM(AY9TOPB), @A9 = SUM(AY9TOPA),
--       @B10 = SUM(AY10TOPB), @A10 = SUM(AY10TOPA),
--       @B11 = SUM(AY11TOPB), @A11 = SUM(AY11TOPA),
--       @B12 = SUM(AY12TOPB), @A12 = SUM(AY12TOPA)
--FROM muh_hesap_plani
--WHERE HESAP_KODU LIKE  @HESAP+'%'
----GROUP BY HESAP_KODU

----set @SONUC = @OCAK + ';' +@SUBAT 

----SELECT VALUEAT AS DONEM, DATAVALUE AS TOPLAM FROM DBO.sTRtOtABLE(@SONUC, ';')
----/*
----SET @DON = 1

--WHILE @DON<>13

--BEGIN

-- IF @DON = 1  BEGIN SET @AYLAR='OCAK' SET @A=@A1 SET @B=@B1 END  
-- IF @DON = 2  BEGIN SET @AYLAR='ŞUBAT' SET @A=@A2 SET @B=@B2 END
-- IF @DON = 3  BEGIN SET @AYLAR='MART' SET @A =@A3 SET @B = @B3 END
-- IF @DON = 4  BEGIN SET @AYLAR='NİSAN' SET @A =@A4 SET @B=@B4 END 
-- IF @DON = 5  BEGIN SET @AYLAR='MAYIS' SET @A=@A5 SET @B =@B5 END
-- IF @DON = 6  BEGIN SET @AYLAR='HAZİRAN' SET @A=@A6 SET @B=@B6 END 
-- IF @DON = 7  BEGIN SET @AYLAR='TEMMUZ' SET @A=@A7 SET @B = @B7 END
-- IF @DON = 8  BEGIN SET @AYLAR='AĞUSTOS' SET @A=@A8 SET @B=@B8 END 
-- IF @DON = 9  BEGIN SET @AYLAR='EYLÜL' SET @A=@A9 SET @B=@B9 END
-- IF @DON = 10 BEGIN SET @AYLAR='EKİM' SET @A=@A10 SET @B=@B10 END
-- IF @DON = 11 BEGIN SET @AYLAR='KASIM' SET @A=@A11 SET @B=@B11 END
-- IF @DON = 12 BEGIN SET @AYLAR='ARALIK' SET @A=@A12 SET @B=@B12 END

--SET @BB=0
--SET @AB =0
--IF @B>@A  SET @BB = @B-@A ELSE SET @AB=@A-@B    

-- INSERT INTO @SONUCTABLO (AY,ALACAK,BORC,BB,AB) VALUES (@AYLAR,@A,@B,@BB,@AB)
-- SET  @DON=@DON + 1 
-- SET @A=0
-- SET @B=0

-- IF @DON = 13 BREAK ELSE CONTINUE

--END 

--SELECT * FROM @SONUCTABLO


