


CREATE PROCEDURE [dbo].[HIZILtoDRHIZIL] @T1 VARCHAR(15) , @T2 VARCHAR(15), @D VARCHAR(8000)
AS
--SET @T1 = '20060601'
--SET @T2 = '20060930'
--SET @D = '0003'

INSERT INTO DRHIZIL (KNR,SNR,SIRANO,AKOD,TANIM,GRUP,CODE,ARZT,ARZT2,ADET,UNITE,NAME1,
SATISF,KSATISF,KDV,TARIH,PSG,HZLNO,MAKNO,KFATNO,ISLENDIMI,DATE_CREATE,USER_ID,S_ADET)


SELECT H.KNR,H.SNR,H.SIRANO,H.AKOD,H.TANIM,H.GRUP,H.CODE,H.ARZT,H.ARZT2,H.ADET,H.UNITE,H.NAME1,
H.SATISF,H.KSATISF,H.KDV,H.TARIH,H.PSG,H.HZLNO,H.MAKNO,H.KFATNO,0,H.DATE_CREATE,H.USER_ID,H.ADET
FROM doktor K
INNER join HIZIL H ON H.ARZT2 = K.SLB --AND K.SLB = @D 

WHERE H.TARIH between @T1 and @T2 and H.ISLENDIMI IS NULL 
AND ARZT2 IN  (select datavalue from strtotable(@d,','))

insert into Doktor_HavuzAl 
select datavalue,@t1,@t2,'H'
from (
select datavalue from strtotable(@d,',')
) as t




