

CREATE PROCEDURE [dbo].[KlinikBul] @KODU varchar(5)
AS
SELECT SS.SLYA AS code,SS.SLYY AS displayName FROM KEYDAT
INNER JOIN  (SELECT SLB, SLT, SLYY, SLYA FROM SAGLIKNET_SERVISLER) SS ON SS.SLB=KEYDAT.SLB
WHERE KEYDAT.SLK='17' and SS.SLB=@KODU

