

CREATE   PROCEDURE NX_SP_TEDARIKCILER (
 @ANAHTAR varchar(16)
) AS
   DECLARE @KOSUL varchar(64)

   SELECT @KOSUL=UPPER(@ANAHTAR)
   SELECT @KOSUL=REPLACE(@KOSUL,'İ','I')
   SELECT @KOSUL=REPLACE(@KOSUL,'O','[OÖ]')
   SELECT @KOSUL=REPLACE(@KOSUL,'C','[CÇ]')
   SELECT @KOSUL=REPLACE(@KOSUL,'G','[GĞ]')
   SELECT @KOSUL=REPLACE(@KOSUL,'U','[UÜ]')
   SELECT @KOSUL=REPLACE(@KOSUL,'S','[SŞ]')
   SELECT @KOSUL=REPLACE(@KOSUL,'I','[Iİ]')

   SELECT [KNR] AS [ID], [KNR] AS [KODU], [ADI1] AS [ADI],
       ([ADRZUS]+' '+[STR]+' '+[PLZ]+' '+[ORT]  ) AS [ADRES]
   FROM [SATADR]
   WHERE [ADI1] LIKE @KOSUL+'%'

