
CREATE  PROCEDURE NX_SP_HASTAYA_CIKIS_YAP

	 ( @HAREKET_ID int )

AS

BEGIN TRAN

	DECLARE
		@FHZLNO INT,@FKNR VARCHAR (6),@FSNR VARCHAR (3),@FMALZEME VARCHAR (15),@FMIKTAR FLOAT,@FETIKET_FIYATI FLOAT,
		@FOZEL_INDIRIM FLOAT, @FTOPLAM FLOAT,@FKTOPLAM FLOAT,@FKDV FLOAT,@FSIRANO FLOAT,@FAKOD VARCHAR (2),@FILAC_SARF VARCHAR(1),
		@FTANIM VARCHAR (2),@FGRUP VARCHAR (3),@FNAME1 VARCHAR (35),@FKULLANICI_KODU VARCHAR (50),@FARZT VARCHAR (4),
		@FPSG VARCHAR (10),@FZAMAN VARCHAR(19),@FSERVIS VARCHAR (2), @FHASTAADI_SOYADI VARCHAR(50),@i int,@FINDIRIMI INT,@FINDIRIMS INT,@FKARAKTER_SAYISI INT,@FCIKTAR1 VARCHAR(19),@FAMBU1 VARCHAR(1),@FETIKET_FIYATI3 FLOAT,@FETIKET_FIYATI2 FLOAT

	SELECT @FZAMAN=getdate()

	select @FKNR = (KARANTINA_NO),@FAKOD = (RIGHT(CIKIS_DEPOSU,2)),@FKULLANICI_KODU=(KULLANICI_KODU),@FILAC_SARF=(ILAC_SARF)  from NX_HAREKETLER where HAREKET_ID=@HAREKET_ID
	SELECT @FKARAKTER_SAYISI=LEN(@FKNR)
	
	IF @FKARAKTER_SAYISI=5 
	BEGIN
		SELECT @FKNR='0' + @FKNR
	END

	IF @FKARAKTER_SAYISI=4
	BEGIN
		SELECT @FKNR='00' + @FKNR
	END

	select @FSNR = MIN(SNR) from BEHAND  where KNR=@FKNR
	select @FCIKTAR1 = (CIKTAR) from BEHAND  where KNR=@FKNR AND SNR=@FSNR
	select @FAMBU1 = (AMBU) from BEHAND  where KNR=@FKNR AND SNR=@FSNR	
	
	IF @FCIKTAR1<>NULL AND @FAMBU1='Y'
	BEGIN
		SELECT @FKNR='0'
	END

	select @FPSG = (PSG),@FHASTAADI_SOYADI=(HASTAADI) + (HASTASOYADI)  from ADRES  where KNR=@FKNR
	select @FSIRANO = MAX(SIRANO)+1  from HIZIL  where KNR=@FKNR AND SNR=@FSNR
	
	
	SELECT @FTANIM='09'	
	IF @FILAC_SARF='S'
	BEGIN
		SELECT @FTANIM='16'
	END

	IF @FSIRANO=NULL
	BEGIN
		SELECT @FSIRANO=1
	END
	
	select @FHZLNO = MAX(HZLNO)+1  from BEHAND  where KNR=@FKNR AND SNR=@FSNR
	IF @FHZLNO=NULL
	BEGIN
		SELECT @FHZLNO=1	
	END
	
	select @FINDIRIMI = RIGHT(LEFT((ORAN1),30),3)  from ADRES_KATIL  where  KNR=@FKNR
	select @FINDIRIMS = RIGHT(LEFT((ORAN1),51),3)  from ADRES_KATIL  where  KNR=@FKNR

	IF @FINDIRIMI=NULL
	BEGIN
		SELECT @FINDIRIMI=100
	END

	IF @FINDIRIMS=NULL
	BEGIN
		SELECT @FINDIRIMS=100
	END

	UPDATE BEHAND SET HZLNO=@FHZLNO where KNR=@FKNR and SNR=@FSNR

	IF @@ROWCOUNT=0  goto RLLBCK

	select @FARZT = (ARZT),@FSERVIS=(SERVIS)  from BEHAND_DETAY  where KNR=@FKNR AND SNR=@FSNR ORDER BY DATE_CREATE DESC

	DECLARE kalemler_cursor CURSOR FOR 
        	SELECT MALZEME, MIKTAR, ETIKET_FIYATI ,OZEL_INDIRIM,KDV
        	FROM NX_HAREKET_KALEMLERI 
       	 WHERE HAREKET_ID = @HAREKET_ID 
        	ORDER BY MALZEME 

	OPEN kalemler_cursor
	SELECT @i=0
	FETCH NEXT FROM kalemler_cursor 
	INTO @FMALZEME, @FMIKTAR, @FETIKET_FIYATI,@FOZEL_INDIRIM,@FKDV

	WHILE @@FETCH_STATUS = 0 
	BEGIN   
		SELECT @i=@i+1 

		select @FGRUP = (GRUP),@FNAME1=(NAME1) from ILACSARF where CODE=@FMALZEME AND AKOD=@FAKOD

		UPDATE ILACSARF set TOPCIK = TOPCIK + @FMIKTAR,TOPSAT = TOPSAT + ROUND((@FMIKTAR*@FETIKET_FIYATI),2)WHERE AKOD=@FAKOD and TANIM=@FTANIM  and GRUP=@FGRUP and CODE=@FMALZEME

		IF @@ROWCOUNT=0 goto RLLBCK
			
		SELECT @FETIKET_FIYATI3=0
		select @FETIKET_FIYATI2=@FETIKET_FIYATI

	
				SELECT @FETIKET_FIYATI3=@FETIKET_FIYATI-ROUND(@FETIKET_FIYATI*@FINDIRIMI/100,2)
				SELECT @FETIKET_FIYATI=ROUND(@FETIKET_FIYATI*@FINDIRIMI/100,2)

		INSERT into HIZIL(KNR, SNR, TARIH, AKOD, TANIM, GRUP, CODE, NAME1, KDV, ADET, SATISF, KSATISF, PSG, ARZT, ARZT2, HZLNO, SIRANO, USER_ID, DATE_CREATE) 
		values ( @FKNR,@FSNR,@FZAMAN,@FAKOD,@FTANIM,@FGRUP,@FMALZEME,@FNAME1,@FKDV,@FMIKTAR,ROUND(@FETIKET_FIYATI,2),ROUND(@FETIKET_FIYATI3,2),@FPSG,@FARZT,@FARZT,@FHZLNO,@FSIRANO,@FKULLANICI_KODU,@FZAMAN)	

		IF @@ROWCOUNT=0  goto RLLBCK

		INSERT into SHARK(AKOD, TANIM, GRUP, CODE, TARIH, EVRAKNO, FIRMA, ACIKLAMA, G_C, ADET, BIRIMF, TUTAR, SERVIS, ARZT, USER_ID, DATE_CREATE) 
		values (@FAKOD,@FTANIM,@FGRUP,@FMALZEME,@FZAMAN,@FKNR + @FSNR,'P',@FHASTAADI_SOYADI,'C',@FMIKTAR,ROUND(@FETIKET_FIYATI2,2),ROUND((@FMIKTAR*@FETIKET_FIYATI2),2),@FSERVIS,@FARZT,@FKULLANICI_KODU,@FZAMAN)

		IF @@ROWCOUNT=0 goto RLLBCK

		SELECT @FSIRANO=@FSIRANO + 1

		FETCH NEXT FROM kalemler_cursor 
   		INTO @FMALZEME, @FMIKTAR, @FETIKET_FIYATI,@FOZEL_INDIRIM,@FKDV
	END 

	CLOSE kalemler_cursor 
	DEALLOCATE kalemler_cursor 

	select @FTOPLAM=sum(ROUND(ADET * SATISF,2)), @FKTOPLAM=sum(ROUND(ADET * KSATISF,2))  from HIZIL where KNR=@FKNR and SNR=@FSNR

	update BEHAND set MTOPT=@FTOPLAM, KTOPT=@FKTOPLAM where KNR=@FKNR and SNR=@FSNR

	IF @@ROWCOUNT=0  goto RLLBCK

	UPDATE NX_HAREKETLER SET DURUM='A' /*AKTARILDI*/ WHERE HAREKET_ID=@HAREKET_ID

	IF @@ROWCOUNT=0 goto RLLBCK

	COMMIT TRAN
	RETURN 1 /* 1=BAŞARILI, 0=BAŞARISIZ */

RLLBCK:
	ROLLBACK TRAN
