










CREATE     PROCEDURE NX_SP_ILACSARF_DEPOLAR ( 
@AKOD varchar(2),
@KOD varchar(15)
) AS
	SELECT [NAME1] AS [ADI],  [GRUP], [TANIM] /*'09' ilaç, '16' SARF*/ ,
		[CODE] AS [KOD],  [CODE] AS [BARKOD],  ([TOPGIR]-[TOPCIK]+[DEVIR]) AS [MIKTAR],
		((CASE TANIM WHEN '09' THEN '03' WHEN '16' THEN '04' ELSE '--' END)+[AKOD]) AS [DEPO_ID], 
        [FIRMA] AS [URETICI], [FIRMA] AS [TEDARIKCI],
        [SATISF] AS [SATIS_FIYATI], [ALISF] AS [ALIS_FIYATI]
	FROM [ILACSARF] WHERE [CODE]=@KOD AND (@AKOD='*' OR AKOD=@AKOD)
    ORDER BY [AKOD]


