




CREATE  PROCEDURE NX_SP_SAYIM_AKTAR
	(
		@HAREKET_ID int
	)
AS
	DECLARE @AKOD varchar(2)
	DECLARE @KULLANICI_KODU varchar(20)
	DECLARE @TANIM varchar(2)

	SELECT @AKOD=RIGHT(H.GIRIS_DEPOSU,2), 
		 @KULLANICI_KODU=H.KULLANICI_KODU, 
		 @TANIM=(CASE H.ILAC_SARF WHEN 'I' THEN '09' WHEN 'S' THEN '16' END)
	FROM NX_HAREKETLER H 
	WHERE HAREKET_ID=@HAREKET_ID

	BEGIN TRAN
		DELETE FROM TMPECZSAYIMLISTESI 
		WHERE [USER_ID]=@KULLANICI_KODU AND TANIM=@TANIM
			 AND AKOD=@AKOD AND CODE IN (SELECT MALZEME FROM NX_HAREKET_KALEMLERI WHERE HAREKET_ID=@HAREKET_ID)
	
		INSERT INTO TMPECZSAYIMLISTESI 
		(AKOD,TANIM,GRUP,CODE,NAME1,SAYIM,MEVCUT,FAZLA,EKSIK,FIRMA,[USER_ID])
		SELECT @AKOD,@TANIM,
			M.GRUP,HK.MALZEME, M.NAME1, HK.MIKTAR, (M.TOPGIR-M.TOPCIK+M.DEVIR) AS MEVCUT,
			(CASE WHEN (M.TOPGIR-M.TOPCIK+M.DEVIR)<HK.MIKTAR THEN HK.MIKTAR-(M.TOPGIR-M.TOPCIK+M.DEVIR) ELSE 0  END) AS FAZLA, 
			(CASE WHEN (M.TOPGIR-M.TOPCIK+M.DEVIR)>HK.MIKTAR THEN (M.TOPGIR-M.TOPCIK+M.DEVIR)-HK.MIKTAR ELSE 0 END) AS EKSIK,
			M.FIRMA, @KULLANICI_KODU
		FROM NX_HAREKET_KALEMLERI HK LEFT OUTER JOIN ILACSARF M
			ON HK.MALZEME=M.CODE AND M.TANIM=@TANIM AND M.AKOD=@AKOD
		WHERE HK.HAREKET_ID=@HAREKET_ID

		IF @@ROWCOUNT=0 OR @@ERROR<>0 goto RLLBCK

		UPDATE NX_HAREKETLER SET DURUM='A' /*AKTARILDI*/ WHERE HAREKET_ID=@HAREKET_ID
		IF @@ROWCOUNT=0 OR @@ERROR<>0 goto RLLBCK

	COMMIT TRAN
	RETURN 1 /* 1=BAŞARILI, 0=BAŞARISIZ */

RLLBCK:
	ROLLBACK TRAN
	RETURN 0


