

CREATE PROCEDURE NX_SP_HASTA_YATIS_BILGISI
(
   @KARANTINA_NO varchar(7)
)
AS
 SELECT TOP 1 A.[KNR] AS [ID], A.[KNR] AS [KODU], (A.[HASTAADI]+' '+A.[HASTASOYADI]) AS [ADI] ,
    B.[BHDAT] AS [GIRIS_TARIHI] FROM [BEHAND] B LEFT OUTER JOIN             
     [ADRES] A ON A.[KNR]=B.[KNR]
   WHERE  A.[KNR]=@KARANTINA_NO
  ORDER BY B.[SNR]

