
CREATE PROCEDURE NX_SP_VARSAYILAN_GIRIS_DEPOSU 
(
	@ILAC_SARF varchar(2),
	@VARSAYILAN_DEPO varchar(4) out
)
AS
	SELECT @VARSAYILAN_DEPO='0000'
	IF @ILAC_SARF='09'
	BEGIN
		SELECT @VARSAYILAN_DEPO='03'+SLT
		FROM         KEYDAT
		WHERE     (SLK = '00') AND (SLB = 'ILANAAMBAR')
	END ELSE IF @ILAC_SARF='16'
		BEGIN
			SELECT @VARSAYILAN_DEPO='04'+SLT
			FROM         KEYDAT
			WHERE     (SLK = '00') AND (SLB = 'SFANAAMBAR')
		END

	RETURN 1
