

CREATE  PROCEDURE NX_SP_TOPLU_TRANSFER
      ( @HAREKET_ID int ) 
AS
	BEGIN TRAN

	DECLARE
		@FMALZEME VARCHAR (15),@FMIKTAR FLOAT,@FETIKET_FIYATI FLOAT,@FOZEL_INDIRIM FLOAT,@FKDV FLOAT,@FILAC_SARF VARCHAR(1),
		@FTANIM VARCHAR (2),@FGRUP VARCHAR (3),@FNAME1 VARCHAR (35),@FNAME2 VARCHAR (35),@FKULLANICI_KODU VARCHAR (50),@FZAMAN VARCHAR(19),
		@FBELGE_NO VARCHAR(15),@FAKODC VARCHAR(2),@FAKODG VARCHAR(3),@FALISF FLOAT,@FSATISF FLOAT,@FTEST VARCHAR(3),
		@FUNITE VARCHAR(30),@FFIRMA VARCHAR(30),@FJEN_KOD VARCHAR(30),@FVERADET FLOAT,@FFAR_KOD VARCHAR(30),@i int,@FHAR_TIPI VARCHAR(2),@FACIKLAMA VARCHAR(30)

	SELECT @FZAMAN=getdate()

	select @FBELGE_NO=(BELGE_NO),@FAKODC = RIGHT((CIKIS_DEPOSU),2),@FAKODG = (GIRIS_DEPOSU),@FKULLANICI_KODU=(KULLANICI_KODU),
	@FILAC_SARF=(ILAC_SARF),@FHAR_TIPI=(HAREKET_TIPI)  from NX_HAREKETLER where HAREKET_ID=@HAREKET_ID


	select @FACIKLAMA = (SLT)   from KEYDAT where SLK='08' AND SLB=@FAKODG

	DECLARE kalemler_cursor CURSOR FOR 
        	SELECT MALZEME, MIKTAR, ETIKET_FIYATI ,OZEL_INDIRIM,KDV
        	FROM NX_HAREKET_KALEMLERI 
       	WHERE HAREKET_ID = @HAREKET_ID 
       	ORDER BY MALZEME 

	OPEN kalemler_cursor
	SELECT @i=0
	FETCH NEXT FROM kalemler_cursor 
	INTO @FMALZEME, @FMIKTAR, @FETIKET_FIYATI,@FOZEL_INDIRIM,@FKDV

	WHILE @@FETCH_STATUS = 0 
	BEGIN   
		SELECT @i=@i+1 

	IF @FHAR_TIPI='TG'
	BEGIN
		select @FALISF=(ALISF),@FSATISF=(SATISF),@FTANIM=(TANIM),@FGRUP=(GRUP),@FJEN_KOD=(JEN_KOD),@FFIRMA=(FIRMA),@FUNITE=(UNITE),
		@FVERADET=(VERADET),@FNAME1=(NAME1),@FNAME2=(NAME2),@FALISF = (ALISF),@FTANIM=(TANIM),@FGRUP=(GRUP),@FFAR_KOD=(FAR_KOD)
	 	from ILACSARF where CODE=@FMALZEME AND AKOD=@FAKODG

		UPDATE ILACSARF set TOPGIR = TOPGIR + @FMIKTAR*@FVERADET, TOPALS = TOPALS + ROUND((@FMIKTAR*@FALISF*@FVERADET),2), ALISF = @FALISF, SATISF = @FSATISF
		WHERE CODE=@FMALZEME AND AKOD=@FAKODG

		IF @@ROWCOUNT=0  goto RLLBCK

		INSERT into SHARK(AKOD, TANIM, GRUP, CODE, TARIH, EVRAKNO, FIRMA, ACIKLAMA, G_C, ADET, BIRIMF, TUTAR, USER_ID, DATE_CREATE) 
		values ( @FAKODG,@FTANIM,@FGRUP,@FMALZEME,@FZAMAN,@FBELGE_NO,'T', @FACIKLAMA,'G',@FMIKTAR*@FVERADET,@FALISF,
		ROUND((@FMIKTAR*@FALISF*@FVERADET),2),@FKULLANICI_KODU,@FZAMAN)

		IF @@ROWCOUNT=0  goto RLLBCK
		

	END


	IF @FHAR_TIPI='TC'
	BEGIN

		select @FALISF=(ALISF),@FSATISF=(SATISF),@FTANIM=(TANIM),@FGRUP=(GRUP),@FJEN_KOD=(JEN_KOD),@FFIRMA=(FIRMA),@FUNITE=(UNITE),
		@FVERADET=(VERADET),@FNAME1=(NAME1),@FNAME2=(NAME2),@FALISF = (ALISF),@FTANIM=(TANIM),@FGRUP=(GRUP),@FFAR_KOD=(FAR_KOD)
	 	from ILACSARF where CODE=@FMALZEME AND AKOD=@FAKODC

		UPDATE ILACSARF set TOPCIK = TOPCIK + @FMIKTAR,TOPSAT = TOPSAT + ROUND((@FMIKTAR*@FALISF),2) WHERE CODE=@FMALZEME AND AKOD=@FAKODC

		IF @@ROWCOUNT=0 goto RLLBCK

		INSERT into SHARK(AKOD, TANIM, GRUP, CODE, TARIH, EVRAKNO, FIRMA, ACIKLAMA, G_C, ADET, BIRIMF, TUTAR, USER_ID, DATE_CREATE) 
		values (@FAKODC,@FTANIM,@FGRUP,@FMALZEME,@FZAMAN,@FBELGE_NO,'T',@FACIKLAMA,'C',@FMIKTAR,@FALISF,
		ROUND((@FMIKTAR*@FALISF),2),@FKULLANICI_KODU,@FZAMAN)

		IF @@ROWCOUNT=0  goto RLLBCK
	END

		FETCH NEXT FROM kalemler_cursor 
   		INTO @FMALZEME, @FMIKTAR, @FETIKET_FIYATI,@FOZEL_INDIRIM,@FKDV
	END 

	CLOSE kalemler_cursor 
	DEALLOCATE kalemler_cursor 

	UPDATE NX_HAREKETLER SET DURUM='A' /*AKTARILDI*/ WHERE HAREKET_ID=@HAREKET_ID
	IF @@ROWCOUNT=0 goto RLLBCK

	COMMIT TRAN
	RETURN 1 /* 1=BAŞARILI, 0=BAŞARISIZ */

RLLBCK:
	ROLLBACK TRAN
