


CREATE      PROCEDURE NX_SP_DEPOLAR
  ( @KULLANICI_KODU varchar(20),
    @TANIM_KODU varchar(2) -- '04' sarf depoları, '03' ilaç depoları
  )
 AS
    DECLARE @NESNE_ADI varchar(32) -- 'ILAC', 'SARF'
    SELECT @NESNE_ADI=(CASE @TANIM_KODU WHEN '03' THEN 'ILAC' WHEN '04' THEN 'SARF' ELSE '' END)

	IF @KULLANICI_KODU<>'*' 
	BEGIN
	 	SELECT (T.SLK+T.SLB)/*DEPO KODU*/ AS [ID], T.SLT AS ADI FROM KULLANICI_YETKI Y 
	            LEFT OUTER JOIN  KEYDAT T ON cast(T.SLB as int)=Y.TABNUMBER/*AKOD*/
		WHERE T.SLK=@TANIM_KODU AND Y.[OBJECTNAME]=@NESNE_ADI
			AND Y.FORMNAME='DIGER' AND Y.[USER_ID]=@KULLANICI_KODU
	END ELSE BEGIN
		SELECT (T.SLK+T.SLB)/*DEPO KODU*/ AS [ID], T.SLT AS ADI FROM  KEYDAT T 
		WHERE T.SLK=@TANIM_KODU
		END


