

CREATE  PROCEDURE NX_SP_GIRIS_YAP
       ( @HAREKET_ID int )
AS
	
	BEGIN TRAN

DECLARE @FZAMAN varchar(19),@FSNR VARCHAR(3),@FKNR VARCHAR(10),@FFAT_NO VARCHAR(15),@FIRS_NO VARCHAR(15),@FFAT_TARIHI DATETIME,
@FIRS_TARIHI DATETIME,@FGIRIS_DEPOSU VARCHAR(2),@FKULLANICI_KODU VARCHAR(15),@FILAC_SARF VARCHAR(1),@FOZEL_INDIRIM FLOAT,@FTOPLAM FLOAT,
@FKDV_TUTARI FLOAT,@i int,@FMALZEME VARCHAR(35),@FMIKTAR FLOAT,@FETIKET_FIYATI FLOAT,@FKDV FLOAT,@FECZACI_KARI FLOAT,@FTOPLAM_IND FLOAT,
@FMAL_FAZLASI FLOAT,@FMIADI DATETIME,@FAKOD VARCHAR(2),@FTANIM VARCHAR(2),@FGRUP VARCHAR(3),@FNAME1 VARCHAR(35),@FADI1 VARCHAR(50)

	SELECT @FZAMAN=getdate()

SELECT @FFAT_NO=(FAT_NO),@FIRS_NO=(IRS_NO),@FFAT_TARIHI=(FAT_TARIHI),@FIRS_TARIHI=(IRS_TARIHI),
@FGIRIS_DEPOSU=RIGHT((GIRIS_DEPOSU),2),@FKNR=(TEDARIKCI),@FKULLANICI_KODU=(KULLANICI_KODU),
@FILAC_SARF=(ILAC_SARF) FROM NX_HAREKETLER WHERE HAREKET_ID=@HAREKET_ID

SELECT @FSNR=MIN(SNR)-1 FROM SATBEH WHERE KNR=@FKNR

SELECT @FADI1=(ADI1) FROM SATADR WHERE KNR=@FKNR

IF @FSNR=NULL
BEGIN
	SELECT @FSNR='999'
END

IF LEN(@FSNR)=2
BEGIN
	SELECT @FSNR='0' + @FSNR
END

IF LEN(@FSNR)=1
BEGIN
	SELECT @FSNR='00' + @FSNR
END

SELECT @FKDV_TUTARI=SUM(ROUND((ROUND((MIKTAR*ETIKET_FIYATI*(1-OZEL_INDIRIM/100)),2)*KDV/100),2)),@FTOPLAM=SUM(ROUND((MIKTAR*ETIKET_FIYATI),2)),
 @FTOPLAM_IND=SUM(ROUND((MIKTAR*ETIKET_FIYATI*OZEL_INDIRIM/100),2))
 FROM NX_HAREKET_KALEMLERI WHERE HAREKET_ID=@HAREKET_ID

insert into SATBEH (KNR, SNR, IRSALIYETARIHI, IRSALIYENO, FATURATARIHI, FATURANO, ISKONTO, ISKONTO1,
TOPLAM, YUVARLAMA,KDVTUTARI, KDVYUVARLAMA, GENELTOPLAM, ILACSARF, TESELLUMTARIHI, TESELLUMNO, USER_ID, DATE_CREATE) 
values (@FKNR, @FSNR,@FIRS_TARIHI,@FIRS_NO,@FFAT_TARIHI, @FFAT_NO,@FTOPLAM_IND, 0, @FTOPLAM- @FTOPLAM_IND, 0, @FKDV_TUTARI, 0, 
@FTOPLAM- @FTOPLAM_IND+@FKDV_TUTARI, @FILAC_SARF,@FFAT_TARIHI, '', @FKULLANICI_KODU,@FZAMAN)

	IF @@ROWCOUNT=0 goto RLLBCK

	DECLARE kalemler_cursor CURSOR FOR 
        	SELECT MALZEME, MIKTAR, ETIKET_FIYATI ,ECZACI_KARI,MAL_FAZLASI,MIADI,OZEL_INDIRIM,KDV
        	FROM NX_HAREKET_KALEMLERI 
       	WHERE HAREKET_ID = @HAREKET_ID 
       	ORDER BY MALZEME 

	OPEN kalemler_cursor
	SELECT @i=0

	FETCH NEXT FROM kalemler_cursor 
	INTO @FMALZEME, @FMIKTAR, @FETIKET_FIYATI,@FECZACI_KARI,@FMAL_FAZLASI,@FMIADI,@FOZEL_INDIRIM,@FKDV

	WHILE @@FETCH_STATUS = 0 
	BEGIN   
		SELECT @i=@i+1 


SELECT  @FTANIM=(TANIM),@FGRUP=(GRUP),@FNAME1=(NAME1) FROM ILACSARF WHERE CODE=@FMALZEME AND AKOD=@FGIRIS_DEPOSU

insert into SATHIZ (KNR, SNR, AKOD, TANIM, GRUP, CODE, NAME1, ADET, BIRIMF, TOPLAMF, ECZKARO, OZISKO, ISKONTO, KDVO, KDVT,
ALISF, ORJTUTAR, FZMAL, OZELF, MIAD, USER_ID, DATE_CREATE) 
values (@FKNR,@FSNR, @FGIRIS_DEPOSU, @FTANIM,@FGRUP,@FMALZEME,@FNAME1, @FMIKTAR, @FETIKET_FIYATI-@FETIKET_FIYATI*@FOZEL_INDIRIM/100,
((@FETIKET_FIYATI-@FETIKET_FIYATI*@FOZEL_INDIRIM/100)*@FMIKTAR), 0,@FOZEL_INDIRIM, @FETIKET_FIYATI*@FOZEL_INDIRIM/100*@FMIKTAR, @FKDV,
ROUND((ROUND((@FMIKTAR*@FETIKET_FIYATI*(1-@FOZEL_INDIRIM/100)),2)*@FKDV/100),2), @FETIKET_FIYATI, ROUND((@FETIKET_FIYATI*@FMIKTAR),2), 
@FMAL_FAZLASI, 'F', @FMIADI, @FKULLANICI_KODU,@FZAMAN)

	IF @@ROWCOUNT=0 goto RLLBCK

update ILACSARF set TOPGIR = TOPGIR + @FMIKTAR, TOPALS = TOPALS +ROUND((ROUND((@FMIKTAR*@FETIKET_FIYATI*(1-@FOZEL_INDIRIM/100)),2)*(1+@FKDV/100)),2), SEVKDAT =@FFAT_TARIHI, ALISF = @FETIKET_FIYATI, OZELF = 'F'
 where AKOD=@FGIRIS_DEPOSU and TANIM=@FTANIM and GRUP=@FGRUP and CODE=@FMALZEME

	IF @@ROWCOUNT=0 goto RLLBCK

INSERT into SHARK ( AKOD, TANIM, GRUP, CODE, TARIH, FIRMA, EVRAKNO, ACIKLAMA, G_C, ADET, BIRIMF, TUTAR, USER_ID, DATE_CREATE)
 values (@FGIRIS_DEPOSU,@FTANIM,@FGRUP,@FMALZEME,@FZAMAN,'S',@FFAT_NO,@FADI1,'G',@FMIKTAR,@FETIKET_FIYATI,ROUND((@FETIKET_FIYATI*@FMIKTAR),2),@FKULLANICI_KODU,@FZAMAN)

	IF @@ROWCOUNT=0 goto RLLBCK

		FETCH NEXT FROM kalemler_cursor 
   		INTO @FMALZEME, @FMIKTAR, @FETIKET_FIYATI,@FECZACI_KARI,@FMAL_FAZLASI,@FMIADI,@FOZEL_INDIRIM,@FKDV
	END 

	CLOSE kalemler_cursor 
	DEALLOCATE kalemler_cursor 

update SATBEH set ISLENDI='T', FATURATARIHI=@FFAT_TARIHI where KNR=@FKNR and SNR=@FSNR

	IF @@ROWCOUNT=0 goto RLLBCK

insert into SATCARI (KNR, SNR, TARIH, EVRAKNO, ACIKLAMA, B_A, TUTAR, KOD, USER_ID, DATE_CREATE) 
values (@FKNR,@FSNR, @FFAT_TARIHI,@FFAT_NO, 'FATURALI MAL ALIŞI', 'A', (@FTOPLAM-@FTOPLAM_IND+@FKDV_TUTARI), 'F', @FKULLANICI_KODU,@FZAMAN)

	IF @@ROWCOUNT=0 goto RLLBCK

update SATADR set ALACAK=ALACAK+(@FTOPLAM-@FTOPLAM_IND+@FKDV_TUTARI) where KNR=@FKNR

	IF @@ROWCOUNT=0 goto RLLBCK

	UPDATE NX_HAREKETLER SET DURUM='A' /*AKTARILDI*/ WHERE HAREKET_ID=@HAREKET_ID

	IF @@ROWCOUNT=0 goto RLLBCK

	COMMIT TRAN
	RETURN 1 /* 1=BAŞARILI, 0=BAŞARISIZ */

RLLBCK:
	ROLLBACK TRAN
