


CREATE    PROCEDURE NX_SP_HAREKET_KALEM_GUNCELLE
	(
		@HAREKET_ID int,
		@MALZEME varchar(15),
		@MIKTAR float,		
       		@ETIKET_FIYATI float,
		@ECZACI_KARI float,
		@MAL_FAZLASI float,
		@MIADI datetime,
		@OZEL_INDIRIM float,
		@KDV float
	)
AS
	/* SET NOCOUNT ON */
	IF @MIKTAR<>0
	BEGIN 
	  UPDATE NX_HAREKET_KALEMLERI SET 
		MIKTAR=@MIKTAR, 
		ETIKET_FIYATI=@ETIKET_FIYATI,
		ECZACI_KARI=@ECZACI_KARI,
		MAL_FAZLASI=@MAL_FAZLASI,
		MIADI=@MIADI,
		OZEL_INDIRIM=@OZEL_INDIRIM,
		KDV=@KDV
	 WHERE HAREKET_ID=@HAREKET_ID AND MALZEME=@MALZEME 
	  IF @@ROWCOUNT=0 
      BEGIN
        INSERT INTO NX_HAREKET_KALEMLERI 
             (HAREKET_ID,MALZEME,MIKTAR,ETIKET_FIYATI,ECZACI_KARI,MAL_FAZLASI,MIADI,OZEL_INDIRIM,KDV) 
        VALUES 
            (@HAREKET_ID,@MALZEME,@MIKTAR,@ETIKET_FIYATI,@ECZACI_KARI,@MAL_FAZLASI,@MIADI,@OZEL_INDIRIM,@KDV)
        RETURN @@ROWCOUNT        
      END 
  END
    ELSE
  DELETE FROM NX_HAREKET_KALEMLERI WHERE HAREKET_ID=@HAREKET_ID AND MALZEME=@MALZEME

	RETURN 1


