


CREATE PROCEDURE [dbo].[SAGLIKNET_DISGONDER] @ILKTAR VARCHAR(10),@SONTAR VARCHAR(10),@GELGIT VARCHAR(1),@KNRSEC VARCHAR(10)
AS
IF @GELGIT=0  BEGIN 
SELECT     HIZIL.KNR, HIZIL.SNR, HIZILGONSAGNET.GUID AS SAGLIKNET_TAKIPID, HIZIL.SIRANO, HIZMET.BKODU, HIZIL.TARIH AS GELISTAR, ADRES.CINSIYETI, ADRES.HASTAADI, 
                      ADRES.HASTASOYADI, ADRES.DOGUMTARIHI, ADRES.UYRUGU, ADRES.TCKIMLIKNO, BEHAND.PROTOKOLNO, BEHAND.TAKIPNO, 
                      BEHAND.TAKIPSEND,HIZIL.TARIH as CIKTAR,KEYDAT.SLVV AS DRTESCIL, KEYDAT.SLXA AS DRTC, HIZIL.NAME1, ADRES.BAGKARNENO AS KARNENO, 
                      ADRES.PSG AS HASTAKURUM, HIZILGONSAGNET.GELENCEVAP
FROM         HIZIL INNER JOIN
                          (SELECT     KNR, SNR, PROTOKOLNO, TAKIPNO, TAKIPSEND  FROM BEHAND AS BEHAND_1) AS BEHAND ON HIZIL.KNR = BEHAND.KNR AND HIZIL.SNR = BEHAND.SNR INNER JOIN
                          (SELECT     KNR, CINSIYETI, HASTAADI, HASTASOYADI, DOGUMTARIHI, UYRUGU, TCKIMLIKNO, BAGKARNENO, PSG
                            FROM          ADRES AS ADRES_1) AS ADRES ON HIZIL.KNR = ADRES.KNR 
INNER JOIN
                          (SELECT     SLB, SLVV, SLXA
                            FROM          KEYDAT AS KEYDAT_1
                            WHERE      (SLK = '07')) AS KEYDAT ON HIZIL.ARZT2 = KEYDAT.SLB INNER JOIN
                          (SELECT     BKODU, TANIM, GRUP, CODE
                            FROM          HIZMET AS HIZMET_1) AS HIZMET ON HIZIL.TANIM = HIZMET.TANIM AND HIZIL.GRUP = HIZMET.GRUP AND 
                      HIZIL.CODE = HIZMET.CODE LEFT OUTER JOIN
                          (SELECT     KNR, SNR, SIRANO, GUID, GELENCEVAP
                            FROM          HIZILGONSAGNET AS HIZILGONSAGNET_1) AS HIZILGONSAGNET ON HIZIL.KNR = HIZILGONSAGNET.KNR AND 
                      HIZIL.SNR = HIZILGONSAGNET.SNR AND HIZIL.SIRANO = HIZILGONSAGNET.SIRANO
WHERE  (isnumeric(SUBSTRING(HIZIL.NAME1, 2, 2)) = 1) AND (HIZMET.BKODU NOT IN ('401050','406020','405080','405430','404140','404090')) AND (HIZILGONSAGNET.GELENCEVAP <> 'CA' OR
                      HIZILGONSAGNET.GELENCEVAP IS NULL) AND CONVERT(VARCHAR,HIZIL.TARIH,112) BETWEEN @ILKTAR AND @SONTAR
END
IF @GELGIT=1  BEGIN 
SELECT  HIZIL.KNR, HIZIL.SNR, HIZIL.TARIH AS GELISTAR, ADRES.CINSIYETI, ADRES.HASTAADI, ADRES.HASTASOYADI, ADRES.DOGUMTARIHI, 
                      ADRES.UYRUGU, ADRES.TCKIMLIKNO, BEHAND.PROTOKOLNO, BEHAND.TAKIPNO, BEHAND.TAKIPSEND, KEYDAT.SLVV AS DRTESCIL, 
                      KEYDAT.SLXA AS DRTC, HIZIL.NAME1, ADRES.BAGKARNENO AS KARNENO, ADRES.PSG AS HASTAKURUM, HIZMET.BKODU, BEHAND.CIKTAR, 
                      HIZILGONSAGNET.GELENCEVAP
FROM         HIZIL INNER JOIN
                      BEHAND ON HIZIL.KNR = BEHAND.KNR AND HIZIL.SNR = BEHAND.SNR INNER JOIN
                      ADRES ON HIZIL.KNR = ADRES.KNR AND BEHAND.CIKTAR IS NOT NULL INNER JOIN
                          (SELECT     SLB, SLVV, SLXA
                            FROM          KEYDAT AS KEYDAT_1
                            WHERE      (SLK = '07')) AS KEYDAT ON HIZIL.ARZT2 = KEYDAT.SLB INNER JOIN
                      HIZMET ON HIZIL.TANIM = HIZMET.TANIM AND HIZIL.GRUP = HIZMET.GRUP AND HIZIL.CODE = HIZMET.CODE LEFT OUTER JOIN
                      HIZILGONSAGNET ON HIZIL.KNR = HIZILGONSAGNET.KNR AND HIZIL.SNR = HIZILGONSAGNET.SNR
WHERE     (dbo.HIZIL.TANIM = '02') AND (LEN(dbo.ADRES.BAGKARNENO) > 1)
AND CONVERT(VARCHAR,BEHAND.BHDAT,112) BETWEEN @ILKTAR AND @SONTAR
--AND (HIZILGONSAGNET.GELENCEVAP = 'CA')
END
IF @GELGIT=2  BEGIN 
SELECT HIZIL.KNR, HIZIL.SNR, HIZIL.TARIH AS GELISTAR, ADRES.CINSIYETI, ADRES.HASTAADI, 
                      ADRES.HASTASOYADI, ADRES.DOGUMTARIHI, ADRES.UYRUGU, ADRES.TCKIMLIKNO, BEHAND.PROTOKOLNO, BEHAND.TAKIPNO, 
                      BEHAND.TAKIPSEND, KEYDAT.SLVV AS DRTESCIL, KEYDAT.SLXA AS DRTC, HIZIL.NAME1, ADRES.BAGKARNENO AS KARNENO, 
                      ADRES.PSG AS HASTAKURUM, HIZMET.BKODU, BEHAND.CIKTAR, HIZILGONSAGNET.GELENCEVAP, DISKODLARI.kodu AS DISKODU, DISKODLARI.adi AS DISADI,SUBSTRING(HIZIL.NAME1, 2, 2) AS DIS
FROM         HIZIL INNER JOIN
                      BEHAND ON HIZIL.KNR = BEHAND.KNR AND HIZIL.SNR = BEHAND.SNR INNER JOIN
                      ADRES ON HIZIL.KNR = ADRES.KNR AND BEHAND.CIKTAR IS NOT NULL INNER JOIN
                          (SELECT     SLB, SLVV, SLXA
                            FROM          KEYDAT AS KEYDAT_1
                            WHERE      (SLK = '07')) AS KEYDAT ON HIZIL.ARZT2 = KEYDAT.SLB INNER JOIN
                      HIZMET ON HIZIL.TANIM = HIZMET.TANIM AND HIZIL.GRUP = HIZMET.GRUP AND HIZIL.CODE = HIZMET.CODE INNER JOIN
                      DISKODLARI ON SUBSTRING(HIZIL.NAME1, 2, 2) = DISKODLARI.tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS 
INNER JOIN  HIZILGONSAGNET ON HIZIL.KNR = HIZILGONSAGNET.KNR --AND HIZIL.SNR = HIZILGONSAGNET.SNR
WHERE     (HIZIL.TANIM = '02') AND (LEN(ADRES.BAGKARNENO) > 1) AND (CONVERT(VARCHAR, BEHAND.BHDAT, 112) BETWEEN @ILKTAR AND @SONTAR) AND
 HIZILGONSAGNET.GELENCEVAP='CA'  AND HIZIL.KNR=@KNRSEC
AND HIZILGONSAGNET.SCODE='AE:OK' --AND (isnumeric(SUBSTRING(HIZIL.NAME1, 2, 2)) = 1)
END





