

CREATE PROCEDURE [dbo].[SAGLIKNET_MUDAHELE] @KNR VARCHAR(6),@SNR VARCHAR(3)
AS
--DECLARE @KNR VARCHAR(6),@SNR VARCHAR(3)
--SET @KNR='014044'
--SET @SNR='999'
SELECT HT.BKODU,HT.NAME1 FROM HIZIL HL
INNER JOIN (SELECT TANIM,GRUP,CODE,BKODU,NAME1 FROM HIZMET) HT ON HT.TANIM=HL.TANIM AND HT.GRUP=HL.GRUP AND HT.CODE=HL.CODE
INNER JOIN (SELECT DISTINCT KODU FROM MUDAHALELER  GROUP BY KODU) MDH ON MDH.KODU=HT.BKODU
INNER JOIN (SELECT * FROM KEYDAT WHERE (SLK='01') AND (SLX IN ('0','11'))) KEYDAT  ON KEYDAT.SLB=HL.TANIM
WHERE KNR=@KNR AND SNR=@SNR


