CREATE PROCEDURE [dbo].[SAGLIKNETDURUM] @ILKTAR VARCHAR(10),@SONTAR VARCHAR(10)
AS
SELECT HIZILGONSAGNET.TUR,COUNT(*) AS TOPLAM ,'GONDERILEN' AS DURUM FROM BEHAND 
INNER JOIN HIZILGONSAGNET ON BEHAND.KNR = HIZILGONSAGNET.KNR AND BEHAND.SNR = HIZILGONSAGNET.SNR
WHERE     (HIZILGONSAGNET.SCODE = 'AA:OK') AND (CONVERT(VARCHAR, BEHAND.BHDAT, 112) BETWEEN @ILKTAR AND @SONTAR) 
GROUP BY HIZILGONSAGNET.TUR
UNION ALL
SELECT HIZILGONSAGNET.TUR,COUNT(*) AS TOPLAM,'GONDERILMEYEN' AS DURUM FROM BEHAND 
LEFT OUTER JOIN  HIZILGONSAGNET ON BEHAND.KNR = HIZILGONSAGNET.KNR AND BEHAND.SNR = HIZILGONSAGNET.SNR
WHERE     (HIZILGONSAGNET.SCODE IS NULL) AND (CONVERT(VARCHAR, BEHAND.BHDAT, 112) BETWEEN @ILKTAR AND @SONTAR) 
GROUP BY HIZILGONSAGNET.TUR
UNION ALL
SELECT HIZILGONSAGNET.TUR,COUNT(*) AS TOPLAM ,'HATALI' AS DURUM FROM BEHAND 
INNER JOIN HIZILGONSAGNET ON BEHAND.KNR = HIZILGONSAGNET.KNR AND BEHAND.SNR = HIZILGONSAGNET.SNR
WHERE     (HIZILGONSAGNET.SCODE = 'AE:OK') AND (CONVERT(VARCHAR, BEHAND.BHDAT, 112) BETWEEN @ILKTAR AND @SONTAR) 
GROUP BY HIZILGONSAGNET.TUR
UNION ALL
SELECT HIZILGONSAGNET.TUR,COUNT(*) AS TOPLAM,'TOPLAM KAYIT' AS DURUM FROM BEHAND 
LEFT OUTER JOIN  HIZILGONSAGNET ON BEHAND.KNR = HIZILGONSAGNET.KNR AND BEHAND.SNR = HIZILGONSAGNET.SNR
WHERE (CONVERT(VARCHAR, BEHAND.BHDAT, 112) BETWEEN @ILKTAR AND @SONTAR) 
GROUP BY HIZILGONSAGNET.TUR


