

CREATE PROCEDURE [dbo].[SAGLIKNET_DISSAYISI] @KNR VARCHAR(6),@SNR VARCHAR(3),@SIRA int
AS
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,2,2)=tipdatakod COLLATE Turkish_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,6,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,10,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,14,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
--5
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,18,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,22,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,26,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
--8
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,30,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,34,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,38,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
--11
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,42,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,46,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,50,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
--14
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,54,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,58,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,62,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA

UNION ALL
--17
SELECT DISKODLARI.kodu  AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,66,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,70,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,74,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
--20
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,78,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,82,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,86,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
UNION ALL
SELECT DISKODLARI.kodu AS DISKOD,adi AS DIS1 from HIZIL 
INNER JOIN DISKODLARI ON SUBSTRING(NAME1,90,2)=tipdatakod COLLATE SQL_Latin1_General_CP1254_CI_AS
WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRA
--24





