


CREATE PROCEDURE [dbo].[SAGLIKNET_ANA_EKTANI] @KNR VARCHAR(6),@SNR VARCHAR(3)
AS

SELECT TA.KNR,TA.SNR,TA.GELIS_TARIHI,ICD.ICD_KODU AS ICDKODU,ICD.ICD_ADI AS ICDADI,
ISNULL(replace(convert(varchar,TA.OZSOYGECMIS),'<','('),'YOK') AS HIKAYE,
ISNULL(replace(convert(varchar,TA.MUAYENEBULGULARI),'<','('),'YOK') AS BULGU,
ISNULL(replace(convert(varchar,TA.SISTEMSORGULARI),'<','('),'YOK') AS SIKAYET
FROM         TET_ANAMNEZ TA
INNER JOIN (SELECT KNR,SNR,TESHISKODU FROM TET_ANAMNEZ_DETAY) TAD ON TAD.KNR=TA.KNR AND TAD.SNR=TA.SNR
INNER JOIN (SELECT ICD_ADI,ICD_KODU  FROM SAGLIKNET_ICDXML) ICD ON ICD.ICD_KODU=SUBSTRING(TAD.TESHISKODU,3,5)
WHERE TA.KNR=@KNR AND TA.SNR=@SNR
--WHERE TA.KNR='756363'AND TA.SNR='999'

/*
--ESKİ SİSTEM
SELECT TA.KNR,TA.SNR,TA.GELIS_TARIHI,ICD.SLB AS ICDKODU,ICD.SLT AS ICDADI,
ISNULL(replace(convert(varchar,TA.OZSOYGECMIS),'<','('),'YOK') AS HIKAYE,
ISNULL(replace(convert(varchar,TA.MUAYENEBULGULARI),'<','('),'YOK') AS BULGU,
ISNULL(replace(convert(varchar,TA.SISTEMSORGULARI),'<','('),'YOK') AS SIKAYET
FROM         TET_ANAMNEZ TA
INNER JOIN (SELECT KNR,SNR,TESHISKODU FROM TET_ANAMNEZ_DETAY) TAD ON TAD.KNR=TA.KNR AND TAD.SNR=TA.SNR
INNER JOIN (SELECT SUBSTRING(SLB,3,6) AS SLB,SLT FROM  dbo.KEYDAT WHERE SLK = '32' GROUP BY SUBSTRING(SLB,3,6), SLT) ICD ON ICD.SLB=SUBSTRING(TAD.TESHISKODU,3,5)
WHERE TA.KNR=@KNR AND TA.SNR=@SNR
ORDER BY ICD.SLB
*/