

CREATE PROCEDURE [dbo].[SAGLIKNET_TETKIKLER] @KNR VARCHAR(6), @SNR VARCHAR(3)
AS
--DECLARE @KNR VARCHAR(6), @SNR VARCHAR(3)
--SET @KNR='028773'
--SET @SNR='999'
SELECT HZT.BKODU,HZT.NAME1 FROM BEHAND B
INNER JOIN (select KNR,SNR,TANIM,GRUP,CODE FROM HIZIL) H ON H.KNR=B.KNR AND H.SNR=B.SNR
INNER JOIN (SELECT TANIM,GRUP,CODE,BKODU,NAME1 FROM HIZMET WHERE LEN(ISNULL(BKODU,0))>1) HZT ON HZT.TANIM=H.TANIM AND HZT.GRUP=H.GRUP AND HZT.CODE=H.CODE
INNER JOIN (SELECT SLB FROM KEYDAT WHERE SLK='01' AND SLX IN('1','2')) K ON K.SLB=H.TANIM
WHERE  B.AMBU IN('P','A') AND B.KNR=@KNR AND B.SNR=@SNR


