

CREATE PROCEDURE [dbo].[SAGLIKNET_RECETEBUL] @KNR VARCHAR(6),@SNR VARCHAR(3)
AS
SELECT * FROM HASTA_RECETE
--INNER JOIN  ICDLER ON ICDLER.SLB=TAD.TESHISKODU
WHERE KNR=@KNR AND SNR=@SNR AND (ISNULL(PERIOD,0)>0) AND (PERIODBRIM IS NOT NULL) AND (KULLANIMSEKLI IS NOT NULL) AND (ISNULL(ADET,0)>0)
AND (RECETETUR IS NOT NULL) AND (CODE IS NOT NULL)

