

CREATE PROCEDURE [dbo].[SAGLIKNETEKLEGUNCELLE] @KNR VARCHAR(10),@SNR VARCHAR(10) ,@SIRANO  INT,@GUID  VARCHAR(50),@TUR VARCHAR(10)
AS
DECLARE @SONUC  VARCHAR(50)
SELECT @SONUC=(SELECT COUNT(*) FROM HIZILGONSAGNET WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRANO) 
FROM HIZILGONSAGNET
IF @SONUC=1
UPDATE HIZILGONSAGNET SET GUID=@GUID WHERE KNR=@KNR AND SNR=@SNR AND SIRANO=@SIRANO
ELSE
INSERT INTO HIZILGONSAGNET (KNR,SNR,SIRANO,GUID,TUR) VALUES(@KNR,@SNR,@SIRANO,@GUID,@TUR)

