

CREATE PROCEDURE [dbo].[SAGLIKNET_YATANHAST] @ILKTAR VARCHAR(10),@SONTAR VARCHAR(10)
AS
SELECT KNR,SNR,BHDAT,ARZT,AMBU FROM BEHAND 
INNER JOIN (SELECT SLB AS DRKOD ,SLXX AS DRSERVIS FROM KEYDAT WHERE SLK='07') DR ON  BEHAND.ARZT=DR.DRKOD
INNER JOIN (SELECT * FROM KEYDAT WHERE SLK='17') SERVIS ON  DR.DRSERVIS=SERVIS.SLB
WHERE AMBU='Y' AND CONVERT(VARCHAR,BEHAND.BHDAT,112) BETWEEN @ILKTAR AND @SONTAR



