



CREATE PROCEDURE [dbo].[SAGLIKNET_GONDERILMEYEN_MUAYENE] @ILKTAR VARCHAR(10),@SONTAR VARCHAR(10)
AS
SELECT     BEHAND.KNR, BEHAND.SNR, BEHAND.BHDAT, BEHAND.CIKTAR,BEHAND.PROTOKOLNO
FROM         BEHAND LEFT OUTER JOIN
                      HIZILGONSAGNET ON BEHAND.KNR = HIZILGONSAGNET.KNR AND BEHAND.SNR = HIZILGONSAGNET.SNR
WHERE     (HIZILGONSAGNET.KNR IS NULL)  AND (CONVERT(VARCHAR(10),BHDAT,112) BETWEEN @ILKTAR AND @SONTAR)






