

CREATE PROCEDURE [dbo].[SAGLIKNET_SEVKTANI] @KNR VARCHAR(6),@SNR VARCHAR(3)
AS
SELECT KNR,SNR,TESHISKODU AS ICDKODU,ICDLER.SLB AS TANIADI FROM TET_ANAMNEZ_DETAY TAD
INNER JOIN  ICDLER ON ICDLER.SLB=TAD.TESHISKODU
WHERE KNR=@KNR AND SNR=@SNR




