


CREATE PROCEDURE [dbo].[SP_BAKIYE] @HN VARCHAR(6)
AS
DECLARE @BB FLOAT,@KB FLOAT,@H VARCHAR(6)

SET @BB = ( 
select SUM(MTOPT) AS T 
from BEHAND
where KNR=@HN and MTOPT>0
GROUP BY KNR)

SET @KB = (
select -- TARIH, MAKBUZTIPI,BORCALACAK, 
(SUM(CASE BORCALACAK WHEN 'B' THEN TUTAR ELSE 0 END) -
 SUM(CASE BORCALACAK WHEN 'A' THEN TUTAR ELSE 0 END)) AS B
from KASA where KNR=@HN and ISIPTAL is null
GROUP BY KNR)

SELECT
 (@BB-@KB) AS S


