








CREATE PROCEDURE sp_MedulaV3FaturaAnamnez @basvuruno varchar(15)
as
select  substring(substring(RTRIM(ONTANI),1,250)+' '+substring(RTRIM(CONVERT(VARCHAR(250),TESHISVETEDAVI)),1,250),1,250) AS sonucaciklama
,BH.TAKIPNO ,TA.PROTNO ,BH.TABKODU from BEHAND  BH 
LEFT join BEHAND_DETAY  BD ON BD.KNR = BH.KNR AND    BH.SNR = BD.SNR
LEFT join TET_ANAMNEZ  TA ON TA.KNR = BD.KNR AND    TA.SNR = BD.SNR AND BD.GELISTARIHI=TA.GELIS_TARIHI
WHERE  BH.HASTABASNO=@basvuruno and BH.TAKIPNO<>'' AND BH.TAKIPSEND='1' AND BD.EKSORGU='H' AND BD.KONT IS NULL







