
CREATE procedure [dbo].[WEBLABONAY] @KNR VARCHAR(6)
AS
--DECLARE @KNR VARCHAR(6)
--SET @KNR='053294'
SELECT CONVERT(VARCHAR,BHDAT,104) AS BHDAT,KEYDAT.SLT,KEYDAT1.SLT,B.SNR
FROM LBISTE L, BEHAND B ,KEYDAT AS KEYDAT ,KEYDAT AS KEYDAT1
where  B.KNR=L.KNR AND B.SNR=L.SNR AND  B.KNR=@KNR  AND 
KEYDAT.SLB=B.ARZT AND KEYDAT.SLK='07' AND KEYDAT1.SLB=B.SERVIS AND KEYDAT1.SLK='17'
GROUP BY BHDAT,B.SNR,KEYDAT.SLT,KEYDAT1.SLT
order by B.SNR DESC