


CREATE procedure [dbo].[WEBLABHASTA] @KNR VARCHAR(6)
AS
--DECLARE @KNR VARCHAR(6)
--SET @KNR='053294'
SELECT  KNR, CASE WHEN CINSIYETI=1 THEN 'Erkek' else 'Kadın' END CINSIYETI , HASTAADI, HASTASOYADI, 
CONVERT(CHAR,DOGUMTARIHI,104) AS DOGUMTARIHI,TCKIMLIKNO,SIGORTANO,PSG
FROM         ADRES
WHERE     (KNR = @KNR)



