CREATE NONCLUSTERED INDEX [IX_ILACSARF_2]
    ON [dbo].[ILACSARF]([AKOD] ASC, [TANIM] ASC, [GRUP] ASC, [FAR_KOD] ASC, [NAME1] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

