CREATE NONCLUSTERED INDEX [IX_KULLANICI_YETKI_4]
    ON [dbo].[KULLANICI_YETKI]([USER_ID] ASC, [FORMNAME] ASC, [TABNUMBER] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

