CREATE NONCLUSTERED INDEX [IX_LBISTE1_Y]
    ON [dbo].[LBISTE]([TANIM] ASC, [GRUP] ASC, [CODE] ASC, [KABUL_NO] ASC, [KABUL] ASC, [ONAY] ASC, [ONAY_TARIH] ASC, [DRONAY] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

