CREATE NONCLUSTERED INDEX [IX_NX_HAREKETLER_KULLANICI_DEPO_BELGE]
    ON [dbo].[NX_HAREKETLER]([KULLANICI_KODU] ASC, [GIRIS_DEPOSU] ASC, [BELGE_NO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

