CREATE NONCLUSTERED INDEX [IX_SCARI_5]
    ON [dbo].[SCARI]([KNR] ASC, [KOD] ASC, [MEDFATURATARIHI] ASC, [BK] ASC, [B_A] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

