SELECT DISTINCT tlkpvDoctor.SLT, tlkpvService.SLT, ISNULL(sq1.SGKHastaSayisi, 0) as SGKHastaSayisi, ISNULL(sq2.OzelHastaSayisi, 0) as OzelHastaSayisi
FROM tlkpvDoctor 
	INNER JOIN tlkpvService ON tlkpvDoctor.SLXX = tlkpvService.SLB
	INNER JOIN OTOMATIK_MUAYENELER ON tlkpvService.SLB = OTOMATIK_MUAYENELER.SERVISKODU

	LEFT JOIN 
	(SELECT DISTINCT BEHAND.ARZT, COUNT(BEHAND.KNR) as SGKHastaSayisi
		FROM BEHAND  
	INNER JOIN KURADR ON BEHAND.PSG = KURADR.PSG
	WHERE (BEHAND.BHDAT Between '20110801' And '20110802') AND BEHAND.AMBU='P' AND KURADR.lngKurumTipiID = 1
	GROUP BY BEHAND.ARZT)  sq1 ON tlkpvDoctor.SLB = sq1.ARZT

	LEFT JOIN 
	(SELECT DISTINCT BEHAND.ARZT, COUNT(BEHAND.KNR) as OzelHastaSayisi
		FROM BEHAND  
	INNER JOIN KURADR ON BEHAND.PSG = KURADR.PSG
	WHERE (BEHAND.BHDAT Between '20110801' And '20110802') AND BEHAND.AMBU='P' AND KURADR.lngKurumTipiID <> 1
	GROUP BY BEHAND.ARZT)  sq2 ON tlkpvDoctor.SLB = sq2.ARZT
	
WHERE tlkpvDoctor.SLY=0 
GROUP BY tlkpvDoctor.SLT, tlkpvService.SLT, ISNULL(sq1.SGKHastaSayisi, 0), ISNULL(sq2.OzelHastaSayisi, 0)
