-- OLMASINI ÝSTEDÝÐÝNÝZ GRUP KODUNU GRUP='' YAZAN YERE YAZMANIZ GEREKÝYOR.

UPDATE ILACSARF SET GRUP='002' WHERE CODE='DEÐÝÞTÝRÝLECEK ÝLACIN KODU'
UPDATE SHARK SET GRUP='002' WHERE CODE='DEÐÝÞTÝRÝLECEK ÝLACIN KODU' AND 
UPDATE HIZIL SET GRUP='002' WHERE CODE='DEÐÝÞTÝRÝLECEK ÝLACIN KODU'
UPDATE SATHIZ SET GRUP='002' WHERE CODE='DEÐÝÞTÝRÝLECEK ÝLACIN KODU'
UPDATE KURHIZIL SET GRUP='002' WHERE CODE='DEÐÝÞTÝRÝLECEK ÝLACIN KODU'
UPDATE LOGHIZILDELETED SET GRUP='002' WHERE CODE='DEÐÝÞTÝRÝLECEK ÝLACIN KODU'
UPDATE ECZDEVIRILACSARF SET GRUP='002' WHERE CODE='DEÐÝÞTÝRÝLECEK ÝLACIN KODU'
UPDATE LOGHIZILDOKTORDEGISTI SET GRUP='002' WHERE CODE='DEÐÝÞTÝRÝLECEK ÝLACIN KODU'

