
UPDATE SATHIZ (NOLOCK) SET SATHIZ.GRUP=I.GRUP
FROM SATHIZ SH INNER JOIN tblvIlacSarfAna I ON SH.TANIM = I.TANIM and SH.CODE = I.CODE
WHERE SH.TANIM = '09'

UPDATE HIZIL SET HIZIL.GRUP=I.GRUP
FROM HIZIL H (NOLOCK) INNER JOIN tblvIlacSarfAna I ON H.TANIM = I.TANIM and H.CODE = I.CODE
WHERE H.TANIM = '09'

