//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace Naz.Hastane.Medula.FaturaKayitIslemleriWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FaturaKayitIslemleriSoapBinding", Namespace="http://servisler.ws.gss.sgk.gov.tr")]
    public partial class FaturaKayitIslemleriService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback faturaOkuOperationCompleted;
        
        private System.Threading.SendOrPostCallback faturaIptalOperationCompleted;
        
        private System.Threading.SendOrPostCallback faturaKayitOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FaturaKayitIslemleriService() {
            this.Url = global::Naz.Hastane.Medula.Properties.Settings.Default.Naz_Medula_FaturaKayitIslemleri_FaturaKayitIslemleriService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event faturaOkuCompletedEventHandler faturaOkuCompleted;
        
        /// <remarks/>
        public event faturaIptalCompletedEventHandler faturaIptalCompleted;
        
        /// <remarks/>
        public event faturaKayitCompletedEventHandler faturaKayitCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servisler.ws.gss.sgk.gov.tr", ResponseNamespace="http://servisler.ws.gss.sgk.gov.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("faturaOkuReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public FaturaOkuCevapDVO faturaOku([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] FaturaOkuGirisDVO faturaOkuGiris) {
            object[] results = this.Invoke("faturaOku", new object[] {
                        faturaOkuGiris});
            return ((FaturaOkuCevapDVO)(results[0]));
        }
        
        /// <remarks/>
        public void faturaOkuAsync(FaturaOkuGirisDVO faturaOkuGiris) {
            this.faturaOkuAsync(faturaOkuGiris, null);
        }
        
        /// <remarks/>
        public void faturaOkuAsync(FaturaOkuGirisDVO faturaOkuGiris, object userState) {
            if ((this.faturaOkuOperationCompleted == null)) {
                this.faturaOkuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfaturaOkuOperationCompleted);
            }
            this.InvokeAsync("faturaOku", new object[] {
                        faturaOkuGiris}, this.faturaOkuOperationCompleted, userState);
        }
        
        private void OnfaturaOkuOperationCompleted(object arg) {
            if ((this.faturaOkuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.faturaOkuCompleted(this, new faturaOkuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servisler.ws.gss.sgk.gov.tr", ResponseNamespace="http://servisler.ws.gss.sgk.gov.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("faturaIptalReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public FaturaIptalCevapDVO faturaIptal([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] FaturaIptalGirisDVO faturaIptalGiris) {
            object[] results = this.Invoke("faturaIptal", new object[] {
                        faturaIptalGiris});
            return ((FaturaIptalCevapDVO)(results[0]));
        }
        
        /// <remarks/>
        public void faturaIptalAsync(FaturaIptalGirisDVO faturaIptalGiris) {
            this.faturaIptalAsync(faturaIptalGiris, null);
        }
        
        /// <remarks/>
        public void faturaIptalAsync(FaturaIptalGirisDVO faturaIptalGiris, object userState) {
            if ((this.faturaIptalOperationCompleted == null)) {
                this.faturaIptalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfaturaIptalOperationCompleted);
            }
            this.InvokeAsync("faturaIptal", new object[] {
                        faturaIptalGiris}, this.faturaIptalOperationCompleted, userState);
        }
        
        private void OnfaturaIptalOperationCompleted(object arg) {
            if ((this.faturaIptalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.faturaIptalCompleted(this, new faturaIptalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servisler.ws.gss.sgk.gov.tr", ResponseNamespace="http://servisler.ws.gss.sgk.gov.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("faturaKayitReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public FaturaCevapDVO faturaKayit([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] FaturaGirisDVO faturaGiris) {
            object[] results = this.Invoke("faturaKayit", new object[] {
                        faturaGiris});
            return ((FaturaCevapDVO)(results[0]));
        }
        
        /// <remarks/>
        public void faturaKayitAsync(FaturaGirisDVO faturaGiris) {
            this.faturaKayitAsync(faturaGiris, null);
        }
        
        /// <remarks/>
        public void faturaKayitAsync(FaturaGirisDVO faturaGiris, object userState) {
            if ((this.faturaKayitOperationCompleted == null)) {
                this.faturaKayitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfaturaKayitOperationCompleted);
            }
            this.InvokeAsync("faturaKayit", new object[] {
                        faturaGiris}, this.faturaKayitOperationCompleted, userState);
        }
        
        private void OnfaturaKayitOperationCompleted(object arg) {
            if ((this.faturaKayitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.faturaKayitCompleted(this, new faturaKayitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaOkuGirisDVO {
        
        private string faturaRefNoField;
        
        private string faturaTarihiField;
        
        private string faturaTeslimNoField;
        
        private int saglikTesisKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string faturaRefNo {
            get {
                return this.faturaRefNoField;
            }
            set {
                this.faturaRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string faturaTarihi {
            get {
                return this.faturaTarihiField;
            }
            set {
                this.faturaTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string faturaTeslimNo {
            get {
                return this.faturaTeslimNoField;
            }
            set {
                this.faturaTeslimNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int saglikTesisKodu {
            get {
                return this.saglikTesisKoduField;
            }
            set {
                this.saglikTesisKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaHataDVO {
        
        private string hataKoduField;
        
        private string hataMesajiField;
        
        private string takipNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hataKodu {
            get {
                return this.hataKoduField;
            }
            set {
                this.hataKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hataMesaji {
            get {
                return this.hataMesajiField;
            }
            set {
                this.hataMesajiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string takipNo {
            get {
                return this.takipNoField;
            }
            set {
                this.takipNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaDetayDVO {
        
        private IslemDetayDVO[] islemDetaylariField;
        
        private string takipNoField;
        
        private double takipToplamTutarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IslemDetayDVO[] islemDetaylari {
            get {
                return this.islemDetaylariField;
            }
            set {
                this.islemDetaylariField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string takipNo {
            get {
                return this.takipNoField;
            }
            set {
                this.takipNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double takipToplamTutar {
            get {
                return this.takipToplamTutarField;
            }
            set {
                this.takipToplamTutarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class IslemDetayDVO {
        
        private string islemSiraNoField;
        
        private double islemTutariField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string islemSiraNo {
            get {
                return this.islemSiraNoField;
            }
            set {
                this.islemSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double islemTutari {
            get {
                return this.islemTutariField;
            }
            set {
                this.islemTutariField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaCevapDVO {
        
        private string faturaRefNoField;
        
        private FaturaDetayDVO[] faturaDetaylariField;
        
        private string faturaTeslimNoField;
        
        private double faturaTutariField;
        
        private string hastaBasvuruNoField;
        
        private FaturaHataDVO[] hataliKayitlarField;
        
        private string sonucKoduField;
        
        private string sonucMesajiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string faturaRefNo {
            get {
                return this.faturaRefNoField;
            }
            set {
                this.faturaRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FaturaDetayDVO[] faturaDetaylari {
            get {
                return this.faturaDetaylariField;
            }
            set {
                this.faturaDetaylariField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string faturaTeslimNo {
            get {
                return this.faturaTeslimNoField;
            }
            set {
                this.faturaTeslimNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double faturaTutari {
            get {
                return this.faturaTutariField;
            }
            set {
                this.faturaTutariField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hastaBasvuruNo {
            get {
                return this.hastaBasvuruNoField;
            }
            set {
                this.hastaBasvuruNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FaturaHataDVO[] hataliKayitlar {
            get {
                return this.hataliKayitlarField;
            }
            set {
                this.hataliKayitlarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sonucKodu {
            get {
                return this.sonucKoduField;
            }
            set {
                this.sonucKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sonucMesaji {
            get {
                return this.sonucMesajiField;
            }
            set {
                this.sonucMesajiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class HizmetDetayDVO {
        
        private string aciklamaField;
        
        private string protokolNoField;
        
        private string taburcuKoduField;
        
        private string takipNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string protokolNo {
            get {
                return this.protokolNoField;
            }
            set {
                this.protokolNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string taburcuKodu {
            get {
                return this.taburcuKoduField;
            }
            set {
                this.taburcuKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string takipNo {
            get {
                return this.takipNoField;
            }
            set {
                this.takipNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaGirisDVO {
        
        private string faturaRefNoField;
        
        private string faturaTarihiField;
        
        private string hastaBasvuruNoField;
        
        private HizmetDetayDVO[] hizmetDetaylariField;
        
        private int saglikTesisKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string faturaRefNo {
            get {
                return this.faturaRefNoField;
            }
            set {
                this.faturaRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string faturaTarihi {
            get {
                return this.faturaTarihiField;
            }
            set {
                this.faturaTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hastaBasvuruNo {
            get {
                return this.hastaBasvuruNoField;
            }
            set {
                this.hastaBasvuruNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HizmetDetayDVO[] hizmetDetaylari {
            get {
                return this.hizmetDetaylariField;
            }
            set {
                this.hizmetDetaylariField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int saglikTesisKodu {
            get {
                return this.saglikTesisKoduField;
            }
            set {
                this.saglikTesisKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaIptalHataliKayitDVO {
        
        private string faturaTeslimNoField;
        
        private string hataKoduField;
        
        private string hataMesajiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string faturaTeslimNo {
            get {
                return this.faturaTeslimNoField;
            }
            set {
                this.faturaTeslimNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hataKodu {
            get {
                return this.hataKoduField;
            }
            set {
                this.hataKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hataMesaji {
            get {
                return this.hataMesajiField;
            }
            set {
                this.hataMesajiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaIptalCevapDVO {
        
        private FaturaIptalHataliKayitDVO[] hataliKayitlarField;
        
        private string sonucKoduField;
        
        private string sonucMesajiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FaturaIptalHataliKayitDVO[] hataliKayitlar {
            get {
                return this.hataliKayitlarField;
            }
            set {
                this.hataliKayitlarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sonucKodu {
            get {
                return this.sonucKoduField;
            }
            set {
                this.sonucKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sonucMesaji {
            get {
                return this.sonucMesajiField;
            }
            set {
                this.sonucMesajiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaIptalGirisDVO {
        
        private string[] faturaTeslimNoField;
        
        private int saglikTesisKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] faturaTeslimNo {
            get {
                return this.faturaTeslimNoField;
            }
            set {
                this.faturaTeslimNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int saglikTesisKodu {
            get {
                return this.saglikTesisKoduField;
            }
            set {
                this.saglikTesisKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaCevapDetayDVO {
        
        private string aciklamaField;
        
        private IslemDetayDVO[] islemDetaylariField;
        
        private string protokolNoField;
        
        private string taburcuKoduField;
        
        private string takipNoField;
        
        private double takipToplamTutarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IslemDetayDVO[] islemDetaylari {
            get {
                return this.islemDetaylariField;
            }
            set {
                this.islemDetaylariField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string protokolNo {
            get {
                return this.protokolNoField;
            }
            set {
                this.protokolNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string taburcuKodu {
            get {
                return this.taburcuKoduField;
            }
            set {
                this.taburcuKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string takipNo {
            get {
                return this.takipNoField;
            }
            set {
                this.takipNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double takipToplamTutar {
            get {
                return this.takipToplamTutarField;
            }
            set {
                this.takipToplamTutarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dvo.gss.sgk.gov.tr")]
    public partial class FaturaOkuCevapDVO {
        
        private FaturaCevapDetayDVO[] faturaDetaylariField;
        
        private string faturaRefNoField;
        
        private string faturaTarihiField;
        
        private string faturaTeslimNoField;
        
        private double faturaTutariField;
        
        private string sonucKoduField;
        
        private string sonucMesajiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FaturaCevapDetayDVO[] faturaDetaylari {
            get {
                return this.faturaDetaylariField;
            }
            set {
                this.faturaDetaylariField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string faturaRefNo {
            get {
                return this.faturaRefNoField;
            }
            set {
                this.faturaRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string faturaTarihi {
            get {
                return this.faturaTarihiField;
            }
            set {
                this.faturaTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string faturaTeslimNo {
            get {
                return this.faturaTeslimNoField;
            }
            set {
                this.faturaTeslimNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double faturaTutari {
            get {
                return this.faturaTutariField;
            }
            set {
                this.faturaTutariField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sonucKodu {
            get {
                return this.sonucKoduField;
            }
            set {
                this.sonucKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sonucMesaji {
            get {
                return this.sonucMesajiField;
            }
            set {
                this.sonucMesajiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void faturaOkuCompletedEventHandler(object sender, faturaOkuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class faturaOkuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal faturaOkuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FaturaOkuCevapDVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FaturaOkuCevapDVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void faturaIptalCompletedEventHandler(object sender, faturaIptalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class faturaIptalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal faturaIptalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FaturaIptalCevapDVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FaturaIptalCevapDVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void faturaKayitCompletedEventHandler(object sender, faturaKayitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class faturaKayitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal faturaKayitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FaturaCevapDVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FaturaCevapDVO)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591