
CREATE TRIGGER [OZELDURUM_UPDATE] ON [dbo].[TET_ANAMNEZ_DETAY] 
FOR INSERT
AS

DECLARE @KNR VARCHAR(6) , @SNR VARCHAR(3), @TESHISKODU VARCHAR(10)

SELECT @KNR=KNR , @SNR=SNR , @TESHISKODU=TESHISKODU  FROM INSERTED

BEGIN

UPDATE HIZIL SET HIZIL.MEDOZDURUM='8'
FROM HIZIL,HIZMET,KATILIM_PAYI_MUAF_TESHISLER,INSERTED
WHERE @KNR=HIZIL.KNR
AND @SNR=HIZIL.SNR
AND @TESHISKODU LIKE '%'+KATILIM_PAYI_MUAF_TESHISLER.TESHISKODU+'%'
AND HIZIL.TANIM=HIZMET.TANIM AND HIZIL.GRUP=HIZMET.GRUP AND HIZIL.CODE=HIZMET.CODE
AND (HIZIL.MEDOZDURUM='' OR HIZIL.MEDOZDURUM IS NULL)
AND HIZMET.MBASLIK=5 

END
