CREATE TRIGGER [TRG_IND_DETAY] ON [dbo].[HASTAINDIRIMLER_DETAY] 
FOR INSERT, DELETE 
AS


DECLARE  @KNR VARCHAR(6),@SNR VARCHAR(3), @SIRANO FLOAT(8) , @ESATISF FLOAT(8) 

SELECT @KNR=KNR , @SNR=SNR , @SIRANO=SIRANO , @ESATISF=ESATISF FROM INSERTED

BEGIN

UPDATE HIZIL SET HIZIL.ESKI_SATISF=ROUND(@ESATISF,2)
FROM HIZIL,INSERTED
WHERE @KNR=HIZIL.KNR AND
@SNR=HIZIL.SNR AND
@SIRANO=HIZIL.SIRANO

END




