CREATE TRIGGER [TRG_IND_DETAY_DEL] ON [dbo].[HASTAINDIRIMLER_DETAY] 
FOR DELETE 
AS


DECLARE  @KNR VARCHAR(6),@SNR VARCHAR(3), @SIRANO FLOAT(8) , @ESATISF FLOAT(8) 

SELECT @KNR=KNR , @SNR=SNR , @SIRANO=SIRANO , @ESATISF=ESATISF FROM DELETED

BEGIN

UPDATE HIZIL SET HIZIL.ESKI_SATISF=NULL
FROM HIZIL,DELETED
WHERE DELETED.KNR=HIZIL.KNR AND
DELETED.SNR=HIZIL.SNR AND
DELETED.SIRANO=HIZIL.SIRANO

END






